### ISSUE TITLE
Option to disable or enable ability to take screenshots

### ISSUE THREAD

**Issue by gigabytedevelopersinc** [andOTP/andOTP#100]
So, I've been messing around with andOTP trying to see if there are any issues with it or detect any bugs. Well, nothing so far! 
But about the disabled ability for users to take screenshots, I personally think it's a nice feature but shouldn't be so on default, so I think that there should be option in the settings page that toggles on/off the ability to take screenshots on andOTP! 
Just a humble suggestion!

**Comment by RichyHBM** [comment]
There already is, it is hidden in the secret features.

Have a look in the wiki for the secret features and how to enable them, then the screenshot option will appear in settings (I'm on my phone so can't link to it)

**Comment by protist** [comment]
To save others time searching:
1. Enable secret features as per the [wiki](https://github.com/andOTP/andOTP/wiki/Special-features)
2. Open `Settings`, and check the second last box
