### ISSUE TITLE
Too many duplicates of the default icon in the Thumbnail Selector

### ISSUE THREAD

**Issue by gigabytedevelopersinc** [andOTP/andOTP#103]
I noticed a count of about 4-6 default icons in the section to select a new thumbnail image
I believe this is a bug as I have had a little look at the EntryThumbnail.java file and can't seem to see the cause of this problem

**Comment by RichyHBM** [comment]
Will take a look at this tonight

**Comment by RichyHBM** [comment]
@gigabytedevelopersinc I suspect its failing to load some of the thumbnails but I cant repro.
Could you post a screenshot and let me know what version of the app you are running? (Play store, test, custom build...)

**Comment by gigabytedevelopersinc** [comment]
There you go! 
Haven't had time to turn on Android Studio lately, I and my team would have found a way to help out! 
![screenshot_2018-01-04-07-13-52](https://user-images.githubusercontent.com/26210471/34552036-34991208-f11f-11e7-9862-c95e4020395d.png)
![screenshot_2018-01-04-07-13-45](https://user-images.githubusercontent.com/26210471/34552037-350ceee4-f11f-11e7-9079-00e373f86419.png)

**Comment by gigabytedevelopersinc** [comment]
And Yes, this happens in all the versions ever since the Thumbnail feature was added!

**Comment by gigabytedevelopersinc** [comment]
Then also, you mentioned that u suspect this is happening because it's failing to load some of the other thumbnails. Well, for once, I also thought the same way but after going through the code, surprise 😲, all the Thumbnails (at least based on what am seeing in the EntryThumbnail.java) are there, it's only the Default (ic_launcher) icon that is duplicated

**Comment by gigabytedevelopersinc** [comment]
About what phone am using. Well, my phone isn't so common but am running on Android 5.1 (HiOS). 
Then, my computer isn't within reach, so am not so sure I can send a logcat now.

**Comment by RichyHBM** [comment]
Yes, so the app will load up the app icon as a thumbnail when the code that converts a vector image into a drawable fails, it should print out a stack trace when this happens.

Having looked at the images that are failing to load I suspect this is a device/os specific issue and is failing because those images have gradient effects in them, but with out a log cat I'm just guessing really..

**Comment by gigabytedevelopersinc** [comment]
Honestly, I've counted them all, I don't think there are any images that
are failing to load!
All the available thumbnails are displayed there! It's only the Default
icon that appears more than once!
N/B: I've tried this on several other devices with different Android
versions too, same thing happens. Don't know why!

**Comment by RichyHBM** [comment]
Well some of them are failing to load, eg you have no bitcoin or origin thumbnail in the screenshot, instead you have the default app icon in their place.

Are you able to build from source? If I can't manage to repro it I may make a branch with the gradient elements removed from the vector images and see if that fixes it

**Comment by gigabytedevelopersinc** [comment]
Ok. That's right, I don't have blockchain, origin and some others!
Since I have Android Studio, I believe I should be able to build from
source!
Meanwhile, if I try and provide a logcat, would there still be need to
create a branch as I don't want to stress you guys so much about this since
it seems to be an issue with the OS or something!

**Comment by RichyHBM** [comment]
Well, with the log cat I can hopefully diagnose. That will determine how big of a task this could be 😅

**Comment by gigabytedevelopersinc** [comment]
Ok... I git cloned the repository and used it to start a small project. 
I had followed your directives, though I don't know much about vectors, but I managed to get rid of the gradients and surprise 😲, it worked, no more duplicates! 😂.
The defaulted vectors (thumbnails) were: Bitcoin, Origin, RSS, Skrill and TeamViewer, everything seems to be working just fine now. 
Do I make a pull request later this evening, or do I leave you to it, since it's a simple fix? 
With or without the gradient, the icons still look good and intact! 
![screenshot_2018-01-04-12-55-52](https://user-images.githubusercontent.com/26210471/34563171-cef91776-f151-11e7-9d07-b688e313d30f.png)
![screenshot_2018-01-04-12-55-11](https://user-images.githubusercontent.com/26210471/34563175-d38640ca-f151-11e7-8bcf-cee97d169233.png)
![screenshot_2018-01-04-12-54-56](https://user-images.githubusercontent.com/26210471/34563182-db536774-f151-11e7-984d-7e42abee10c1.png)

**Comment by RichyHBM** [comment]
Great work!! 

Feel free to leave it for me if you want, I'll give all the icons a pass and make sure they look as close to how they already do! And I can just chuck it into the current thumbnails branch 😄

Interesting thing to have found out, will be good to keep in mind in the future!

**Comment by RichyHBM** [comment]
Also @gigabytedevelopersinc, is the screen on your device really low resolution? The icons look awfully janky!

**Comment by gigabytedevelopersinc** [comment]
Kikikikiki! 😂 😂 😂. Ya ya, it's got nothing to do with the icons, it's a
problem with my phone, whenever the brightness is set to Automatic and
there isn't enough light, the screenshots taken would end up looking weird
and messed up! 😂

**Comment by gigabytedevelopersinc** [comment]
Good! Do it yourself! I actually need a little more time to study github!
😂
**winks** 😉

**Comment by RichyHBM** [comment]
I'm going to close this bug as a fix is in a PR, it will get merged in when the next batch of icons come in.
If you still get this issue after the next update (or if you can clone the thumbnails branch and test it) feel free to reopen it!
