### ISSUE TITLE
Add HackerOne icon

### ISSUE THREAD

**Issue by schiessle** [andOTP/andOTP#104]
First let me say thank you for this great app. I use it every day! 😃  

Now my small feature request: It would be nice to have a hackerone (https://www.hackerone.com/) icon.

**Comment by RichyHBM** [comment]
I'll add it in with the next batch of thumbnails!

**Comment by RichyHBM** [comment]
Added in #97, I'm going to close this issue as it will get pulled across when that PR gets merged
