### ISSUE TITLE
[information] linux client available

### ISSUE THREAD

**Issue by paolostivanin** [andOTP/andOTP#105]
Hello,
I developed a [GTK+ OTP client](https://github.com/paolostivanin/OTPClient) for Linux that supports importing andOTP (password) encrypted backups.
If you find this info useful I could open a PR for updating the README. Otherwise feel free to just close this :)

PS in case you change the backup format, please let me know :+1: 

BR

**Comment by flocke** [comment]
Nice, I will definitely add a link somewhere, either the README or the wiki. Will keep this open to remind me to do so.

**Comment by flocke** [comment]
I don't want to clutter the README even more, so I created a new page in the wiki: https://github.com/andOTP/andOTP/wiki/Open-Source-2FA-Apps
Anyone can feel free to add other 2FA Apps for different platforms, the only requirement is that they are open source.
