### ISSUE TITLE
Auto Backup / Schedule Backup

### ISSUE THREAD

**Issue by jerryn70** [andOTP/andOTP#11]
Option to schedule backup daily/every 2 days/weekly/monthly similar will be a good idea

**Comment by flocke** [comment]
I like the idea, but this will take some time to implement.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by flocke** [comment]
With the tagging support done this is on my TODO list for the next release.
 - [ ] Implement a BroadcastReceiver inside the BackupActivity to trigger automatic backups
 - [ ] (maybe) Implement a internal way to schedule the backups, it would maybe be easier to use external tools like [Easer](https://renyuneyun.github.io/Easer/en/) or Tasker for that

**Comment by RichyHBM** [comment]
Broadcast receivers are in PR #115, if I remember right I think we decided against having an internal recurring backup mechanism (@flocke to confirm) as there are free methods to accomplish this and it seems like a feature that isn't really core to a 2fa app

**Comment by flocke** [comment]
Yes, I think once the BroadcastReceivers are implemented the rest can easily be done with an external app. I'm totally fine with not having an internal way to schedule backups.

**Comment by SuperVirus** [comment]
I would suggest starting an automated backup after each change to the accounts.
Maybe this is easier to implement and should be a good strategy against data loss.

**Comment by RichyHBM** [comment]
Should be fairly easy to accomplish

**Comment by flocke** [comment]
@SuperVirus @RichyHBM I probably won't implement an automated backup after each change to the database. But I really like the idea that @hydrian proposed in #46: show a notification which, on click, takes you to the backup activity every time a major change (adding or removing of entries) of the database happened.

**Comment by drhus** [comment]
Auto backup definitely a must,but how about application data folder, https://developers.google.com/drive/api/v3/appdata like you manually backup download or save to drive but the automatic function to a hidden Data folder we don't delete accidentally and automatically discovered by andOTP when connecting drive in new phone

**Comment by flocke** [comment]
@drhus Something like this is already implemented. It's called "Enable Android sync" in the settings. But it only works with the password-based encryption and not when using the KeyStore (it can't backup the key in the keystore).

**Comment by drhus** [comment]
good the option is implemented, I didn't notice that however it seems to not be working I tried to Enable Android Sync, and setup andOTP on two different cellphone it's not working, not able to restore from new cell phone, different account

**Comment by RichyHBM** [comment]
It won't keep both accounts in sync, it is used so that if you lose/break your phone Google can restore settings

**Comment by RichyHBM** [comment]
Android also dictates when the OS performs these sync operations so we can't guarantee that the app has done it. I think that the toggle should be enabled by default when a pin/password is used though, one for @flocke to have a think about?

**Comment by himselfv** [comment]
@flocke: "show a notification which, on click, takes you to the backup activity"

Why not just allow an auto-backup at such points then? Notifications are annoying both to those who don't want a backup and to those who want auto-backup (just do it!). Just add an option to do it automatically.

**Comment by flocke** [comment]
I probably won't be implementing any of this since I plan to stop adding new features after the next stable release.
The reason for that is that I want to create a new OTP app from scratch. As you might know is that this app was created as a fork of [OTP Authenticator](https://github.com/0xbb/otp-authenticator) and when I started development it was my first Android project, so I only did small changes in the beginning. As it is now there is a lot of old code that I can't change anymore without breaking everything. Now that I got more experience in Android development I feel it would be more effective to re-write everything from scratch, which is what I will do when I find the time.

**Comment by bd8392** [comment]
> I probably won't be implementing any of this since I plan to stop adding new features after the next stable release.
> The reason for that is that I want to create a new OTP app from scratch. As you might know is that this app was created as a fork of [OTP Authenticator](https://github.com/0xbb/otp-authenticator) and when I started development it was my first Android project, so I only did small changes in the beginning. As it is now there is a lot of old code that I can't change anymore without breaking everything. Now that I got more experience in Android development I feel it would be more effective to re-write everything from scratch, which is what I will do when I find the time.

Hi :-) I just discovered andOTP and wanted to move to it (as authenticator pro stopped working for me). I just wanted to as if there are concrete plans for the new app, or do you develop this one further? :-) The option with scheduled backup would be really interesting to me :-)

**Comment by flocke** [comment]
> Hi :-) I just discovered andOTP and wanted to move to it (as authenticator pro stopped working for me). I just wanted to ask if there are concrete plans for the new app, or do you develop this one further? :-) The option with scheduled backup would be really interesting to me :-)

I have decided to stop the rewrite and continue developing andOTP instead. I don't have a lot of time and I want to focus on improving andOTP instead of creating something new from scratch. I will revisit the idea of scheduled backups at some point, but it's not very high on the todo list since you can already trigger backups using 3rd party apps like Tasker and do automatic backups after a new entry is added.

**Comment by bd8392** [comment]
I just switched to your solution, and absolutely love it! I come from authenticator pro (depricated) and it's perfect! As you have automatic-backups in place, I wouldn't need scheduled one :-). As the sake of the improvement for this variant, I would abandon the development of scheduled Backups :-). Instead this feature would be useful https://github.com/andOTP/andOTP/issues/701

Also a direct "cloud-connector" for the Backups (to stream to Google, Nextcloud etc) would be more of use than scheduled ones :-). I automatically sync with nextcloud over the nextcloud app :-). I also love the approach that the app stores the config in Google with their backup :-)
