### ISSUE TITLE
Whitespace between three figures

### ISSUE THREAD

**Issue by alexanderadam** [andOTP/andOTP#110]
Might be just a small issue:

I think it improves readability a bit if you there would be a whitespace between number triples (like Google Authenticator have it for example)

so it would be nice to have something like `343343` instead of `343343`

Thank you very much for your work 👍

**Comment by flocke** [comment]
This one was already requested in #83 and is implemented in PR #93.
I will merge it as soon as the custom-encryption branch is done.
