### ISSUE TITLE
Language switcher doesn't work

### ISSUE THREAD

**Issue by enwokoma** [andOTP/andOTP#112]
So I noticed that when I switch languages from the settings page, the screen of andOTP flashes but yet nothing happens, the language still remains in English, it just doesn't switch! 
Could this be a bug or what? Am quite confused 😕 because I noticed the strings for other languages exist in the source of andOTP but it doesn't work within the app, why?

**Comment by flocke** [comment]
Which language are you trying to switch to and which version are you using?

**Comment by enwokoma** [comment]
All of them and it's the latest version!

**Comment by flocke** [comment]
Strange, I just tried it with the last version on my phone (unreleased) and it works well. I haven't touched anything on the code since the initial release. Which Android version are you using?
@RichyHBM can you try the language changed on your phone and report back?

**Comment by RichyHBM** [comment]
@flocke Works fine on my phone, LineageOS 14.1 and the current play store version

**Comment by enwokoma** [comment]
Here you go! Running on 5.1 HiOS. 
![screenshot_2018-01-14-22-21-46](https://user-images.githubusercontent.com/26168869/34920827-8cf68df6-f979-11e7-83f6-37e6f148f9f3.png)
![screenshot_2018-01-14-22-21-35](https://user-images.githubusercontent.com/26168869/34920828-8d84e006-f979-11e7-8552-2e6e5e7799c4.png)
![screenshot_2018-01-14-22-21-25](https://user-images.githubusercontent.com/26168869/34920829-8e144e12-f979-11e7-9b00-f783f832891b.png)

Tried all languages, same problem!

**Comment by flocke** [comment]
Never heard, of HiOS before but it seems to be based on Android Lollipop. I'm gonna try the switcher in a Lollipop AVD later today.

**Comment by gigabytedevelopersinc** [comment]
Ya ya. It seems to be a problem of lollipop devices because I also tried it
on another lollipop device and it doesn't work still!

**Comment by flocke** [comment]
If it is a problem on all Lollipop devices I should be able to reproduce and debug it pretty easily.

**Comment by enwokoma** [comment]
I guess so too, could be an issue with lollipop!

**Comment by RichyHBM** [comment]
I was going to say, HiOS was the one giving problems for vectors with gradients. Maybe something wrong with the rom? Can you guys change language in other apps?

**Comment by enwokoma** [comment]
Sorry for the late reply, but yes, I am able to switch languages in other apps. 
![screenshot_2018-01-16-00-48-10](https://user-images.githubusercontent.com/26168869/34966809-e18cfd4c-fa5e-11e7-9ea5-0bda78d106e7.png)
![screenshot_2018-01-16-00-48-04](https://user-images.githubusercontent.com/26168869/34966810-e227f78e-fa5e-11e7-9f99-478d15fe22e7.png)

**Comment by flocke** [comment]
Which app is that? Is it open source as well?

**Comment by enwokoma** [comment]
It's a File Manager app, not entirely sure if it's Open-Source

**Comment by enwokoma** [comment]
Ya ya. It is Open-Source, just found it [here](https://github.com/RuijiePan/FileManager)

**Comment by flocke** [comment]
Nice, then I can take a peek at how they implemented it.

**Comment by flocke** [comment]
@enwokoma Could you try and get me a logcat on your device? I can't see anything majorly different on their app.

**Comment by flocke** [comment]
After a bit of research this happens to me as well on any AVD running something older than Nougat.
I'm gonna need some time to figure this out.

**Comment by RichyHBM** [comment]
As a temporary work around, the app does always seem to obey the system language, even on devices < Android N

**Comment by flocke** [comment]
Done, at least in my tests it now works on every AVD from KitKat to Oreo!

**Comment by enwokoma** [comment]
Ok. I just checked it out with the latest commit and yes! It works only problem is, on selecting the Chinese language, the app crashes and shows **Unfortunately, andOTP has stopped.**. Then it looks like the **PyccKNÑ** language doesn't change anything **_(Could this be that it hasn't yet been translated to that language?_**
![screenshot_2018-01-18-01-51-49](https://user-images.githubusercontent.com/26168869/35075416-339c21ae-fbf3-11e7-9ed0-ef98e7241239.png)

**Comment by enwokoma** [comment]
Then, I also noticed that for some reason, selecting the English language changes the language of andOTP to a language that's not English,
![screenshot_2018-01-18-01-52-23](https://user-images.githubusercontent.com/26168869/35075473-73df626c-fbf3-11e7-8406-17741868bc97.png)
I kinda have this feeling that the English language was swapped with the PyccKNÑ language (probably by mistake)!

**Comment by enwokoma** [comment]
Well, so far so good. But I noticed that over 90% of the words in andOTP isn't changed to Chinese when I selected the Chinese language, same thing happens when I select the PycckNÑ language too! (Could this be that andOTP haven't been translated properly to these languages)?

**Comment by flocke** [comment]
I just tried it, for me there are a lot of translated strings in Chinese when I switch. There are still some untranslated ones but not many, definitely not 90%. I tested on all Android versions in AVDs and it's the same everywhere.
