### ISSUE TITLE
Humble Bundle icon

### ISSUE THREAD

**Issue by krisu5** [andOTP/andOTP#119]
It would be nice that Humble Bundle icon would be added.

Couple vector options for icon:
- ["Bindle" logo](https://drive.google.com/open?id=0BxnfJ5MQi2uTSmtyeUdRQkM2QU0) (.EPS)
- ["H" logo](https://drive.google.com/open?id=0BxnfJ5MQi2uTOHBobVBCbk5MVU0) (vectorized .PSD, for some reason)

Source: https://support.humblebundle.com/hc/en-us/articles/202742060-Bundle-Logos

Just in case, I uploaded these as ZIP too.
[Humble Bundle vectors.zip](https://github.com/andOTP/andOTP/files/1649745/Humble.Bundle.vectors.zip)

**Comment by tastytea** [comment]
A generic Terminal/SSH icon would also be nice.
 * https://openclipart.org/download/212873/1421942630.svg ([public domain](https://openclipart.org/share))
 * https://upload.wikimedia.org/wikipedia/commons/6/6f/Octicons-terminal.svg ([MIT License](https://commons.wikimedia.org/wiki/File:Octicons-terminal.svg))

**Comment by flocke** [comment]
I'm for the "H" logo and the 2nd terminal one. If @RichyHBM doesn't find the time I'm gonna try adding them myself on Monday.

**Comment by RichyHBM** [comment]
I should be able to put them in this evening, but by all means feel free to add them before hand

**Comment by flocke** [comment]
Both done, found some time to do it myself.

**Comment by krisu5** [comment]
Thanks for icons and for the great app!
