### ISSUE TITLE
Add Grid/Tile based view

### ISSUE THREAD

**Issue by RichyHBM** [andOTP/andOTP#120]
As you add more and more entries the default list view starts to get a bit unwielding. To mitigate this, as well as the tabs, I purpose allowing a grid/tile based view.

I have been working on this over the last couple days and have reached the point where I would like some user input. 

Currently I have it like this: 
<img width="431" alt="grid" src="https://user-images.githubusercontent.com/5472275/35352455-e38d3be6-013b-11e8-9bcf-99ea9ce86a10.png">

As you see, this just shows thumbnail and label, my question is: what approach would be preferred for displaying the full entry info?

2 suggestions:

- Have a popup with full details when you click on an entry

- Have an authy like view where the top half of the screen displays the details of the currently selected entry
![authy-100736003-orig](https://user-images.githubusercontent.com/5472275/35352475-ed2f4446-013b-11e8-8691-8560df933e81.jpg)

**Comment by flocke** [comment]
I never thought of this before, but I like the idea. The Authy interface looks really nice, although I think it will be harder to implement compared to a simple popup.

**Comment by 5t0rmr1d3r** [comment]
I also like the Authy like interface more.

**Comment by RichyHBM** [comment]
OK, will see if an authy like interface is viable. My main concern is with landscape devices, but I guess I can split it left-right when its landscape

**Comment by RichyHBM** [comment]
This is what I have managed to get
![qemu-system-i386_2018-01-30_21-18-42](https://user-images.githubusercontent.com/5472275/35591891-57bed418-0603-11e8-8f09-e559ab4922d1.png)
![qemu-system-i386_2018-01-30_21-18-51](https://user-images.githubusercontent.com/5472275/35591899-5c3af864-0603-11e8-8bcd-bddbfbb6e897.png)
![qemu-system-i386_2018-01-30_21-19-14](https://user-images.githubusercontent.com/5472275/35591901-5ec00d04-0603-11e8-9030-29f85513722d.png)
![qemu-system-i386_2018-01-30_21-19-23](https://user-images.githubusercontent.com/5472275/35591904-60cb262e-0603-11e8-8c36-39a6463731fd.png)

**Comment by enwokoma** [comment]
Not looking bad at all, though I think there might be issues with this when the label or tags length are too long! 
How do we plan a workaround for this?

**Comment by RichyHBM** [comment]
Same way they currenty do, if the label is too long to fit it can use the scroll feature

**Comment by Rafficer** [comment]
Will the authy like version move the tiles down when clicking on one? If it does, imo a popup would be better, because it lets you memorize where which tile is.

**Comment by RichyHBM** [comment]
It does yes, in still unsure which to go with

**Comment by flocke** [comment]
From our discussion in the Telegram group I would say go with the popup for simplicity.

**Comment by enwokoma** [comment]
Just a suggestion to spice the UI up, I would advise that there should be a button on the action bar that toggles between the listview and gridview!

**Comment by RichyHBM** [comment]
@enwokoma There is, the 3 block icon in the top right (next to search) is a drop down that lets you select the sorting order and the list view type

**Comment by enwokoma** [comment]
Well, not bad for me, though I would have suggested a separate button from the sort button!

**Comment by flocke** [comment]
We haven't worked on this for almost 2 years, closing for now.
We might revisit it if we ever run out of things to do.
