### ISSUE TITLE
Add some universal icons

### ISSUE THREAD

**Issue by Buxdehuda** [andOTP/andOTP#122]
I'd like to suggest to add more universal icons that aren't specific to a particular service. For example an e-mail icon (envelope) and a controller of some sort (NES/XBox styled) for gaming related accounts. Especially when using less known sites this could help to reduce the amount of icons needed to be included in the app.

**Comment by RichyHBM** [comment]
Happy to put a few extra if you an think of a list of stuff needed @Buxdehuda

**Comment by Buxdehuda** [comment]
In addition to these two already mentioned I could think of a generic cloud icon, one wallet-like symbol for bank accounts and perhaps an 'education' icon with this squared hat, though I don't know if this one is so important.

**Comment by RichyHBM** [comment]
OK, I will add a bunch of icons from the material guideline set

**Comment by Buxdehuda** [comment]
Great, thank you!
