### ISSUE TITLE
Feature Request: Rename and delete tags

### ISSUE THREAD

**Issue by max-wittig** [andOTP/andOTP#126]
Currently it doesn't seem to be possible to rename tags in the app or to delete existing tags.

Is that right or am I missing something?

Using version from Google PlayStore from February 1, 2018 - 0.4.0.1

**Comment by RichyHBM** [comment]
The tags system is pretty basic, to delete a tag remove it from all entries. Remaining isn't directly possible so you'll have to delete and create a new one

**Comment by max-wittig** [comment]
Okay thank you. Any plans to improve on this in the future?

**Comment by RichyHBM** [comment]
I don't think so, maybe the issue comes from the thought that tags are more like folders, where as they actually are filters

**Comment by flocke** [comment]
I'm gonna assign this to you @RichyHBM and let you make the decision. In my opinion the tag system is totally fine as it is now.

**Comment by RichyHBM** [comment]
I think I'm going to close this specific issue as the tags are a filteringsystem, thus the side bar just displays any tags associated with an entry. I dont really know what we would want renaming/deleting to do, unless it were just mass renaming or deleting all tags on their entries..

But if you have any other suggestions please feel free to open another issue!
