### ISSUE TITLE
Add Fingerprint and Face Authentication

### ISSUE THREAD

**Issue by enwokoma** [andOTP/andOTP#127]
Nice work so far! Though the Google backup feature is yet to be implemented, a new feature that would be really awesome to see in andOTP is the ability to set up authentication mode to Fingerprint or Face ID! 
Just like the way u added password and PIN authentication! I think it would be nice to allow a user to open/authenticate andOTP using his Fingerprint or his face, andOTP when authentication is set to Fingerprint in the dialog, an activity or fragment should open and ask him to enroll his Fingerprint, it should ask to enroll his face if he/she decides to authenticate with his face id, after enrollment, it should be stored somewhere so that when the user opens andOTP, a request for his Fingerprint touch or Face scan should be made, the moment the scanned face or Fingerprint touch matches the ones stored within andOTP, then the app should open to the MainActivity. 

I would have tried getting something by this week but I am out of schedule and having written some codes on this, am stuck at the enrollment because currently, I can only use the already enrolled Fingerprint data on the phone and not the enrolled Fingerprint/Face ID within andOTP but this would cause some security problems because most people enroll more than 1 Fingerprint data on their devices and I wouldn't like a situation where another enrolled Fingerprint data outside andOTP can be able to authenticate the app! 
PS: Same thing goes for the Face ID (I believe can be achieved using the FACESDK) and there should be an ability to reenroll or change/edit the already enrolled Fingerprint and Face ID data!

**Comment by RichyHBM** [comment]
AndOTP already allows using the systems authentication, so if you set your lock screen to use fingerprint I assume it should just work.

I don't have a fingerprint device so I can't test it myself

**Comment by enwokoma** [comment]
Ya ya. I think it does, but this isn't what I was suggesting because setting andOTP to use device credentials as the means of authentication means that if a user has more than 1 Fingerprint data/id registered on his device, it means that another person can gain access to use andOTP just because his Fingerprint is registered on the users device! 

To me, this isn't just right! Just saying!

**Comment by flocke** [comment]
That's something I will have to think about. It seems like a lot of effort to implement and is in my opinion not something a simple 2FA app needs.

**Comment by RichyHBM** [comment]
Personally I think adding fingerprint/face reader directly into andOTP is a bit excessive. Any fingerprint/face reading functionality should ideally just be provided by android, so unless there is a way to have a fingerprint on a per app basis I dont think this should be added.

**Comment by ximmox** [comment]
System authentication works fine with the device's registered fingerprints, so no need to implement it on your own (just tested, Moto Z, Lineage 14.1, microG).
If you trust others to unlock your phone with their fingerprints but don't trust them with your OTP tokens, that's not really a common problem I suppose...

**Comment by enwokoma** [comment]
Cool! Can you send a snapshot of how the authentication is requested for on andOTP when it has been set to use system authentication

Like the layout that is shown when the user is requested to scan his/her Fingerprint before gaining access to use andOTP!

**Comment by enwokoma** [comment]
Kikikikiki! 😂 😂 😂. That line

> If you trust others to unlock your phone with their Fingerprints but don't trust them with your OTP tokens, that's not really a common problem I suppose! 
Mehn it's just savage! 😂 😂 😂

**Comment by ximmox** [comment]
It looks like this: https://imgur.com/a/hqoIb

**Comment by enwokoma** [comment]
Not bad! Closing this since it actually works when authentication is set to Device Credentials!

**Comment by RichyHBM** [comment]
As an alternative @enwokoma if you really want to lock andOTP behind a fingerprint that is different to your main lock screen, the app AppLock on the play store can do that I

**Comment by enwokoma** [comment]
Cool! Thanks! 
U could do well to add that info somewhere in the README.md or WIKI because, not everyone would have the idea about this!

**Comment by RichyHBM** [comment]
I don't really think that info is relevant to andOTP tbh
