### ISSUE TITLE
Crashes after update to 0.4.0.1

### ISSUE THREAD

**Issue by filalex77** [andOTP/andOTP#128]
#### General information

* **App version:** 0.4.0.1
* **App source:** F-Droid
* **Android Version:** 5.1
* **Custom ROM:** No (Flyme 6)

#### Expected result
**What is expected?** 
Starting up normally

**What does happen instead?**
Crashes after entering PIN

#### Logcat
```
I/InstalledAppProviderSer(28859): Marking org.shadowice.flocke.andotp as installed
E/AndroidRuntime(32618): Process: org.shadowice.flocke.andotp, PID: 32618
E/AndroidRuntime(32618): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=100, result=-1, data=null} to activity {org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] android.content.Intent.getByteArrayExtra(java.lang.String)' on a null object reference
E/AndroidRuntime(32618): 	at org.shadowice.flocke.andotp.Activities.MainActivity.onActivityResult(MainActivity.java:401)
W/ActivityManager( 1286):   Force finishing activity 1 org.shadowice.flocke.andotp/.Activities.MainActivity
I/WindowManager( 1286): Screenshot max retries 4 of Token{eebcdf2 ActivityRecord{256f0cfd u0 org.shadowice.flocke.andotp/.Activities.MainActivity t25103 f}} appWin=Window{128f0120 u0 org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.MainActivity} drawState=1
I/ActivityManager( 1286): Process org.shadowice.flocke.andotp (pid 32618) has died
I/WindowState( 1286): WIN DEATH: Window{128f0120 u0 org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.MainActivity}
I/Utils   (29366): uid is : 10150  packagesInfo is : org.shadowice.flocke.andotp
I/Utils   (29366): uid is : 10150  packagesInfo is : org.shadowice.flocke.andotp
W/PackageManager( 2080): Failure retrieving resources for org.shadowice.flocke.andotp: Resource ID #0x0
```

#### Steps to reproduce
 Upgrade 0.3.1 to 0.4.0.1, start the app

**Comment by flocke** [comment]
An here I thought I caught all null pointer exceptions. Let me look into it tomorrow.

**Comment by filalex77** [comment]
@flocke Yeah, sure. Staying on 0.3.1 for now - it works. Thanks for the great project :)

**Comment by flocke** [comment]
Could you get me the full logcat? The one you posted seems to be filtered to only show entries from andOTP. From what I can get from the partial log it seems that the Intent in https://github.com/andOTP/andOTP/blob/9d4cde29461cbdcf89be83ca2e7f690d955a430c/app/src/main/java/org/shadowice/flocke/andotp/Activities/MainActivity.java#L401 is `null`. However that can happen ...

**Comment by filalex77** [comment]
Yes, I did filter it for clarity. Here's the [full logcat](https://gist.github.com/588b2e0b1eac71758093971ded4f1afd) (reinstalled 0.4.0.1, tried to start it 2 times). Hope it helps!

**Comment by flocke** [comment]
Did you install 0.4.0.1 clean or did you upgrade from 0.3.1?
Could you try setting up 0.4.0.1 clean?

**Comment by filalex77** [comment]
Sure. I will double-check my backups and then try clean installing.

**Comment by Flnch** [comment]
@flocke I also had the app crashing after upgrading from 0.3.1 but with an error message complaining about the Android KeyStore. After setting up a clean actual version and importing my backup everything works fine again.

**Comment by filalex77** [comment]
Confirmed: clean installation works, imported backups.

**Comment by flocke** [comment]
Nice, I will still look into it because I really don't get how the intent can be `null` (I tested upgrading from 0.3.1 several times and it never happened).

**Comment by Crote** [comment]
Is there a way to fix this without a clean reinstall? My backup isn't as recent as it should be, unfortunately. Downgrading to 0.3.1 in F-Droid doesn't seem to be possible either.

**Comment by flocke** [comment]
@Crote If you are rooted you can manually edit the settings and disable the authentication. For that edit the file `/data/data/org.shadowice.flocke.andotp/shared_prefs/org.shadowice.flocke.andotp_preferences.xml`. There should be a line like `<string name="pref_auth">pin</string>` (obviously not `pin` if you use something else). Remove that whole line.

**Comment by Crote** [comment]
No root for me, unfortunately. Oh well, I guess it'll probably be easier to just spend the 15 minutes or so re-registering my 2FA accounts.

**Comment by olisax** [comment]
Crash for me also after updating from 3.x to 4.x. I didn't make any export of the keys before the upgrade; but fortunately I have a relatively recent TWRP backup, so I was able to go back to the former version and export the json file :-)
