### ISSUE TITLE
Unable to overwrite existing otp accounts backup

### ISSUE THREAD

**Issue by enwokoma** [andOTP/andOTP#130]
So, I made a backup of my accounts on my andOTP straight to my internal storage a few weeks ago and then after making some changes by adding more accounts, I decided to make a new backup to the same directory, only to get an error toast message saying the backup was unsuccessful but the moment I deleted the existing json backup file from the directory, I noticed that exporting a backup from andOTP now works. 
This isn't right because andOTP should be able to overwrite the existing backup file, or at least prompt a dialog box asking the user if he/she wants to overwrite the existing backup file or if they want to save it as a different backup with a different name of their choice!

**Comment by flocke** [comment]
Works without a problem for me. I need a logcat to look into this further.

**Comment by enwokoma** [comment]
Ok.. Would see what I can get by tomorrow!

**Comment by enwokoma** [comment]
Pardon me for the late response! 
I had to be sure of my results on this issue! 

After intensive checking, I found out that this issue isn't a problem from andOTP and that, andOTP saves every new backup irrespective of the existing backup! The problem I was facing earlier in overwriting is an issue from the File Manager I used and not a problem with andOTP at all!
