### ISSUE TITLE
Add Evernote, Namecheap and Kraken Icon

### ISSUE THREAD

**Issue by Rafficer** [andOTP/andOTP#131]
Would be awesome to get those icons. [Kraken](https://kraken.com), [Evernote](https://evernote.com) and [Namecheap](https://namecheap.com).

Or is there some universal guide on how to add Icons? I think this would come in handy for the future, so it would be a lot easier for anyone to create a pull request and add icons themselves.

Or do you not want to bloat the icon choice too much?

**Comment by flocke** [comment]
The usual way for now is to request the icons in the wiki: https://github.com/andOTP/andOTP/wiki/Thumbnails

But you are right, I might write up a small guide on how to add icons as PR in the future. At the moment we optimize the icon files manually (remove gradients, optimize paths, ...) to keep the files as small as possible.

**Comment by Rafficer** [comment]
I knew there had to be some way other than opening an issue. Maybe it's worth adding some question mark to the icon selection that says it's possible to request new icons on github? :)

**Comment by Rafficer** [comment]
I've added the requests to the wiki. Close the issue if you want to :)
