### ISSUE TITLE
Camera permission in the manifest

### ISSUE THREAD

**Issue by rishabhkohli** [andOTP/andOTP#132]
This might be a stupid question, I am not sure.

How come the android manifest doesn't have the camera permission? Is it not updated with the latest code update?

**Comment by flocke** [comment]
It's not in the manifest because it's brought in by the library used to scan the QR codes:  https://github.com/journeyapps/zxing-android-embedded

**Comment by rishabhkohli** [comment]
Oh, okay.
I will read up on that.

Thanks.
