### ISSUE TITLE
Tags selection should be "AND", not "OR"

### ISSUE THREAD

**Issue by SwissTico** [andOTP/andOTP#133]
#### General information

* **App version:** 0.4.0.1
* **App source:** Google Play
* **Android Version:** 8.0
* **Custom ROM:** No

#### Expected result
**What is expected?** 
When you select multiple tags, it would be great that the result show only the items part of both tags.
For example we have various Google Account for various clients, so we have a tag for everything that belong to the client, and another one that belong all Google Accounts of every clients. It would be great that when we select both tags, it shows only the Google account for client X (the result that match all requirement)

**What does happen instead?**
When we select more than one tag, instead of to show what is part of all tags (search result AND), it show all the results of all selected tags (search result OR). In our example before, it shows all Google accounts of all clients and all items of the client X, so it is hard to find the item we look for.

**Comment**
Maybe can be an option to select both way to do in settings because it can be probably useful to other people to have it this actual way.

#### Logcat
```
Paste your logcat here (or use something like Pastbin for long logs)
```

#### Steps to reproduce
 
 * ...

**Comment by flocke** [comment]
I think a settings option to switch between the two modes should be fine.

**Comment by RichyHBM** [comment]
I'd be happy to add a settings option to include this functionality, recently I've been wanting the tags to have a different behaviour and a settings option like this would be perfect
