### ISSUE TITLE
App crashes due to invalid values being processed

### ISSUE THREAD

**Issue by x3rAx** [andOTP/andOTP#135]
### General information

When entering an invalid value (empty or "0") in the "Advanced Options" section when manually entering details, the app crashes. This seems to be due to conversion of "" (empty string) to number or a division by 0 (when value is 0). This happens for both, the "Period" and "Digits" fields.

* **App version:** 0.4.0.1
* **App source:** Google Play
* **Android Version:** 7.1.2
* **Custom ROM:** LineageOs 14.1

(This also happens on my main phone but the logcat on the device above is way less cluttered 😋)

### Expected result
**What is expected?** 
The "Save" button should be disabled while input fields contain invalid information (and maybe the input field containing a wrong value should have a short description why the value is invalid).

**What does happen instead?** 
App crashes.

### Logcat
I've extracted the *exceptions + stack trace* from the logcat. If you really need the whole logcat, I'm willing to send it to you via mail or so, but I don't want to post it publicly (I've seen my WiFi name in there and I'm curious of what other sensitive information (like GPS coordinates?) might be there as well..).

*Empyt value in field "Period":*
```
02-17 23:22:36.627 10690 10690 E AndroidRuntime: FATAL EXCEPTION: main
02-17 23:22:36.627 10690 10690 E AndroidRuntime: Process: org.shadowice.flocke.andotp, PID: 10690
02-17 23:22:36.627 10690 10690 E AndroidRuntime: java.lang.NumberFormatException: For input string: ""
02-17 23:22:36.627 10690 10690 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:533)
02-17 23:22:36.627 10690 10690 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:556)
02-17 23:22:36.627 10690 10690 E AndroidRuntime: 	at org.shadowice.flocke.andotp.View.ManualEntryDialog$7.onClick(ManualEntryDialog.java:172)
02-17 23:22:36.627 10690 10690 E AndroidRuntime: 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
02-17 23:22:36.627 10690 10690 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-17 23:22:36.627 10690 10690 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-17 23:22:36.627 10690 10690 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
02-17 23:22:36.627 10690 10690 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-17 23:22:36.627 10690 10690 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
02-17 23:22:36.627 10690 10690 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

*Value "0" in field Period:*
```
02-17 23:23:47.004 11016 11016 E AndroidRuntime: FATAL EXCEPTION: main
02-17 23:23:47.004 11016 11016 E AndroidRuntime: Process: org.shadowice.flocke.andotp, PID: 11016
02-17 23:23:47.004 11016 11016 E AndroidRuntime: java.lang.ArithmeticException: divide by zero
02-17 23:23:47.004 11016 11016 E AndroidRuntime: 	at org.shadowice.flocke.andotp.Database.Entry.updateOTP(Entry.java:300)
02-17 23:23:47.004 11016 11016 E AndroidRuntime: 	at org.shadowice.flocke.andotp.View.ManualEntryDialog$7.onClick(ManualEntryDialog.java:176)
02-17 23:23:47.004 11016 11016 E AndroidRuntime: 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
02-17 23:23:47.004 11016 11016 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-17 23:23:47.004 11016 11016 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-17 23:23:47.004 11016 11016 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
02-17 23:23:47.004 11016 11016 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-17 23:23:47.004 11016 11016 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
02-17 23:23:47.004 11016 11016 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

### Steps to reproduce
 
 * Click the "+" button to add a new OTP
 * Select "Enter details"
 * Fill in "Label" and "Secret"
 * Click "Advanced Options"
 * Change the value of "Period" or "Digit" to be empty or "0"
 * Click "Save"

**Comment by flocke** [comment]
Thanks for testing, it should be simple to fix.

**Comment by x3rAx** [comment]
Yeah, I'm currently setting up my Android Studio and will try to fix it (I already located the code that needs to be changed). If I'm fast enough, I'll send you a PR :)

**Comment by flocke** [comment]
Merged, thanks for the quick PR!
