### ISSUE TITLE
Support for mOTP

### ISSUE THREAD

**Issue by madman2021** [andOTP/andOTP#142]
Are there any plans to support MOTP, I would love to use this App to authenticate with a Draytek VPN

**Comment by flocke** [comment]
This is the first time I have heard about MOTP. I will have to look at how it is implemented before deciding.

**Comment by madman2021** [comment]
Spec
http://motp.sourceforge.net/
App I currently use
https://play.google.com/store/apps/details?id=com.sslmotp.app&hl=en

**Comment by flocke** [comment]
Should be fairly straight forward and I probably will include it at some point. For now though HOTP is the next algorithm I'm gonna implement as it is somewhat more common and has been on my TODO for a long time. After that I'm gonna take a look at mOTP.

**Comment by mantinan** [comment]
hi!
I'd also be willing to use andopt if it supported mOTP, is there any movement on this area?
Thanks!

**Comment by flocke** [comment]
Just a note for myself.

mOTP algorithm: `MD5(epoch + secret + pin).SUBSTR(0, 6)`
- `epoch`: 10 sec granularity
`now=new Date();
epoch=""+(now.getTime()+((timez-12)*3600000));
epoch=epoch.substring(0,epoch.length()-4);`
- `secret`: random 16-digit HEX secret (`secret=new MD5(pinfield.getString()).asHex().substring(0,16);` in the reference)
- `pin`: 4-digit PIN

**Comment by mantinan** [comment]
I have commented it on the telegram channel.

We have motp implemented with the pin and everything on top on 0.7.0. It is a work they did for us and now I was trying to push it to you, I have tried to port that to current master but I'm strugling to compile andotp (I have tried both openjdk 9 and 11). So I have it a little stopped right now.

I hope I can put some time on this soon.

Regards.

**Comment by mantinan** [comment]
I have created a pull request for the implmentation of MOTP, it is here:
https://github.com/andOTP/andOTP/pull/617
My original repo for this is at:
https://github.com/mantinan/andOTP

**Comment by flocke** [comment]
Closed in #617
