### ISSUE TITLE
[Help wanted] Improve English strings

### ISSUE THREAD

**Issue by flocke** [andOTP/andOTP#149]
While I am a pretty good English speaker (in my opinion) I am no native speaker, and even I notice that some of the wording in andOTP is not really ideal (but I have no idea on how to improve it). I would love if someone wanting to contribute could look over all the strings in andOTP and, if he deems it necessary, suggest me a better wording (or even complete rewording to better explain the functions of andOTP).

While this is mainly targeted at native speakers anyone with sufficient English knowledge can feel free to suggest something.

**Comment by enwokoma** [comment]
Let me see how I contribute to this!
Am pretty much very good with English!

**Comment by flocke** [comment]
If you have something to improve you can just write it here. Or if you have the time you can open a PR and we can discuss it there.

**Comment by jsoberg** [comment]
Hey @flocke, I know this is a relatively old issue but I'm a native English speaker so I thought I'd throw my hat in the ring. I'll read through what I can and put up a PR. The English text seems good from what I've read while using the app, so most of my suggestions will probably be subjective. I'll explain my reasoning as best I can in my commit messages but feel free to comment.
