### ISSUE TITLE
Proposal to allow automatic login

### ISSUE THREAD

**Issue by RichyHBM** [andOTP/andOTP#153]
Currently andOTP requires you to hit enter to log you in.

This has been addressed before but was decided against due to the performance of trying to decrypt the database or having to store the length of the password.

I propopose the following(This could always be hidden behind a setting so it is opt in):

1. Add a dictionary to the app, maybe few hundred words
2. When the user enters a pin/password we randomly select a word from the list
3. We encrypt the word and store it in a file on device
4. We also encrypt the word with a key stored in the key store
5. When the user opens the app, and based on the minimum pin/password length we wait for them to enter a long enough password
6. We decrypt the keystore based file so we know what word we are comparing it
7. On each pin/password change we spin up an Async task to try to decrypt the file and compare it to the valid word
8. We allow the user to hit enter and try a full decryption as it does Currently
9. If the async task completes succesfully we automatically log the user in

This achieves a number of things, performance should remain, we are doing all tasks in background threads so the main thread should stay as it is.

We are not storing any damaging data unencrypted, and because there are hundreds of seed words posibility it would hopefully also be hard to brute force

Worst case scenario it loses the keystore key and you just lose the ability to auto login

**Comment by flocke** [comment]
I like the basic idea. The only thing I don't like is the part were we use the KeyStore ... I wanted to keep that troublemaker as far from anything to do with the password-based encryption as possible ...

**Comment by RichyHBM** [comment]
That's fair enough, OK let me have a think and see if I can come up with an alternative

**Comment by flocke** [comment]
I'm closing this for now since there has been no movement on this for the last 2 years. If something ever changes feel free to reopen.
