### ISSUE TITLE
EA / Origin Not Supported

### ISSUE THREAD

**Issue by MartinX3** [andOTP/andOTP#158]
At the moment, it doesn't support EA / Origin.
When I scan the QR Code, the APP tolds me, it is invalid.

**Comment by flocke** [comment]
I have an Origin account that I didn't use for some time. Let me check this out when I'm back home on Monday.

**Comment by MartinX3** [comment]
Thank you very much. :)

**Comment by RichyHBM** [comment]
I literally just had this as I added my account. The first qr code they show in the website is a link to the google authenticator in the play store, you need to click next and scan the qr code on the window that has an input field

**Comment by MartinX3** [comment]
At my side the next dialog was a input field for a security number.
