### ISSUE TITLE
UI: Multiple columns?

### ISSUE THREAD

**Issue by danielquinn** [andOTP/andOTP#162]
#### General information

* **App version:** 0.4.0.1
* **App source:** F-Droid
* **Android Version:** 6.0.1
* **Custom ROM:** Stock Google Nexus 5

#### Expected result
**What is expected?** The UI could used a column or "cards" -based layout.  As it is, regardless of screen resolution or orientation, one entry gets one row with a whole whack of dead space between the numbers and the copy/settings icons.  If instead these values were stacked vertically (you could even move the `copy` icon inside the three-dot settings icon) you could effectively double the information you can fit on the screen.

**What does happen instead?**  The UI works, but for users like me with **16** different OTP accounts, I end up scrolling/searching a lot more than I'd like.

#### Logcat

n/a

#### Steps to reproduce

n/a

I want to stress that this is by far the best of all the OTP apps I've tried out there.  If I knew anything about Java or Material design, I'd offer a pull request, but as I'm more a Python nerd, I'm afraid I've not much to offer on this front.

I've got this though, a mockup I did with draw.io :-)

![andotp-example](https://user-images.githubusercontent.com/218205/37647494-4b297a72-2c24-11e8-95f8-b47ddcaf771c.png)

**Comment by flocke** [comment]
@RichyHBM is currently working on a grid based layout. Check #120.

**Comment by danielquinn** [comment]
Oh!  Yes that's exactly what I was hoping for, and *much* prettier than what I had initially had in mind.  Thanks for pointing it out :-)
