### ISSUE TITLE
UI option request

### ISSUE THREAD

**Issue by krc** [andOTP/andOTP#166]
#### General information

* **App version:** 0.5.0.1
* **App source:** Google Play
* **Android Version:** N 7.0
* **Custom ROM:** n/a

I was wondering if we could get an option to hide the "timeout bar"/"code change bar", perhaps only show it when the code has been reveled (assuming that setting has been turned on). 

Or something along those lines... I know it is weird, but having the bar at the top always going down makes me feel very anxious.

**Comment by gerardp** [comment]
_I know it is weird, but having the bar at the top always going down makes me feel very anxious._

It happens to me too, I prefer the google design.

**Comment by flocke** [comment]
I will have to think about it, I actually like the current implementation but I will check out how Google Authenticator does things. It will definitely not be in the next release, I don't have a lot of time currently and there are a few more important things still to do.

**Comment by X-Coder** [comment]
I think the single timeout bar on top doesn't make any sense at all: each code could have a totally different timeout, so why not showing the real timeout on the right side or below each entry?

Or maybe you can add an option for this?

**Comment by flocke** [comment]
In the current beta I added individual timeout bars to all tokens that don't have the default timeout (30s). I will add an option to hide the global timeout bar as well later on.
