### ISSUE TITLE
Request for additional logos

### ISSUE THREAD

**Issue by bluezed** [andOTP/andOTP#169]
I would really appreciate it if logos for the following services could be added to the app:

 - Bitwala - https://bitwala.io
 - HitBTC - https://hitbtc.com
 - BitPanda - https://www.bitpanda.com

Out of about 20 different accounts that I'm using the app for these are the only ones missing a logo for me ;)

Many thanks!

**Comment by flocke** [comment]
Could you please add the requests to the wiki: https://github.com/andOTP/andOTP/wiki/Thumbnails
Preferably with a link to the logos as vector images to save us some time.
