### ISSUE TITLE
Request for copywriting 

### ISSUE THREAD

**Issue by princekelly1** [andOTP/andOTP#174]
Hi, I would like to make a copywriting pull for your project. I would propose to write About us, FAQ that would help promote the project.

**Comment by flocke** [comment]
Hey, feel free to do so. I would prefer you using the Github wiki to write the FAQ and the About us instead of a PR, I try to use it to collect as much information about the project as possible.

**Comment by princekelly1** [comment]
Hi
Thanks I would do that, and submit a copy to you for proof reading. Then
merge into the project wiki

On May 7, 2018 4:58 PM, "Jakob Nixdorf" <notifications@github.com> wrote:

Hey, feel free to do so. I would prefer you using the Github wiki to write
the FAQ and the About us instead of a PR, I try to use it to collect as
much information about the project as possible.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/andOTP/andOTP/issues/174#issuecomment-387112569>, or mute
the thread

**Comment by drhus** [comment]
Good idea @princekelly1 please consider some formal way for public to add their logos, I noticed very few logos we have on andOTP and I'm sure many sites wish to add their logos
