### ISSUE TITLE
[Poll] More screenshot restrictions

### ISSUE THREAD

**Issue by flocke** [andOTP/andOTP#175]
As you most likely know the main screen of andOTP doesn't allow you to take screenshots for security reasons. Recently I got the request to additionally disable screenshots on the Authentication and Settings screen. While I personally don't really see the security benefit I wanted to ask some more users what they think of this suggestion.

Just cast your vote by adding a reaction to this issue:
- :+1: : Yes, restrict screenshots in Authentication and Settings screen
- :-1: : No, keep it as it is now

**Comment by PHoBwz** [comment]
No problem with restricting screenshots but does the backup keep settings or just the auth's? If it doesn't I can see some people just screenshotting settings as a quick and dirty backup

**Comment by flocke** [comment]
@PHoBwz No, backups do not include settings. So taking a screenshot to backup the settings is a smart use case. On the other hands are the settings not so complicated and it shouldn't take long to set them up again even without a screenshot.

**Comment by JochemKuijpers** [comment]
To me, screenshots are a useful tool to help others remotely if they need help with an app that I have also installed. Blocking screenshots seems like a good idea, but can hurt usability too. From the votes, it seems there are two sides to the coin and no real consensus.

Perhaps make it a setting, defaulting to the current behavior?

```java
getWindow().setFlags(LayoutParams.FLAG_SECURE, LayoutParams.FLAG_SECURE);
```

This seems all that is necessary to prevent screenshots (correct me if I'm wrong) in the window that needs to be secured, so a simple checkbox or dropdown to control where these flags are set in the settings screen could make this dynamic and satisfy everyone.

**Comment by flocke** [comment]
@JochemKuijpers Yeah, that's pretty much all that is necessary to restrict screenshots. Currently you need to enable the Special features to allow screenshots of the main screen. I was thinking about a selection where you can choose which screens should be blocked (main, settings and authentication) with main being enabled by default. Further I would make it so you can't disable main without enabling the special features to keep it similar to the current implementation.

**Comment by flocke** [comment]
This poll has been running for 2 weeks by now and I don't think the result is gonna change drastically soon. For now I'm gonna keep everything as it is. Maybe I will make it optional to restrict screenshots on the settings and authentication screens at some point, but that won't make it into the next release (I'm pretty focused on HOTP support for now).
