### ISSUE TITLE
Import password-encrypted backup doesn't require password

### ISSUE THREAD

**Issue by JoaoAparicio** [andOTP/andOTP#176]
#### General information

* **App version:** 0.5.1
* **App source:** Google Play
* **Android Version:**
* **Custom ROM:**

#### Expected result
I expected that when I press "Restore (encrypted)" a prompt would come up for the encryption password.

#### Actual result
What happens instead is that the password-protected backup is successfully imported without a password being required. This leads me to think that the backup password is stored somewhere on the phone. Or maybe the backup password is stored encrypted using the app authentication password which isn't great either.

**Comment by flocke** [comment]
Currently it's exactly as you suspect: the password is stores encrypted on the phone (it's the one you set in the Settings). It's not ideal but that's how it is currently done. I plan to change it in the future somehow but currently I don't have time to work on andOTP a lot, as soon as I get more free time I will rethink how this should work.

**Comment by JoaoAparicio** [comment]
Re: time, don't worry. Thank you so much for this project.

Re: security. I'm not an expert, but my rationale is that people will have weaker passwords for things they access more often, so having the auth password protecting the backup password doesn't make much sense. But maybe you should ask an expert.

Thanks again.

**Comment by skorokithakis** [comment]
Just to chime in, I'm not sure how encryption works right now, but what andOTP should do is use something like bcrypt/scrypt to derive an encryption key from the user's password and use that to encrypt/decrypt.

I'm chiming in here because I saw the security-related discussion.

**Comment by flocke** [comment]
@skorokithakis The current backup password is still a little bit of an issue in that regard. Currently it only uses a SHA hash to generate the encryption key from the password. In the future I would like to implement something similar to the way the password-based encryption of the database works (PBKDF2).

**Comment by skorokithakis** [comment]
@flocke That's "easy" to do, in the following way:

1. The user gives you a password, you run it through a good KDF and store the resulting key.
2. At some later point, the user attempts a restore. If the stored key matches, you can just decrypt and you're good.
3. If the stored key doesn't match, you ask the user for the password. They type in their password, you derive the key with the KDF and try that (in case the backup is from another device), if that doesn't match you try the legacy SHA method. You never store the results of this step anywhere.
4. If neither of the above matches, decryption fails and you say "wrong password".

That way, you have both backwards compatibility and security.

**Comment by himselfv** [comment]
> This leads me to think that the backup password is stored somewhere on the phone. Or maybe the backup password is stored encrypted using the app authentication password which isn't great either.

I would argue this is perfect, please don't change that. Your phone already contains all keys in the open, what protection can be added by forcing the user to type in backup password every backup? It would just be an inconvenience.

The backup password should be stored and protected simply in the same way the keys are protected. And if you already have it, why ask it again when restoring from the backup?

**Comment by flocke** [comment]
I'm closing this issue because since this question was asked the following things have been changed:

1. andOTP now uses a much better key derivation for the backups (PBKDF2)
2. Storing the password in the settings is optional. If it is not entered in the settings the user gets asked for it every time he wants to create or restore a backup.

The user can still store the password in the settings, mostly for automated backup purposes. But in that case the password is used for the manual backups as well.
