### ISSUE TITLE
Manual code input

### ISSUE THREAD

**Issue by n0bodyBod** [andOTP/andOTP#179]
I think manual code input instead of scan QR code could be a great option for just in case.

**Comment by flocke** [comment]
I don't know what you mean, you can already manually input a new account.

**Comment by n0bodyBod** [comment]
Hi, what I mean is entering the secret. Sorry, I wasn’t clear on the issue here.

**Comment by flocke** [comment]
This can already be done. If you click on the plus button in the lower right corner and select "Enter details" you can manually input the secret.

**Comment by n0bodyBod** [comment]
Oh my god, sorry 😅 and thank you!

**Comment by flocke** [comment]
No problem :sweat_smile:
