### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by waqasanwar94** [andOTP/andOTP#180]
Hello, @andOTP I want to contribute in "andOTP" so i want to design a new logo for "andOTP" and it's free.

I hope you like it. If you like it, I will send you to pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.

if you want i will send you my design

Contact me on facebook for fast delivery 
https://www.facebook.com/waqasanwar68

**Comment by flocke** [comment]
Sorry, I like the current logo and am not looking for another one at the moment.
