### ISSUE TITLE
"Select OpenPGP key" wants key for alice@example.com

### ISSUE THREAD

**Issue by codewiz** [andOTP/andOTP#181]
#### General information

* **App version:** 0.5.0.1
* **App source:** F-Droid
* **Android Version:** 8.1
* **Custom ROM:** OnePlus 5T stock OS

#### Expected result
**What is expected?**
When I should be able to specify any recipient for which I have a public key.
Ideally, I should be able to pick multiple recipients (I have different keys for laptop and phone, because I don't trust the phone with my main PGP key).

**What does happen instead?**
The email "alice@example.com" appears to be hard-coded (couldn't find any UI to configure it).
#### Steps to reproduce
 
 * Go to Settings
 * Select OpenKeychain as your OpenPGP provider
 * Click Select OpenPGP key
 * Selection dialog pops up asking to pick a key for "alice@example.com", which I don't have

**Comment by codewiz** [comment]
![image](https://user-images.githubusercontent.com/1184492/40267433-169164bc-5b97-11e8-8c70-1b67361e3393.png)

**Comment by Kewjoe** [comment]
I'm having the same issue. I also tried 0.6.0-beta1 and same thing. I'm also getting it from Fdroid (i tried playstore too, same thing). I'm also on Android 8.1 and I'm on a OnePlus 3T running Lineage OS 15.1 (MicroG edition).

I'm not able to restore my backup.

**Comment by JustABanana** [comment]
For me OpenKeychain allows me to change my key to any key I want if I generate key for alice@example.com first and then try changing the key. https://i.imgur.com/3WwlLOT.png

**Comment by Kewjoe** [comment]
Thanks, I had tried that several times but it kept failing when i tried to decrypt my backup file. But, I just tried again because I wanted to provide the exact error message and it worked... so ya. I guess i'm good now. I'm on 0.6.0-beta1 currently.

**Comment by flocke** [comment]
Yeah, OpenKeychain changed something in the key selection. I used an old example for andOTP and forgot to remove the Alice part. It's already fixed for the next release.

For now you can click on "I already have a key" in the dialog and then on the three-dot menu in the top right and select "List unrelated keys" to show all keys.

**Comment by codewiz** [comment]
@Valodim this is probably an OpenKeychain bug: the string "alice@example.com" does not even occur in otpAND. It coms from the OpenKeychain codebase:

https://github.com/open-keychain/open-keychain/search?utf8=%E2%9C%93&q=alice%40example.com&type=

**Comment by flocke** [comment]
@codewiz It used to be in andOTP because of an old example I used from OpenKeychain. I removed it already, so it doesn't show up in andOTPs code anymore.

**Comment by codewiz** [comment]
@flocke Sorry, I missed it in your previous comment.

And thanks for developing andOTP, I really love it: https://mstdn.io/@codewiz/100055250161051442

**Comment by Valodim** [comment]
Sorry for breaking the api here :( it does fall back to the old dialog if no user id is given, but I didn't account for anyone using "alice@example.org". Anything you need from us?

**Comment by flocke** [comment]
@Valodim No, by now I have everything fixed and it should be working again in the next release. I was just stupid to use the "alice@example.com" from the code example in the API.

**Comment by flocke** [comment]
I'm gonna close this issue since the fix is already implemented, I will release a second beta for 0.6.0 soon which will include it.

**Comment by pstch** [comment]
@flocke do you know if the fix has been pushed to F-Droid ? I installed andOTP and openkeychain recently, and still have this problem.
