### ISSUE TITLE
Few questions, need clarification

### ISSUE THREAD

**Issue by bluefiberbread** [andOTP/andOTP#184]
I've created a backup of my andOTP (json.aes file).

If I lose my phone, would I just need to install andOTP on my new phone, import the backup and that's it? And if I want to sell my phone, how would I get rid of andOTP and my settings on it?

**Comment by RichyHBM** [comment]
That is correct, 

As for getting rid of data, uninstalling andOTP and deleting any backups should do it. A factory reset should be enough

**Comment by flocke** [comment]
As @RichyHBM said, as long as you set the same backup password on both phones you should be able to import the backup without problems.

Uninstalling the app automatically removes all its data. But if you want to sell your phone I would always go with a factory reset.
