### ISSUE TITLE
[Feature Request] App Shortcuts

### ISSUE THREAD

**Issue by rodrigoswz** [andOTP/andOTP#185]
It would be cool to add App Shortcuts (Android 7.1+) to perform quick actions like "Scan QR-Code" and "Enter details".

**Comment by flocke** [comment]
That seems like something useful. I will have to take a look at how to implement this for the next release.

**Comment by rodrigoswz** [comment]
Nice! Thank you

**Comment by flocke** [comment]
Turns out this was easier than I expected ...
