### ISSUE TITLE
Partial key loss

### ISSUE THREAD

**Issue by benoliver999** [andOTP/andOTP#187]
#### General information

* **App version:** 0.5.0.1
* **App source:** F-Droid 
* **Android Version:** 7.1.2
* **Custom ROM:** LineageOS

#### Expected result
**What is expected?** TOTP keys are stored

**What does happen instead?** Some are lost

Very sorry for the vague report, but I can't really reproduce what happened.

I am storing tokens using password authentication. I added 4 or 5 keys to the app last week, now when I log in they are gone!

I can't empirically say that it's the ones I added that time, but I know at least two of them are.

Many of the other tokens I have stored are still there.

Is there anything I might have done wrong?

**Comment by flocke** [comment]
That is really strange, I never had a partial loss, if something happened in the past it were always all tokens. Could you try to get me a logcat and can you tell me which database encryption you are using (Android KeyStore or Password / PIN).

But if something went wrong earlier when you added the tokens the chances of figuring out what happened are very low.

**Comment by benoliver999** [comment]
I am using password encryption.

Here's a logcat after the phone has been on for a while: http://ix.io/1ciX
Here's one after a reboot and opening the app: http://ix.io/1ciY

I re-added a key and it's stuck around so I can't figure it out!

**Comment by benoliver999** [comment]
I'm going to close this because the phone I was using just stopped working... the internal storage has given up the ghost. This could have been the cause of the problem...!

**Comment by flocke** [comment]
Yeah, that seems like it could cause this kind of behavior.
Glad it wasn't something related to andOTP, although not glad you lost a phone.
