### ISSUE TITLE
Compact layout for the cards

### ISSUE THREAD

**Issue by flocke** [andOTP/andOTP#189]
- [x] Add an option to switch between different card layouts
- [ ] Add a more compact layout

**Comment by RichyHBM** [comment]
Is this not encompassed by the grid view?

**Comment by flocke** [comment]
Yeah, could be that this is exactly what was requested. I received this request per mail and just added it here to keep track.

**Comment by tasoili** [comment]
Personally I'd love there to be a more compact, non-tiled view. Check out https://itunes.apple.com/us/app/otp-auth/id659877384 for my favourite iPhone OTP app.

On an iPhone SE, this can show 11 codes at once.
LG V30 with andOTP is only able to show 7 even with a much larger screen.

**Comment by finsterwalder** [comment]
I would very mich like to see a much more compact design as well.
When I use smaller or no icons, the lines should also become slimmer.
And in addition it might even be an idea to offer a two column setup?

**Comment by finsterwalder** [comment]
> Is this not encompassed by the grid view?

What is the "grid view"? Or how can I activate it?

**Comment by ainola** [comment]
Not sure what this grid view is either. I imagine the general idea is to remove the padding so we can see many more entries a la aegis (by my rough estimate aegis can show 8 entries while andotp can show maybe 5)

**Comment by flocke** [comment]
I started this by adding the option to switch between different layouts.
For now I didn't add a more compact layout yet, this will come after the next release.

**Comment by finsterwalder** [comment]
OK! Looking forward to it! :-)

**Comment by finsterwalder** [comment]
And thank you very much for this nice app!

**Comment by flocke** [comment]
This was easier than expected with the new way of changing layouts. I added a first iteration of the compact layout (just reducing some padings). We can work on improving it over time after the next release, but that should happen in a new issue when the time comes.
