### ISSUE TITLE
Codes Provided By App Don't Work For Some Accounts

### ISSUE THREAD

**Issue by FunkyDarkKnight** [andOTP/andOTP#193]
#### General information

* **App version:** 0.6.0-beta2 (been using since at least 0.5.0.1 however, possibly even earlier - got from F-Droid either late last year or early this year; been letting it update since)
* **App source:** F-Droid
* **Android Version:** 7.0
* **Custom ROM:** None

#### Expected result
**What is expected?** 
All of the 2FA codes provided by the app should work as expected.
**What does happen instead?**
The 2FA codes provided by the app are denied, locking me out of some of my accounts. This happens on some of the accounts but not all. Some examples would be my Discord and Ubisoft account. My Google/Github accounts work fine however. I can access the accounts just fine with the backup codes they each provided but the 2FA codes from this app don't work at all. They worked when I first added 2FA to my accounts but as the months have gone on it has become less and less reliable.

One interesting bit of info - my Amazon account didn't work with the code the app provided but without changing it the code eventually worked after a few seconds. Maybe a timing issue? Not too well-versed on the technical side of 2FA and how it works exactly so apologies if it doesn't operate on timings at all.

I didn't backup/restore at all before I saw this issue start to happen. As a test I backed up, reinstalled the app, and restored my codes but the exact issue with the same accounts that are affected is still present, even after doing this a few times.

Used Android KeyStore authentication. Recently switched to Password / PIN but this issue started occurring while using Android KeyStore. Might have something to do with it?

As a test I used a backup code for one of my accounts and disabled 2FA. When I try to re-enable, it rejects all codes given by the app. I scanned in the QR code multiple times to make sure there wasn't any errors in reading.

#### Logcat
```
https://drive.google.com/file/d/1a03ud_p2uxyqpwFJsKcqdLbk_MvJ74lb/view?usp=sharing
```

**Comment by FunkyDarkKnight** [comment]
Aaaaaand I'm an idiot. Turns out my phone clock was just under a minute out from the actual time.

Sorry!

**Comment by flocke** [comment]
Yes, TOTP codes heavily rely on the clocks of the phone and the server being in sync. Maybe I should add a warning or reminder to sync the phones clock somewhere ...
