### ISSUE TITLE
Clone without attribution?

### ISSUE THREAD

**Issue by IzzySoft** [andOTP/andOTP#209]
#### General information

* **App version:** n/a
* **App source:** GitHub
* **Android Version:** n/a
* **Custom ROM:** n/a

#### Expected result
Attribution. 

**What does happen instead?**

Just to inform you: looks like [CometOTP](https://github.com/gigabytedevelopers/CometOTP) is using your code without attribution, copyright headers removed. Even the README.md is almost literally identical, just the app names replaced.

If you can confirm it's your code (I just compared a few places, and they looked very much alike) I wouldn't be surprised. A little while ago they did the same with "their" file manager (FireFiles, see [this issue](https://github.com/gigabytedevelopers/FireFiles/issues/2)). Looks like they haven't learned a thing from the shitstorm they earned then, though we gave them the "benefit of doubt" at that time, considering it a "beginners issue".

Sorry for abusing the template this way, but in the past I've made the experience that if I deleted the template, some bot auto-closed my issue …

#### Logcat
```
Paste your logcat here (or use something like Pastbin for long logs)
```

#### Steps to reproduce
 
 * take a loog at [Entry.java](https://github.com/gigabytedevelopers/CometOTP/blob/master/app/src/main/java/com/gigabytedevelopersinc/app/CometOTP/Database/Entry.java) "over there"
* take a look at the same file in your repo
* optionally, compare a few more files. The [README.md](https://github.com/gigabytedevelopers/CometOTP/blob/a2ff6d2016b10b89d4cd947608f39833feac8acb/README.md) is most obvious even to non-developers.
* the license file has just the two attribution lines removed

PS: I raised that issue [in their repo](https://github.com/gigabytedevelopers/CometOTP/issues/1) as well.

**Comment by enwokoma** [comment]
@IzzySoft. We didn't clone without attribution! 
Besides, if you use the word  `clone`, you make it sound as if we still build and update  CometOTP off the changes of the current andOTP which isn't right. We've made numerous updates on CometOTP independently, the idea of CometOTP comew from andOTP and it is boldly written on the About Page of CometOTP so, I honestly don't understand the misunderstandings. 
You know what, I just noticed that the CometOTP repo hasn't been updated for the past months (3-4) and the last time I remember, we have made over 17 app updates to CometOTP, we just haven't updated the repo to match what we have on our local server, I guess I would have to make the necessary changes to the repo anytime soon! 

Thanks for getting this to our knowledge!

**Comment by IzzySoft** [comment]
It might not be a clone as in `git clone` (checking the commit history, it rather seems like a block-wise copy-and-paste, just leaving out the copyright/credit headers) – but CometOTP uses code from here. So it should give credit to the fact. And no, this doesn't mean you keep updating from here – just that you used andOTP code as part of your project without saying so (but as with FireFiles, again strip the copyright headers from the source files).

All I'm saying is you should give credit when using parts of a project – not stripping any references (mentioned headers) to "camouflage" it.

I've put a note here and on your repo. I won't follow the issue further. It's up to you and the andOTP team what to do about this. I won't intervene if andOTP decides it's OK – even though I personally feel it is not.

**Comment by enwokoma** [comment]
Ok. I've heard you! I would updating them later this evening! 
Do have a nice day! 

Thanks,

**Comment by enwokoma** [comment]
I guess the best I can do in this situation is renaming the current [CometOTP](github.com/gigabytedevelopers/CometOTP) project from **CometOTP** to **CometOTP (andOTP)**, we could just delete the repo and make a fresh fork of the current andOTP project, where I would then add a reference that says _this fork was made for a onetime reference purpose only which was used for the development of CometOTP_ then make a totally new repo for CometOTP which doesn't reference andOTP because with this recent development, I guess  I am left with no option but to stripe the entire codebase of CometOTP and make it Closed-Source 

Tell me what you think about this.

**Comment by enwokoma** [comment]
I guess this commit https://github.com/gigabytedevelopers/CometOTP/commit/58bc27482c9faf208148abe0de28c5dc4e03a247 settles it all. 

Thanks!

**Comment by IzzySoft** [comment]
Thanks, Emmanuel – so it where quite a few files, as I guessed. I've left a comment on the commit (you could add your © line in some places as well).

From my POV this should settle it. I still leave it to @flocke having the last word (and closing the issue). Thanks for fixing it that soon, Emmanuel – and have a better start with the next project :wink: I know "third time lucky", but prefer otherwise in this case :speak_no_evil:

**Comment by RichyHBM** [comment]
Feels like this is an issue for CometOTP rather than AndOTP, so closing

**Comment by flocke** [comment]
I agree with @RichyHBM, this is more of an issue for CometOTP.

I know of the fork and even though it bugged me a little that they didn't really give any credit before my choice of license allows them to fork.

**Comment by IzzySoft** [comment]
Sure @flocke – which is why I opened it there first. This issue here was more to let you know (turns out unnecessarily, as you already knew). I feel it's indecent to not give credit when using bigger parts of code. Not needed for a one-liner, sure, but this was much more (see referenced commit).

But it's solved now, luckily – so we all can concentrate on better things now :wink:
