### ISSUE TITLE
Unlocking with password is not always necessary

### ISSUE THREAD

**Issue by Luke-91** [andOTP/andOTP#216]
#### General information

* **App version:** 0.5.1
* **App source:** Google Play 
* **Android Version:** 7.0
* **Custom ROM:** No

#### Expected result
**What is expected?**
Whenever the app goes into background (e.g. by pressing the home button) it should prompt for the unlock password when going to the foreground again (e.g. via the menu button).

**What does happen instead?**
It sometimes requires the password, it sometimes does not require the password.

#### Logcat
[log_no_password_prompt.txt](https://github.com/andOTP/andOTP/files/2300228/log_no_password_prompt.txt)

#### Steps to reproduce
* Unlock the app.
* Press the home button.
* Wait a few seconds.
* Open the app again.
* No password is (most often) required.

Hint: "requireAuthentication" is only set in onCreate() (and via ScreenOffReceiver), I believe it should be set in onResume() instead.

**Comment by Luke-91** [comment]
#208 is possibly related with this issue.

**Comment by flocke** [comment]
``onResume()`` is called a lot, for example when you open the settings, backup or about screen and return to the MainActivity afterwards. I don't think always re-authenticating there would be a good idea.
But I will look into how to detect if the app gets send to the background and maybe I can hook in there somehow.

**Comment by flocke** [comment]
This was easier than expected.

Using a ``LifecycleObserver`` the whole process, not just the ``MainActivity``, can be monitored and the ``requireAuthentication`` flag can be set when it is send to the background. That way it is not triggered when going to other activities.
