### ISSUE TITLE
[feature request] generating shared secret

### ISSUE THREAD

**Issue by knezi** [andOTP/andOTP#217]
Hi,

thanks for this app. Would you consider adding generating random secrets? There's an online service which requires me to fill in one.

Thanks.

knezi

**Comment by flocke** [comment]
That's very weird. I never heard of a site that expects the user to generate the secret himself, usually that's the sites job.
While we most certainly could do that in andOTP with not much effort I will need some more information, specifically the format the site wants the secret to be entered. Usually the secrets are transmitted as Base32 encoded strings, do you know if that's the same for the site you're using?

**Comment by knezi** [comment]
Yes, I was really surprised. It's a governmental organization, so it's difficult to discuss anything with them :/.
They said that the application for OTP must follow RFC 4226 and that the seed must be either in ASCII or hexadecimal format. I'm not sure what this is though. Should I get more information?

**Comment by flocke** [comment]
I'll have a look at the RFC again if I get back home next week. Maybe it says something about the encoding. I never bothered to check because its basically always Base32.

**Comment by RichyHBM** [comment]
Maybe they just want you to generate the secret rather than them? It seems very odd but also not something AndOTP should really need to support as its such an odd use case

**Comment by knezi** [comment]
@RichyHBM Yeah, I think that's the case. I agree if it's non-standard feature. It's just that claim it's a standard feature. They recommended me to use the application DS3Oath which I haven't found.

**Comment by flocke** [comment]
I don't think this is a standard feature, at least I have never seen it in any other OTP client or on any other OTP-enabled service.
If it is just the generation of the secret you can probably use an online service for that. It's basically just a random string in whatever encoding they want, I think there are a lot of online services out there that can do that.

**Comment by knezi** [comment]
> It's basically just a random string in whatever encoding they want, I think there are a lot of online services out there that can do that.

Right, it's just that I'm a bit afraid to use online services for that. I've tried to generate random strings, but it didn't go through, so there may be some constraints.

**Comment by flocke** [comment]
> Right, it's just that I'm a bit afraid to use online services for that.

I can understand that. Sadly I don't have an online service I can test this with, but if you have a PC with Linux on it you can try this command:
```
cat /dev/urandom | base32 | fold -w32 | head -n 1 | tee base32.txt | base32 -d | od -An -tx1 -w64 | sed 's/\W//g' > hex.txt
```
which will create two files for you: `base32.txt` which contains the random string in base32 encoding (for andOTP) and `hex.txt` which contains the same random string in HEX encoding for your service.

Just a shot in the dark, I don't know if it will work since I can't test it myself.

**Comment by knezi** [comment]
This works. Thank you.

**Comment by flocke** [comment]
Glad I could help.
