### ISSUE TITLE
Can't use andOTP with Google account

### ISSUE THREAD

**Issue by yhoyhoj** [andOTP/andOTP#219]
#### General information

* **App version:** 0.6.0-beta3
* **App source:** F-Droid
* **Android Version:** LineageOS 14.1
* **Custom ROM:** MicroG LineageOS fork

#### Expected result
**What is expected?** When adding 2FA to Google account, Google shows a QR code (otpauth:// url) and then asks for a OTP to confirm. 

**What does happen instead?** The OTP generated by andOTP is not accepted by Google : "Incorrect code"

#### Steps to reproduce
 
Enable 2FA with Authenticator on myaccount.google.com
Scan QRcode with andOTP
Type code when prompted by Google

**Comment by flocke** [comment]
I have been using andOTP with Google for a long time now and never had problems. Did you try it multiple times? Maybe there was an error when scanning the QR code.
Otherwise check the clock on your phone, if it is not synchronized correctly TOTP tokens won't  work.

**Comment by tessus** [comment]
I'm totally confused. I tried to setup 2fa with Google, but they do not use TOTP. They use their own system by sending a message via the Android API somehow. 
How do you even get a TOTP QR code in Google?

**Comment by flocke** [comment]
There should be an option to not use that method and use Google Authenticator instead, I think it's called "alternative second step" or something like that.

**Comment by tessus** [comment]
@flocke unfortunately there isn't:

<img width="636" alt="screen shot 2018-09-10 at 18 58 04" src="https://user-images.githubusercontent.com/223439/45328927-fb59fd00-b52b-11e8-9379-a8fe3a98cd38.png">

As you can see the only 2 other options are `Security Key` (e.g. Yubico) or `Text or Phone Call`.
Maybe they have removed TOTP unless you are already using it.
In any case, there's no way to ask Google, because the only info I get when searching or this topic is this exact screen. Sending a mail to Google is also impossible, so I'm stuck and not able to use TOTP with Google.

**Comment by flocke** [comment]
I'm gonna make a second Google account and check it out later on, maybe you are right and they removed it.

**Comment by flocke** [comment]
OK, I just looked in my Google account again and I have Text or Call enabled as first option and TOTP as second. Maybe you need to enable one of the three options it gives you first before you can enable TOTP as alternative.

**Comment by flocke** [comment]
@tessus Good to hear. No idea why they made it like this if you can remove the primary method later on again...

**Comment by pgera** [comment]
@tessus , is this a gsuite account ? I was greeted with this too recently when I tried to enable 2fa on a new gsuite account. I wonder if they are trying to deprecate TOTP, starting with gsuite accounts.

**Comment by tessus** [comment]
@pgera no, it's not a gsuite account. I thought about something else: maybe it's a geo location thing. We both are located in North America, the others in this discussion are in Europe.

**Comment by RichyHBM** [comment]
Seems like this issue is now resolved, please comment on here if not
