### ISSUE TITLE
[feature request] openkeychain integration for backups

### ISSUE THREAD

**Issue by benjumanji** [andOTP/andOTP#224]
I'd like to be able to backup the database by encrypting with a public key in my keychain.

I am willing to do this work, if it's likely to be accepted (the feature, I am not asking pre-approval for any old sloppy code).

The way I would see this working is user wants to backup, so the store is decrypted using pin / device key then re-encrypted with a pgp key of the users choosing.

**Comment by flocke** [comment]
This has already been implemented since the very first public release.

**Comment by benjumanji** [comment]
I apologise for wasting your time :grimacing:

**Comment by flocke** [comment]
No worries 😃
