### ISSUE TITLE
Allow app-only storage without encryption

### ISSUE THREAD

**Issue by haarp** [andOTP/andOTP#226]
Hello,

I would like to request the ability to store OTP secrets within the app's own storage (/data/data/org.shadowice.flocke.andotp/) unencrypted. It seems the only way to store them without extra passwords currently is to use Android's credential storage (which has its own problems, e.g. enforcing a lockscreen)

The reason I ask for this is because my automatic backup procedure dumps the entirety of /data. If the secrets in /data are encrypted, my backups will be of limited use - I cannot import them anywhere wihout the help of a working copy of andOTP - which is not always a given. So ultimately my reason for requesting this is portability and independence.

It would be very much appreciated. Thanks!

**Comment by pbanj** [comment]
This is why I don't use this. I really don't want to have to enter anything to be able to get my codes. Breaking backup solutions to achieve that is kind of crap. Would be nice to see this added so I can ditch Google authenticator

**Comment by flocke** [comment]
Sorry, but I won't be doing this. This app is focussed on security and storing the very sensitive OTP secrets in plain text is something that is NOT secure.
Besides that I won't be adding new features after the next stable release since I am doing a rewrite from scratch.

**Comment by flocke** [comment]
I might reconsider that feature at some point, but it is very low on my todo list. In the moment I don't have a lot of time to work on andOTP, so it will definitely not be added this year.

**Comment by vd1** [comment]
Hi Markus

Do you suggest that the app's usability could be improved
by being less stringent on security? If yes, what is the security feature
that you think can be dispensed with?
I may be completely missing your point here ...

Cheers
Vincent

**Comment by mbirth** [comment]
@vd1 Exactly this. Let the OS handle the security part (phone lock, filesystem permissions, storage encryption, etc.). Keep the app simple and only let it do what it's supposed to do: Give me tokens and give them to me fast - without having to unlock anything else but my phone. Similar to the experience with Google Authenticator: Unlock phone, touch app icon on home screen, read token.

I mean, technically, this is possible already by using the KeyStore, but judging by the warnings, that is not something you can trust, it seems.

**Comment by flocke** [comment]
I just want to add that the KeyStore has gotten a lot better over the last year. I haven't heard a lot of complaints recently and I am using it on my daily device since a few months.

**Comment by vd1** [comment]
Thanks Marcus!
Vincent

**Comment by mbirth** [comment]
@flocke I'm sorry, but "has gotten a lot better" is still not sounding very convincing. :wink: It has to be rock solid. I don't want to risk opening andOTP and sitting in front of an empty screen when I'm away from my backup codes.

**Comment by RichyHBM** [comment]
These issues were only ever reported on lineage/roms, at the end of the day why not try it? Keep your keys in Google authenticator and add some dummy codes to andOTP and make sure they don't disappear
