### ISSUE TITLE
Possiblity to auto-sync

### ISSUE THREAD

**Issue by bilelmoussaoui** [andOTP/andOTP#228]
Hey,

Thanks for the great application. I have recently added the backup/restore support of andOTP to a Linux 2FA application https://gitlab.gnome.org/World/Authenticator.
People have been requesting to add the auto-sync with Authy servers which is not possible. I was thinking if there's a possibility that you add the auto-sync from whatever service you want (like Dropbox, Google Drive or whatever) which could be used by the application I'm working on to keep the accounts on sync between both mobile and laptop for Linux users.

Thanks!

**Comment by RichyHBM** [comment]
This is currently not planned, the closest thing would be to setup a tasker task to create a backup every night or something like that
