### ISSUE TITLE
Add icon for MediaWiki

### ISSUE THREAD

**Issue by webracer999** [andOTP/andOTP#231]
Hello,

I've missing an icon for MediaWiki.
For all my other services I've found a corresponding icon.

Would be nice, if you can add it.

Regards, webracer999

**Comment by yilmzfurkan** [comment]
https://worldvectorlogo.com/download/wikimedia.svg

**Comment by webracer999** [comment]
yilmzfurkan, thank you for the link.
But WikiMedia (https://www.wikimedia.org) isn't MediaWiki (https://www.mediawiki.org).

I've found the logos of MediaWiki at https://commons.wikimedia.org/wiki/Category:SVG_MediaWiki_logos

MediaWiki has a sunflower in the logo.

**Comment by yilmzfurkan** [comment]
@webracer999 sorry, your right!

**Comment by webracer999** [comment]
@yilmzfurkan No problem! B-)
