### ISSUE TITLE
next release?

### ISSUE THREAD

**Issue by tessus** [andOTP/andOTP#237]
I was wondering, if something is blocking the 0.6.0 release.

beta3 has been out for 3 months now and there have not been any essential commits since then (other than icons)...

**Comment by RichyHBM** [comment]
The plan is to re-write AndOTP from scratch, I know Flocke has started this but both of us have been pretty busy as of lately. There wont be any new major features going into this codebase

**Comment by tessus** [comment]
Thank you very much for the info. In that case, please release 0.6.0 as is it is right now.

You can still create a 0.7.0 or 1.0.0 release when you have done all the rewriting. I'm just saying that there have been 72 commits since the last official release and creating a 0.6.0 release shouldn't be too much work.

I would also mention in the README that current development is limited to rewriting the code base and maybe you could also add an ETA (just in the ballpark, e.g. 1 months, 6 months, 1 year, ...).

**Comment by flocke** [comment]
Yeah, I'm planing releasing version 0.6.0 once all PRs and issues for the milestone are closed. Since those are mostly thumbnails it should be quick.

As for the rewrite, as Richy already said, I don't have a lot of time currently. But hopefully that should change by the end of this or the beginning of next year. I'm currently experimenting a bit with the encryption base whenever I have free time, but it's still far from ready.

**Comment by flocke** [comment]
Btw. thanks for checking and closing the issues @RichyHBM

**Comment by tessus** [comment]
@flocke 

> Yeah, I'm planing releasing version 0.6.0 once all PRs and issues for the milestone are closed. 

I was afraid of that.

> Since those are mostly thumbnails it should be quick.

Unfortunately it doesn't seeem so. Nothing really has happened during the last 3 months. This is why I suggested to just release 0.6.0 as is. And then go for a 0.6.1 when you have more time. If you don't have time we are still stuck with beta3 for another 3 months (this is extrapolated from the commits that have happened the last 3 months and the commits that have to happen to close the issues marked with the milestone 0.6.0). But according to you, by then you will have more time to look into the rewrite, thus 0.6.0 will either postpone or drag along `andOTP rewrite` or it will take more time then again to release 0.6.0.

**Comment by tessus** [comment]
Please, don't take my comments the wrong way, it's understandable that devs are busy.
I'm just saying that it would make sense to release 0.6.0 right away.

**Comment by flocke** [comment]
I get your point and I just went over the milestone and moved some not so important stuff to 0.6.1.
There are only 2 bugs left that I still want to address before pushing 0.6.0 to stable.

**Comment by tessus** [comment]
Thanks for your understanding.

**Comment by flocke** [comment]
I'm gonna try to address both bugs next week and then start the final preparations for the stable release (pushing the translations to Crowdin).

**Comment by flocke** [comment]
I just pushed the final translations to Crowdin. To give the translators enough time to work on the new strings I scheduled the release of 0.6.0 for Friday the 26th. There is still one PR remaining in the milestone for v0.6.0, but this is only thumbnail, should it not be merged until the deadline I will just move it to v0.6.1.

**Comment by tessus** [comment]
Awesome, thank you for the update.

**Comment by tessus** [comment]
Yiippieee!

Just saw that the new version is available in the Play Store. Quick question: will it also be available on F-droid?

**Comment by flocke** [comment]
Yes, it will be. The first build failed because of some error on F-Droids side (happened to a couple of other apps as well) but it will be retried soon.

**Comment by tessus** [comment]
Great, thx for the info.
