### ISSUE TITLE
See the keys of the accounts added by scan QR codes?

### ISSUE THREAD

**Issue by xversion1** [andOTP/andOTP#241]
Check if all requirements are fulfilled otherwise the issue will be closed without any comment

  * Add details to fields  below
  * Use search. Check if the issue is already reported before creating a new one. 
    https://github.com/andOTP/andOTP/issues
  * Try again after clearing the apps data before posting (**don't forget to backup**)
  * Record a logcat: https://goo.gl/mc71vk
  * Bug reports without logcat will be closed (I can not reproduce every bug myself and I can not fix them without logs)
  * Delete this info block

-----------------------------

#### General information

* **App version:all
* **App source:F-Droid
* **Android Version:all
* **Custom ROM:Lineage

#### Expected result
**What is expected?** 
Edit button to edit the key
**What does happen instead?**
Doesn't have it
#### Logcat
Don't have
Paste your logcat here (or use something like Pastbin for long logs)
Don't have

#### Steps to reproduce
 
 I want to see the key after adding an account by scan QR code. Is it possible? Because I need that key to add to another app without re-enable 2FA from the account.

**Comment by flocke** [comment]
This is currently not possible in the app and I don't think it will be implemented since I plan to stop adding new features after the stable release of v0.6.0 and focus on the rewrite.
For now you could always export a plain-text backup and get the shared secret from there.

**Comment by magiruuvelvet** [comment]
Just my 2 cents. Why not just keep the page open and scan the QR code in all apps or decode it to see the token secret, before continuing with the 2FA validation process?

The codes can also be seen in the backups, but keep in mind that doing insecure plaintext backups from andOTP is not a good idea, as everyone having access to that secret can generate valid tokens for that account.

**Comment by xversion1** [comment]
> This is currently not possible in the app and I don't think it will be implemented since I plan to stop adding new features after the stable release of v0.6.0 and focus on the rewrite.
> For now you could always export a plain-text backup and get the shared secret from there.

Thanks! always use OpenGPG backup, didn't notice that there's plain-text backup as well.

**Comment by xversion1** [comment]
> Just my 2 cents. Why not just keep the page open and scan the QR code in all apps or decode it to see the token secret, before continuing with the 2FA validation process?
> 
> The codes can also be seen in the backups, but keep in mind that doing insecure plaintext backups from andOTP is not a good idea, as everyone having access to that secret can generate valid tokens for that account.
> 
> I always save the QR code to my /tmp (ramfs) directory and add it in all apps and verify that all apps generate the same OTP before finally confirming the 2FA activation.

You're right! My reason is I've been using andOTP for along time with a lot of accounts and recently I just started use another OTP app on PC. This app can't scan QR code. If I want to add all of my accounts into it, there are two options: get the keys from andOTP or disable/enable 2FA of all the accounts again. You can see the second option can be a pain in the ass.
