### ISSUE TITLE
Add Instagram icon

### ISSUE THREAD

**Issue by TheSonAlsoRises** [andOTP/andOTP#247]
Hi,

Could you add the Instagram logo?

Website: https://www.instagram.com/
Image: https://upload.wikimedia.org/wikipedia/commons/e/e7/Instagram_logo_2016.svg

Thanks!

**Comment by flocke** [comment]
The problem here is that the logo has a big gradient part, which Android sometimes does not like.
I will see if I can get it to work reliable somehow ...

@RichyHBM Any ideas? Except using a bitmap of course :stuck_out_tongue_winking_eye:

**Comment by danielstreba** [comment]
Hey @flocke!

Maybe you could add the monochrome Instagram logo instead of the colored one.

[https://upload.wikimedia.org/wikipedia/commons/3/3e/Instagram_simple_icon.svg](https://upload.wikimedia.org/wikipedia/commons/3/3e/Instagram_simple_icon.svg)

**Comment by flocke** [comment]
I think I'm gonna use the simplified logo.
