### ISSUE TITLE
Intent encrypted backup error

### ISSUE THREAD

**Issue by TheCodeDestroyer** [andOTP/andOTP#250]
Currently Im backing up my data via intent(org.shadowice.flocke.andotp.broadcast.ENCRYPTED_BACKUP) all was well, but when I upgraded from 5.0.1 stable to latest 6.0.3 beta I get an error: 
Encrypted backups currently not allowed. Please enabled them in settings.

I looked for a toggle or anything but on first look through settings everything seems OK, also I did a manual encrypted backup and it was successful.

Am I missing something?

_Sent from my Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by flocke** [comment]
In the settings there is an option called "Backup Broadcasts" which you have to use to enable encrypted backups as a security measure.

**Comment by TheCodeDestroyer** [comment]
That was it, thank you!
