### ISSUE TITLE
Remove whitespaces when manually entering a secret

### ISSUE THREAD

**Issue by Wyall** [andOTP/andOTP#253]
#### General information

* **App version: 0.6.0**
* **App source:** Google Play
* **Android Version: 8.1.0**
* **Custom ROM: OmniRom**

Instagram now support 2fa via App. They give two options:
1. Use an app, but then you are redirected to the play store page of google authenticator. Not working with andotp
2. Do it manually: Then they give you a key/code(?), you enter that in andotp and check with the generated code. Like usual with scanning QR codes.

The problem with number 2: The key has 2 spaces between a set of letters, like this:
ERGT  326T  MI3Y  6W4S  XXXX  GTHG  XXXX  FYVX
For me this didn't work until I removed all the spaces. I'm not sure if this Instagram 2fa without SMS is a staged rollout, but I'd expect many people with the same problem.

But maybe someone else can verify first that I didn't just mess up something else while setting this up.

**Comment by flocke** [comment]
I don't have an Instagram account so I can't test it myself. But from what you describe it sounds like you did everything right. The secret should not contain spaces, I assume they did it do you can read it better.

**Comment by Wyall** [comment]
Yes, removing the spaces made it work. With spaces the generated code wasn't excepted by Instagram.

So I suggest adding a check for (white)spaces and removing them?

**Comment by flocke** [comment]
Seems like a good idea, I'll keep this open to track the issue.

**Comment by flocke** [comment]
Fixed in #426
