### ISSUE TITLE
Add phpMyAdmin logo

### ISSUE THREAD

**Issue by thmo** [andOTP/andOTP#254]
Could you also add the phpMyAdmin logo?

Since version 4.8.0, pma installations support [two-factor authentication](https://docs.phpmyadmin.net/en/latest/two_factor.html)

A favivon is [here](https://github.com/phpmyadmin/phpmyadmin/blob/master/favicon.ico), I didn't find it in a different format.

**Comment by alerque** [comment]
A full vector logo in SVG format is [available here](https://commons.wikimedia.org/wiki/File:PhpMyAdmin_logo_2010_hidef.svg).

**Comment by thmo** [comment]
Thanks for searching. From there we also get to know the upstream source:
https://github.com/phpmyadmin/data/blob/master/other_logo/logo.svg

I think it is licensed under CC BY 4.0, even allowing to modify the logo, if credit is given and an indication about the changes made.
