### ISSUE TITLE
add support for importing freeotp+ json backup file

### ISSUE THREAD

**Issue by rich-murphey** [andOTP/andOTP#255]
Would you accept a pull request that adds support for importing a FreeOTP+ json backup file?

I believe it would be a small amount of code based on this:

I modified one of the FreeOTP migration scripts, to support reading FreeOTP json export.
https://github.com/rich-murphey/freeotp-to-andotp

I'd be glad to submit some proposed code.

**Comment by max-wittig** [comment]
I would be code that is run on a few users(<5 I would guess) apps, once in a lifetime.

Why not just use the python script?
Even if it's not a lot of code, it adds more complexity to everything.

**Comment by rich-murphey** [comment]
Yes, the python script is adequate.
Thanks!
