### ISSUE TITLE
Remove issuer from label to avoid repetition

### ISSUE THREAD

**Issue by ThiefMaster** [andOTP/andOTP#257]
For example, the otpauth URL imported via QR code for my Google account is this:

    otpauth://totp/Google:my%40email.com?secret=lolnicetry&issuer=Google

This results in the pretty ugly label `Google - Google:my@email.com`.
The [spec](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#label) shows that the part before the colon is the issuer (and should match the one in the query string). So my suggestion would be to remove the `foo:` part from the label if it matches the issuer.

**Comment by flocke** [comment]
Issuer and label will be saved separately staring from the next version. So this will be invalid then, closing.

**Comment by asheiduk** [comment]
@flocke That's unfortunate because the Google Authenticator does and [recommends to remove redundant issuers][1] from the label. This saves precious space.

[1]: https://github.com/google/google-authenticator/wiki/Conflicting-Accounts#recommendation-for-code-generation-app-developers
