### ISSUE TITLE
Keep issuer and label separate

### ISSUE THREAD

**Issue by ThiefMaster** [andOTP/andOTP#258]
Currently issuer and label are [concatenated](https://github.com/andOTP/andOTP/blob/master/app/src/main/java/org/shadowice/flocke/andotp/Database/Entry.java#L128) at import time. I think it would be cleaner if issuer and label were stored separately.

This would allow showing them more nicely (with less truncation), e.g. like [how it's done in freeotp](https://user-images.githubusercontent.com/179599/48661436-ffe1eb00-ea71-11e8-8708-4ff321c3ea5f.png) (which is actually where I found this project as a more active alternative!).

It would also allow things such as grouping by issuer.

**Comment by mbiebl** [comment]
I'm looking for an alternative for google authenticator with backup functionality and andotp looks promising.
google authenticator also splits issuer and label and nicely presents them separately in the UI. This is useful if you have say two dropbox accounts to keep them apart more easily.
