### ISSUE TITLE
Last digit of PIN is available in application preview

### ISSUE THREAD

**Issue by alonbl** [andOTP/andOTP#261]
#### General information

* **App version:** 0.6.0
* **App source:** Google Play
* **Android Version:** 7.1.2
* **Custom ROM:** AICP LIBRA

#### Expected result
**What is expected?** 

Keep PIN hidden at all time

**What does happen instead?**

Last digit of PIN is available in application preview when switching between applications.

I know this is edge condition, but I believe it should be fixed.

#### Steps to reproduce
 
1.  Open CometOTP
2.  Type PIN when prompted
3.  Goto settings
4.  Lock display
5.  Unlick display
6.  Enter PIN as requested
7.  Switch applications "<"
8.  Notice the preview

**Comment by ziegenberg** [comment]
I'm not able to reproduce this bug with on an OnePlus 5 with Android 9 and andOTP version 0.7.0-play.

If nobody else is able to reproduce it, can this be closed?

**Comment by flocke** [comment]
I was never able to reproduce this as well. I will close it now since it's such an old issue.
