### ISSUE TITLE
Some Improvements

### ISSUE THREAD

**Issue by malnvenshorn** [andOTP/andOTP#263]
I'm coming from freeOTP and I noticed some aspects which I don't like about your app which prevents me from using it. Maybe my suggestions can help you to improve andOTP.

- The first thing I've noticed is the fact that I have to set a password (keystore is not working). Yes you can argue it improves security, but it is still 2FA. If someone has your phone and access to the app he still needs your login information and if someone has your login credentials and steals your phone to generate the token he might also spend some effort in figuring out the password for andOTP. Besides that if you loose your phone you should change your passwords anyway. But maybe it's just my opinion.

- The app is sluggish. Maybe this is related to the continuous generation of the tokens?! For example, opening the settings dialog takes ~8s on my Galaxy S5 mini. I would like an option to generate the token only if I click on  the entry, like it is in freeOTP.

- The size of the label is very small even with the lowest possible text size (12). I would suggest multiple rows or to align the icons on the right with the generated token so we have a complete line available.

I will continue watching this app, because in freeOTP I'm definitely missing the backup feature.

**Comment by rnc** [comment]
@flocke I would also like to see generate token on demand and custom images for uncommon providers (as per #225). 
Unfortunately it seems Dropbox doesn't implement SAF so backup doesn't work with it although reading e.g. https://www.sitepoint.com/adding-the-dropbox-api-to-an-android-app/ it seems feasible that andOTP could potentially integrate with Dropbox?

**Comment by flocke** [comment]
I'm not gonna implement any new features in andOTP in the near future as I am rewriting the entire app from scratch, see [The Rewrite](https://github.com/andOTP/andOTP/wiki/The-Rewrite). But I will think about your suggestions for the new app as soon as it is in a semi-usable state.

**Comment by flocke** [comment]
Closing this, since it is a very old issue and a lot has already been done to improve the raised points.
