### ISSUE TITLE
Add Backblaze icon

### ISSUE THREAD

**Issue by VoiDeD** [andOTP/andOTP#265]
Could the backblaze icon be added?

https://www.backblaze.com/
https://upload.wikimedia.org/wikipedia/en/9/9b/Backblaze_Logo.svg

Probably just needs the fireball without the text.

Thanks!

**Comment by krisu5** [comment]
[There's pull request already pending.](https://github.com/andOTP/andOTP/pull/243)

**Comment by flocke** [comment]
PR #243 merged
