### ISSUE TITLE
Ubisoft unable to recognize andOTP codes

### ISSUE THREAD

**Issue by kgursu** [andOTP/andOTP#269]
Hi. 
I could not use andOTP as an replacement for Google Authenticator at Ubisoft Account Services. Is that a known issue or am I doing something wrong?
Thanks.

**Comment by flocke** [comment]
I'll have to check this, I have Ubisoft in andOTP but haven't used it for a while now. I will try if and report back.

**Comment by kgursu** [comment]
Any news on this?

24 Ara 2018 Pzt 11:39 tarihinde Jakob Nixdorf <notifications@github.com>
şunu yazdı:

**Comment by flocke** [comment]
I am not at home over the holidays so I can't really check. I will try it in the new year when I am back home.

**Comment by jaredbriskman** [comment]
For what it's worth, I just setup andOTP with Ubisoft Account Services 2FA, and everything worked perfectly. 

I scanned the QR code provided, instead of entering the key manually.

**Comment by kgursu** [comment]
Hmm, then it would be something on my side. Thanks...

Jared Briskman <notifications@github.com>, 28 Ara 2018 Cum, 03:18 tarihinde
şunu yazdı:

**Comment by kgursu** [comment]
I'm encountering the same issue again, after leaving it there untouched for a long time.
Do you have any recommendations??

**Comment by kgursu** [comment]
When I try to scan the QR code, AndOTP recognize it as invalid. Alternatively, I enter the code for it, then AndOTP crashes...

**Comment by flocke** [comment]
That sounds like they are using invalid Base32 encoding for their secret. There was a bug that caused andOTP to crash when manually entering an invalid secret. It is fixed in v0.7.1-beta1 but it should tell you that your secret is invalid.

**Comment by flocke** [comment]
Could someone test this again? We recently updated the library used to decode the Base32 secrets, it should now support decoding most Base32 strings, even if they don't fully comply with the strict form.

**Comment by kgursu** [comment]
It seems to be working now. It required me some steps I don't remember fully now.
Probably on this one, I needed to close my blue color removing program f.lux, which seemed to be odd. But I could possibly mix issues here.
I did solve it anyway. Thanks for this fix!...
