### ISSUE TITLE
Consider removal of some logos (Patreon, PayPal, Steam) to avoid confusion

### ISSUE THREAD

**Issue by jancborchardt** [andOTP/andOTP#272]
#### General information

(The info is not relevant here though I think)

* **App version:** 0.6.1
* **App source:** F-Droid
* **Android Version:** 8.1
* **Custom ROM:** LineageOS 15.1

#### Expected result
**What is expected?** 
Icons of services which don’t support TOTP are not shown in the "Change image" picker.

**What does happen instead?**
Icons of services like Patreon, Steam and PayPal are displayed. I went through the icons to see which other services I use could be secured via TOTP, and for those 3 it was not possible as they use SMS (Patreon and PayPal) or their own app (Steam).

#### More info

- Patreon removed TOTP support for any new 2FA setup https://support.patreon.com/hc/en-us/articles/206538086-How-Do-I-Set-Up-Two-Factor-Authentication-
   > "Moving forward, SMS two factor authentication will be our only two factor option."
- PayPal only makes TOTP possible with a really bad unofficial hack https://medium.com/@dubistkomisch/set-up-2fa-two-factor-authentication-for-paypal-with-google-authenticator-or-other-totp-client-60fee63bfa4f
   > "Several people have mentioned the PayPal mobile apps still only work with SMS security codes unfortunately."
- Steam does not support TOTP cause they have their own app, only works via a hack through andOTP special features: https://github.com/andOTP/andOTP/wiki/Special-features
   > ["Disclaimer: Steam trading won't work with this enabled since you won't be able to confirm trades. This will never be implemented, so please nobody ask for it, this is far beyond the scope of this app!"](https://github.com/andOTP/andOTP/issues/38#issuecomment-337139637)

If outright removal is not something you would like to do, maybe they should only show after you enabled the [special features](https://github.com/andOTP/andOTP/wiki/Special-features#how-to-enable-the-special-features) in andOTP? At least for the Steam icon that’s directly related, since the functionality is only activated then.

**Comment by flocke** [comment]
I won't be implementing this myself as I am trying to focus on [the rewrite](https://github.com/andOTP/andOTP/wiki/The-Rewrite). But I would be open for PRs if someone wants to tackle this (removing Patreon and only showing Steam and PayPal when Special Features are enabled).

**Comment by max-wittig** [comment]
Steam actually works. I use steam otp via the offical tutorial.

**Comment by jancborchardt** [comment]
@flocke cool, thanks for the clarification! Submitted a pull request to remove the Patreon logo at https://github.com/andOTP/andOTP/pull/273

The other part:

> only showing Steam and PayPal when Special Features are enabled

is beyond my ability, so anyone is welcome to help. :slightly_smiling_face:

**Comment by krisu5** [comment]
You can still use Patreon with TOTP if you have connected before this stupid change happen and have the secret key / QR.

So no, at least don't remove Patreon (even though it's not big deal, but whatever).

**Comment by ItTakesTwo** [comment]
The same is valid for PayPal as you can circumvent their SMS procedure for 2FA and use your preferred OTP app.

**Comment by AbrarSyed** [comment]
Paypal has since added first-class support for TOTP applications. I am not sure exactly when, but I enrolled with andTotp just yesterday.

![Screenshot_2019-04-03 Security Settings](https://user-images.githubusercontent.com/523593/55491730-ad0d6800-55fb-11e9-85ef-499eac16f31d.png)

**Comment by RichyHBM** [comment]
Sounds like all these services are still valid, I may look into a way of splitting the "experimental" logos from the main ones, but I don't think this should be in 0.6.3
