### ISSUE TITLE
Add RIPE Network Coordination Centre (NCC) icon

### ISSUE THREAD

**Issue by Fusl** [andOTP/andOTP#275]
https://www.ripe.net/about-us/press-centre/ripe-ncc-logos

**Comment by bortzmeyer** [comment]
Just for the record: I use AndOTP with RIPE-NCC and it works fine.

**Comment by flocke** [comment]
The main problem with the icon is that it contains gradients, which have caused problems with logos before. I will take a look again once I have more time.

**Comment by revuwa** [comment]
I grapped just the symbol of the logo and saved them as two versions:

- RipeNcc_96x96.svg = colored (untouched)
- RipeNcc_96x96_bw.svg = black/white (without color-gradients)

[RIPE_NCC.zip](https://github.com/andOTP/andOTP/files/3248364/RIPE_NCC.zip)

Hope this helps in any way.
