### ISSUE TITLE
Add INWX logo

### ISSUE THREAD

**Issue by mxmehl** [andOTP/andOTP#283]
Would you please add the INWX logo, one of the largest domain providers in Germany?

From the PNG file I've created a SVG file with Inkscape. However, it doesn't look like your much simpler XML files... Both files attached.

Thanks!

[inwx.tar.gz](https://github.com/andOTP/andOTP/files/2730512/inwx.tar.gz)

**Comment by flocke** [comment]
Thank you for the SVG version. The XML files are a special vector format for Android, you can use Android Studio to import SVG files and convert them.
