### ISSUE TITLE
Dark and Black theme should colorize navigation bar

### ISSUE THREAD

**Issue by Geobert** [andOTP/andOTP#284]
#### General information

* **App version:** 0.6.1
* **App source:** Google Play
* **Android Version:** 9
* **Custom ROM:** OxygenOS

#### Expected result
**What is expected?** 

When choosing dark or black theme, navigation bar should be dark as well

**What does happen instead?**

The navigation bar is white

#### Logcat
N/A

#### Steps to reproduce
 
choose dark / black theme

**Comment by augustuswillem** [comment]
Was just about to make this suggestion. Hope this gets implemented soon, I really want that pretty OLED look.

**Comment by HarryJohnso** [comment]
@Geobert @augustuswillem as mentioned in the pull request here [https://github.com/andOTP/andOTP/pull/371](https://github.com/andOTP/andOTP/pull/371) it might solve this issue.

**Comment by flocke** [comment]
Fixed in #371
