### ISSUE TITLE
Add animebytes icon

### ISSUE THREAD

**Issue by jug007** [andOTP/andOTP#286]
Hello
Would be cool if the animebytes logo could be added.
https://github.com/anniemaybytes/calamari/blob/master/randomstuff/logos/ab_logo.svg
It is normally pink like in their favicon: https://github.com/anniemaybytes/calamari/blob/master/assets/public/favicon.ico
Dunno if my browser is just being weird or if the vectorgraphic actually has no color.

**Comment by flocke** [comment]
That's really strange with the color, the SVG also had none in Inkscape. I just used the pink from the favicon.
