### ISSUE TITLE
Add Plesk Icon

### ISSUE THREAD

**Issue by Coernel82** [andOTP/andOTP#290]
Eihter the Plesk Favicon as it is a square:
https://i.pinimg.com/favicons/d67fe1370ecdf878446ac94a35ee2720cfb2ef4a25650e88fb560cc6.ico?1db747255c64a30f9236e9d929e986ca

or the real logo:
https://fly4yvafxrnhqjg3k6k6hhyb-wpengine.netdna-ssl.com/wp-content/themes/sidekick/assets/images/design/logo_plesk.png

Thank you!

**Comment by RichyHBM** [comment]
Hello, please provide an SVG image. Closing for now as I am adding all logos requested for 0.6.3 and need to clear up the list, please open again if you find an SVG. @flocke If you think this should be added let me know
