### ISSUE TITLE
Codes Show In Reversed Order If System Language Is RTL

### ISSUE THREAD

**Issue by michael2210** [andOTP/andOTP#292]
#### General information

* **App version:** 0.6.1
* **App source:** Google Play
* **Android Version:** 9 (Android Pie)
* **Custom ROM:** Stock S9

#### The Problem

Lets say that the 2FA code to a site should be 123 456,
the code shows on the app as 456 123.
It does it (switching the order of the 2 sets of 3 numbers) to all the codesin the app.

It's because my system language on my android is Hebrew which is RTL (Right To Left).
If I change my system language to English the code is in the right order.

**Comment by flocke** [comment]
There is a PR open that should fix this (https://github.com/andOTP/andOTP/pull/280).
But since I don't use a RTL language I can't really test it and say if it is correct, would you be willing to test a build @michael2210?

**Comment by flocke** [comment]
Fixed in #280.
