### ISSUE TITLE
Don't show PIN while it is being entered

### ISSUE THREAD

**Issue by lauritzt** [andOTP/andOTP#294]
### General information

* **App version:** 0.6.1
* **App source:** F-Droid
* **Android Version:** 8.0

### Current result

Currently, when I enter my PIN, the most recent number is shown. This makes it significantly easier for others to shoulder-surf.

### Expected result

The PIN should be hidden while it is being entered, such that the numbers are never shown in the input field. This way, a user could simply cover up the keypad to avoid shoulder-surfing. The user would still be able to tap the eye icon to show the entire PIN.

This would also fix #261 (if I'm interpreting it correctly).

**Comment by flocke** [comment]
I think that's actaully an Android setting. You should be able to disable this in you devices Settings (under Security if I remember correctly). But I will have a look again, maybe it is because of my custom ROM...

**Comment by lauritzt** [comment]
It is indeed. Thank you!
