### ISSUE TITLE
Add icon for Mega

### ISSUE THREAD

**Issue by laopisai** [andOTP/andOTP#297]
Please add icon for Mega

https://github.com/meganz/firefox-web-extension/tree/master/images

![icon](https://raw.githubusercontent.com/meganz/firefox-web-extension/master/images/icon_128.png)

**Comment by flocke** [comment]
Forgot that Mega was already added in 44c22a7acb2fe3cbf6eb1f544148c38c68d1b9e2. It will be in the next release.
