### ISSUE TITLE
Unable to open / decrypt backup encrypted via PIN on other device

### ISSUE THREAD

**Issue by dragetd** [andOTP/andOTP#299]
#### General information

* **App version: 0.6.1**
* **App source:** F-Droid
* **Android Version: 7.1**
* **Custom ROM: Linage 14.1 / microg Lineage 14.1**

#### Expected result
I have two devices, both the same Android version (tho one is using microg builds, the other regular lineage + gapps)

Both running 0.6.1. On one device I have my OTPs saved and wanted to backup them. The setting had been to use the dvice keys and not a password or pin. I switched this setting, set a pin and andOTP told me it had successfully migrated the database.

I saved the encrypted backup and transfered it to the other device. On this device I tried to import it and provide the same pin. But andOTP refuses to import it, saying the password is bad.

Is this supposed to work? Why does it still try to use the android KeyStore as seen in the attached Logcat (it is from the recieving device)?

And is Password and Pin the same, just with a different input interface or is the password '123' different to the pin '123' (eventho I tried both)

#### Logcat
```
02-20 04:28:41.092 W/WindowManager(788): Attempted to remove non-existing token: android.os.Binder@268fd96
02-20 04:29:13.210 W/System.err(22279): javax.crypto.IllegalBlockSizeException
02-20 04:29:13.210 W/System.err(22279): 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
02-20 04:29:13.210 W/System.err(22279): 	at javax.crypto.Cipher.doFinal(Cipher.java:2056)
02-20 04:29:13.210 W/System.err(22279): 	at org.shadowice.flocke.andotp.Utilities.EncryptionHelper.decrypt(EncryptionHelper.java:150)
02-20 04:29:13.210 W/System.err(22279): 	at org.shadowice.flocke.andotp.Utilities.Settings.getBackupPasswordEnc(Settings.java:390)
02-20 04:29:13.210 W/System.err(22279): 	at org.shadowice.flocke.andotp.Activities.BackupActivity.doRestoreCrypt(BackupActivity.java:419)
02-20 04:29:13.210 W/System.err(22279): 	at org.shadowice.flocke.andotp.Activities.BackupActivity.onActivityResult(BackupActivity.java:272)
02-20 04:29:13.210 W/System.err(22279): 	at android.app.Activity.dispatchActivityResult(Activity.java:6937)
02-20 04:29:13.210 W/System.err(22279): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4122)
02-20 04:29:13.210 W/System.err(22279): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4169)
02-20 04:29:13.210 W/System.err(22279): 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
02-20 04:29:13.211 W/System.err(22279): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
02-20 04:29:13.211 W/System.err(22279): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-20 04:29:13.211 W/System.err(22279): 	at android.os.Looper.loop(Looper.java:154)
02-20 04:29:13.211 W/System.err(22279): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
02-20 04:29:13.211 W/System.err(22279): 	at java.lang.reflect.Method.invoke(Native Method)
02-20 04:29:13.211 W/System.err(22279): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
02-20 04:29:13.211 W/System.err(22279): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
02-20 04:29:13.211 W/System.err(22279): Caused by: android.security.KeyStoreException: Unknown error
02-20 04:29:13.211 W/System.err(22279): 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:676)
02-20 04:29:13.211 W/System.err(22279): 	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
02-20 04:29:13.211 W/System.err(22279): 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
02-20 04:29:13.211 W/System.err(22279): 	... 16 more
```

**Comment by flocke** [comment]
The password and PIN are the same, it just changes the keyboard so you can input the PIN easier.

But the backup is encrypted with a different password that you can set in the Settings, it's not tied to the app authentication.

**Comment by dragetd** [comment]
Ahhh.

Well, the 'Authentication' setting is right above the 'Database encryption' - where I can enter the app password. The settings for the the database encryption pin is waaay down. This is very confusing to say the least. :-/

I tried setting the pin in the bottom setting and still failed to import the backup, but I am not 100% sure if I really exported it correctly. I will try again later. Or did you already find an issue (since you added the 'bug' label)?

**Comment by flocke** [comment]
The settings on the top of the page are for the internal database (authentication and encryption settings). And the settings on the bottom are for the backups. You have to set the same "Backup password" on both phones and everything should work.

There is no reason for the "bug" label.
