### ISSUE TITLE
Initial Setup Password / PIN default not working properly

### ISSUE THREAD

**Issue by RichardUUU** [andOTP/andOTP#301]
#### General information

* **App version:** 0.6.1
* **App source:** Google Play / F-Droid / GitHub / ... Google Play
* **Android Version:** 9
* **Custom ROM:** n/a

#### Expected result
**What is expected?** 
During initial setup, second screen defaults to Password/PIN. Third screen should say: Since you have chosen Password / PIN

**What does happen instead?**
Third screen says: Since you have chosen Android KeyStore

#### Logcat
```
Nothing to log
```

#### Steps to reproduce
 See above
 * ...

**Comment by jean** [comment]
Is this a UI issue or is it impossible to actually select password/PIN?

**Comment by just1nw** [comment]
I also saw this issue with the app installed from the Google Play Store (v0.6.2). The selection defaulted to Password/PIN but the second screen indicated that I had selected the Android KeyStore. I went back to the initial setup page and changed to Android Keystore and back again to Password/Pin and i then showed me the correct setup screen for the Passsword/PIN option.
