### ISSUE TITLE
Add HashiCorp Vagrant Cloud icon

### ISSUE THREAD

**Issue by karlding** [andOTP/andOTP#302]
It would be nice to have an icon for HashiCorp's [Vagrant Cloud](https://app.vagrantup.com).

**Comment by RichyHBM** [comment]
Please would you be able to link to an SVG of the icon?

**Comment by karlding** [comment]
There is an SVG logo inline on the linked page.

**Comment by flocke** [comment]
The inlined SVG wasn't really useful (it was all black, I assume it only really works together with the CSS of the page). But luckily a quick image search yielded some other SVG versions.
