### ISSUE TITLE
Add Uber icon

### ISSUE THREAD

**Issue by karlding** [andOTP/andOTP#303]
It would be nice to have an [Uber](https://www.uber.com) icon. They support both Software and SMS tokens as of last year.

SVG icon available here (although it's not square): https://commons.m.wikimedia.org/wiki/File:Uber_logo_2018.svg

**Comment by flocke** [comment]
We cloud just use the app icon, I found a SVG for that as well:

![uber](https://user-images.githubusercontent.com/76665/54013136-62bdd600-4178-11e9-8178-eb926daf0326.png)

What do you think @karlding, @RichyHBM?

**Comment by karlding** [comment]
Sure, I'm okay with either.

Just as a small note, that is [no longer the app icon](https://www.theverge.com/2018/9/12/17851248/uber-new-logo-font-app-design) after their redesign.

**Comment by flocke** [comment]
I didn't know that, then we should use the current logo. I will see what I can find.

**Comment by RichyHBM** [comment]
I prefer the square icon, we can always update it if we find the new logo
