### ISSUE TITLE
Support Web Authentication (WebAuthn)

### ISSUE THREAD

**Issue by AWalton** [andOTP/andOTP#304]
Web Authentication standard is now officially a W3C recommendation: https://www.w3.org/TR/2019/REC-webauthn-1-20190304/

It's intended to replace passwords as the default login factor but certainly could be used in 2FA or MFA. 

WebAuthn can be tested here: https://webauthn.org/

**Comment by flocke** [comment]
I'll have a look, but it seems it needs network access permissions, which is something I would like to keep out of andOTP.

**Comment by relatev** [comment]
I think this would be great benefit for the OpenSource community, as currently only google provides a closed sourcebooks FIDO implementation for android through the gsm api.

**Comment by flocke** [comment]
I will close the issue for now. If I will ever implement this than it would be a new app, not inside andOTP because of the network permissions. But since I don't have a lot of time currently it will be very unlikely that this will happen any time soon.
