### ISSUE TITLE
Backups aren't easy by default: menu stays dimmed until you select a folder

### ISSUE THREAD

**Issue by bortzmeyer** [andOTP/andOTP#308]
* **App version:** 0.6.1
* **App source:** Google Play 
* **Android Version:** 7.1.2
* **Custom ROM:** No, standard system of the Fairphone 2

I select Backup ("Sauvegarde" since my system is in french), ten Encrypted backup ("Sauvegarde chiffrée") I get a screen with the proposed name for the file (p_account.json.aes) but the button Save ("Enregistrer") staus is dimmed, I cannot select it. I can change the name of the backup file but it does not change the state of the button. I tried the other types of backup (clear text and PGP, with OpenKeychain), same problem.

This is because by defauilt AndOTP does not select a folder to put the backup in. You have to select one from the hamburger menu on the top left. I find that disconcerting. Other apps don' work that way.

**Comment by flocke** [comment]
The screen to select the file is actually part of the Android system, not andOTP. But I will look into how to change the default folder for that screen.

**Comment by flocke** [comment]
I couldn't find a way to get a default starting folder for that file select screen. And since it is part of the Android system and not andOTP I am closing this for now.
