### ISSUE TITLE
Automatically pull thumnail from website favicon

### ISSUE THREAD

**Issue by bquistorff** [andOTP/andOTP#309]
Would there be a way to automatically get the thumbnail for entries give the label? Often the text begins with the service name and sometimes it includes the TLD name (e.g. `privacy.com` rather than just `privacy`). When this is the case, could the app pull the favicon from the website and use that as the thumbnail? It wouldn't get complete coverage, but would help somewhat. It would require permission for internet access.

**Comment by 5t0rmr1d3r** [comment]
When I remember right, this was already discussed in the past. The common opinion was, that for security reasons, andotp should not have own internet access.

**Comment by RichyHBM** [comment]
More so than that, andOTP has no way of actually knowing what code is for what site, usually the labels given when scanning a OTP QR code dont intclude any site info, so it would result in more effort to then add the site.

**Comment by flocke** [comment]
What @5t0rmr1d3r and @ RichyHBM said. I am really against adding network permissions to andOTP since that is nothing a simple 2FA app needs im my opinion. There will be an option to add you own images in the new app I am currently writing (maybe not right after the first release, but it's on my to do list).

**Comment by bquistorff** [comment]
Those are good points. One can download the favicon in a browser using links like [icons.duckduckgo.com/ip2/www.stackoverflow.com.ico](https://icons.duckduckgo.com/ip2/www.stackoverflow.com.ico) and [https://www.google.com/s2/favicons?domain=www.stackoverflow.com](https://www.google.com/s2/favicons?domain=www.stackoverflow.com).

**Comment by RichyHBM** [comment]
How do we know what the domain is though? Anyway for now this seems like its a no
