### ISSUE TITLE
Please highlight token when it is about to expire

### ISSUE THREAD

**Issue by hvhaugwitz** [andOTP/andOTP#311]
Sometimes I start to type in the token just before it expires, so I have to re-type the new token.

It would be helpful, if `andOTP` would highlight the token (for example in red font colour) when the token is about to expire (eg in less than 8 seconds for a 30 second token).

#### General information

* **App version:** 0.6.1
* **App source:** F-Droid
* **Android Version:** 8.1.0
* **Custom ROM:** No

**Comment by flocke** [comment]
Nice idea! It will probably not make it into andOTP anymore, but I will surely implement it in [the rewrite](https://github.com/andOTP/andOTP/wiki/The-Rewrite).

**Comment by flocke** [comment]
Implemented in PR #410 by @Ullas-Aithal
