### ISSUE TITLE
Add TransIP icon

### ISSUE THREAD

**Issue by Forage** [andOTP/andOTP#312]
You chose to stick to a fixed list of icons, so here's another one to add ;)

Please include the [TransIP](https://www.transip.nl/) icon:
https://www.transip.nl/img/transip/favicons/apple-touch-icon.png

There's a dark version as well, but including both might be a bit overkill: https://pbs.twimg.com/profile_images/996296331504373761/0UFygf8Y_400x400.jpg

**Comment by RichyHBM** [comment]
Hello, please provide an SVG image. Closing for now as I am adding all logos requested for 0.6.3 and need to clear up the list, please open again if you find an SVG. @flocke If you think this should be added let me know

**Comment by Forage** [comment]
And this you tell me two months after creating the issue, right after having released a new version?

[TransIP.zip](https://github.com/andOTP/andOTP/files/3247233/TransIP.zip)

**Comment by flocke** [comment]
Those look good. Thank you for submitting them.
And sorry for your trouble, the last weeks have been pretty chaotic for me causing me to miss some stuff for the release.
