### ISSUE TITLE
What is the significance of the "Algorithm" setup parameter?

### ISSUE THREAD

**Issue by jaybeers** [andOTP/andOTP#315]
This is probably just a side effect of my being somewhat new to really looking into this stuff, but...what is the significance of the "Algorithm" parameter when you're setting up a new TOTP entry?  Obviously it's a hash algorithm, but I mean...what does that _mean_?  Are you specifying the hash algorithm that the host is using?  What is being hashed?  I thought the string that you type in is the actual cleartext shared secret...where does hashing enter the equation?

I've always just left it at the default `SHA1` setting and been fine when it comes to the practical problem of using the tool, but that cursed curiosity has reared its head.  :)

**Comment by flocke** [comment]
The algorithem is used internally to calculate the token from the secret key and the current time. Basically it calculates a HmacSHA1 (or whatever algorithm you select) token of the current time using the secret key, which is then used to generate the token (there are some more steps involved but that's where the algorithm comes into play). If you want more specific details just search for the TOTP specification, it's all described in there.

In practice basically only HmacSHA1 is ever used but the specification theoretically also allows for other algorithms, so to be fully compliant with the TOTP standard andOTP also supports those.

**Comment by jaybeers** [comment]
Cool, that's the answer I was looking for...thanks!  :)
