### ISSUE TITLE
Add Firefly III icon

### ISSUE THREAD

**Issue by lucavallerini** [andOTP/andOTP#317]
Firefly III is a selfhosted personal financial manager that offers 2FA authentication.

You can find an icon here (unfortunately PNG only) https://github.com/firefly-iii/firefly-iii/blob/master/public/android-chrome-512x512.png

Thank you.

**Comment by RichyHBM** [comment]
Hello, please provide an SVG image. Closing for now as I am adding all logos requested for 0.6.3 and need to clear up the list, please open again if you find an SVG. @flocke If you think this should be added let me know

**Comment by lucavallerini** [comment]
Hello, the only SVG that I can find is this one https://github.com/firefly-iii/firefly-iii/blob/master/public/safari-pinned-tab.svg but I do not think this is suitable for our purpose. I will try to contact the developer to see if he can provide an SVG icon too.

**Comment by flocke** [comment]
@lucavallerini That would be nice. I will reopen the issue once we have a SVG icon 👍
