### ISSUE TITLE
Forgot my unlock code...

### ISSUE THREAD

**Issue by lolalalol** [andOTP/andOTP#319]
Android 5 / F-droid / v 0.6.1

I sadly forgot my AndOTP unlock code/password...
So how can I deal with it ?   :o)

**Comment by flocke** [comment]
Without your code there is no way to access your data, since it is all encrypted with your password.
If you have a backup you can reset the app (go to your devices Settings -> Apps -> andOTP -> Storage -> Clear Storage), set everything up again and import the backup.

**Comment by lolalalol** [comment]
Thank you.
No backup but still I clear andOTP datas...
