### ISSUE TITLE
Moving list entries fails when "all markers" is not selected

### ISSUE THREAD

**Issue by Gnarfoz** [andOTP/andOTP#331]
#### General information

* **App version:** 0.6.1
* **App source:** Google Play
* **Android Version:** 8.0
* **Custom ROM:** -

#### Expected result
**What is expected?** 
Touch, hold, and drag to move list entries around.

**What does happen instead?**
Touch, hold, start moving and the drag operation will quickly be interrupted and the list entry be reset to its original position.

**Comment by flocke** [comment]
That's how it should be. As long as the "all markers" option is not selected there could be entries in the list that are not shown in the current view.
Reordering the entries without the complete list won't work. Imagine for example there are two entries shown, but in reality there are two more, currently hidden, entries in between them. If you now drag an entry between the two shown ones andOTP has no idea how to order the hidden ones.
