### ISSUE TITLE
andOTP Web Extension

### ISSUE THREAD

**Issue by krestaino** [andOTP/andOTP#332]
I've been working on a web extension that imports backups from the app. I'm curious what you think so far. I plan to add a few new features soon and wanted to pick your brain.

https://github.com/krestaino/andotp-extension
https://chrome.google.com/webstore/detail/andotp-extension/apbpiclbhifcmlbhbhillogjkphjdamd

**Encrypted backup support**

I'm really prioritizing this, right now the web extension saves the JSON backup to localStorage. I'm really not too sure of the security concerns with this, so at the very least, I'd like to keep it encrypted. I was digging through some old issues on this repo trying to understand how the JSON backup is encrypted, and I found an issue #295 where you mention it, but I've been having a hard time decrypting it in JavaScript. Any suggestions or pointers would be really helpful.

**Thumbnail support**

I'd like to add thumbnail support like you have in the app, but it's not possible with the current JSON backup structure. It got me thinking, if you allowed users to store the URL for the service, you could use something like [this API](https://favicongrabber.com/service-api-reference) to grab the thumbnails automatically. Then you wouldn't need to maintain them in the repo. Also, I could then use them in the web extension. :)
 
**Sync with phone**

There's several ways to go about doing this. A few ideas:

- Google Drive
- GitHub Gist, kinda like [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) for VS Code.
- **API:** HTTPS POST request with encrypted JSON backup to an endpoint the user sets in settings. A response would sync the app if it's out of date.

That's all. I really like andOTP, being able to backup and restore my 2fa keys is so nice. It was a real pain before I found your app. I appreciate all the work you've done.

**Comment by corbolais** [comment]
@krestaino I would rather stay away from URLs in a security related software. Also, I don't need thumbnails, so this is deprecated as far as I am concerned as a user.

webextenstions: same thing for backup. Ok, you're encrypting backups at least. I'd prefer transferring them directly in an encrypted manner.

cheers

**Comment by Rik44444** [comment]
hi all, i would be a big fan of this!! is it fully operational atm? can i use it as a regular user?

**Comment by Rik44444** [comment]
and thanks for all the great work on andOTP!! my fav auth app by far.

**Comment by Rik44444** [comment]
@flocke @RichyHBM what are your views on this extension?

**Comment by krestaino** [comment]
@Rik44444 Thanks, and yes, it's fully operational right now. Though it **only works with unencrypted backups**, so please consider that before you start using it. I really want to get encrypted backups working, but I haven't had the time to dig back into it.

**Comment by RichyHBM** [comment]
There have been many conversations regarding custom thumbnails, and we general consensus is that it wont be happening in this iteration of the app. As for syncing, I believe flocke didn't want to add unnecessary permissions etc, to the app so it would need to be a manual process.

Flocke would need to talk about the encryption as I haven't really worked with it.

As for the project in general, while I love the principal of it, it kinda defeats the purpose of 2FA, if you have your codes in a browser extension then all someone needs is access to your PC.

**Comment by krestaino** [comment]
> There have been many conversations regarding custom thumbnails, and we general consensus is that it wont be happening in this iteration of the app.

I just want to reiterate this can be automated using a free service like [this](https://favicongrabber.com/service-api-reference).

> As for syncing, I believe flocke didn't want to add unnecessary permissions etc, to the app so it would need to be a manual process.

The current use case of the app, syncing doesn't make all too much sense, so I understand why this is not a priority. In my experience using the extension I made over the past few weeks, the most annoying thing is manually syncing my phone, laptop, and desktop.

> As for the project in general, while I love the principal of it, it kinda defeats the purpose of 2FA, if you have your codes in a browser extension then all someone needs is access to your PC.

You're 100% right, so this is not for everyone. There have been many conversations around this so we don't need to dive into it here too much. But, once I get encryption working, an attacker would physical access to you computer, the password to your computer, the password to whatever service they're trying to breach, and finally the master password of the encrypted backup. Personally, I can accept this risk for convenience.

**Comment by Rik44444** [comment]
jep i agree in terms of convenience
here's another option: 
https://github.com/Authenticator-Extension/Authenticator 
syncing is pretty important for convenience i think! this app does that, so does Authy btw (but not open source)

**Comment by flocke** [comment]
On the syncing and automatic download of thumbnails: I will not add network permissions to andOTP if not absolutely necessary as this is not something a simple 2FA app needs (and that is all andOTP is trying to be). If you want to sync your backups, you can just use Syncthing, Nextcloud or something similar to automatically sync the folder the backups are saved in. As for the thumbnails, I am currently exploring some options for the rewrite of andOTP, but this will still be a while until I have a first version.

**Comment by flocke** [comment]
As for the extension itself: I sadly did not yet have any time to test it as I barely use Chrome. But I really like the idea and will try it out as soon as I have an opportunity.

**Comment by flocke** [comment]
Closing, compatible apps can be added to the wiki.
