### ISSUE TITLE
all tag sets only all visible tags

### ISSUE THREAD

**Issue by corbolais** [andOTP/andOTP#333]
#### General information

* **App version:**
latest as of today
* **App source:** Google Play / F-Droid / GitHub / ...
GP
* **Android Version:**
LineageOS 15.1
* **Custom ROM:**
LineageOS 15.1
#### Expected result
**What is expected?** 
  - selecting "all tags" to select all tags available.
  - selecting "no tag" to deselect any tag available

**What does happen instead?**
  - "all tags" selects all tags currently visible on screen, those not displayed remain unselected.
  - "not tag" deselects all tags currently visible on screen, those not displayed remain selected.

**Comment by RichyHBM** [comment]
I'm not sure this is an issue, this is how I would expect it to work.

For example when you are on an email client and you search for an email, if you clicked the select all, it would select all filtered emails

**Comment by corbolais** [comment]
Hi there!
Sure, but the point is: it is ***only*** selecting those tags actually being visible ***onscreen*** ***right now***.
I have way more tags than what would fit on the screen, those are never selected via "select all".
Please, reread my description above carefully again.
cheers!

**Comment by RichyHBM** [comment]
Ohhhh, ok yes, thats a bug then
