### ISSUE TITLE
Consider letting users add custom logos

### ISSUE THREAD

**Issue by ZenMasta** [andOTP/andOTP#335]
I see a handful of requests for adding various logos. 

But it would be nice if we could also add our own custom images. There are many companies and services that use TOTP and while I applaud that you have many great "ones out of the box". Adding our own would be nice for the ones that aren't included standard. 

Mail Chimp
Zoho
Custom world of warcraft server 😅

-----------------------------

#### General information

* **App version: 0.6.1**
* **App source: Google Play**
* **Android Version: 7.1.2**
* **Custom ROM: Resurrection Remix 5.8.5-2171002**

**Comment by flocke** [comment]
This has been asked a lot of times and it definitely is on our todo list. I will keep this issue open as a reminder and to track the progress.

**Comment by CueHD** [comment]
While I think that adding the ability for a user to add the custom logo is good, in the meantime would it be possible to synchronize the icon list with what is already in the [https://github.com/2factorauth/twofactorauth](url) repository?

**Comment by flocke** [comment]
Not without major effort as well. The way icons are currently added is one-by-one and by hand, carefully optimizing the vector graphics to work well on Android. This is not a really straight forward process and would most likely take more time then implementing the custom icons when done for the whole database you posted.

**Comment by alexanderadam** [comment]
Does it make sense to let this issue open more than once?
I would suggest just to let the older issue #225 open.

**Comment by flocke** [comment]
> Does it make sense to let this issue open more than once?
> I would suggest just to let the older issue #225 open.

Agreed, closing this
