### ISSUE TITLE
Add Proxmox icon

### ISSUE THREAD

**Issue by Fusl** [andOTP/andOTP#337]
![https://www.proxmox.com/images/proxmox/Proxmox_logo_standard_hex_400px.png](https://www.proxmox.com/images/proxmox/Proxmox_logo_standard_hex_400px.png)

**Comment by MLWALK3R** [comment]
![logo1](https://www.proxmox.com/images/proxmox/Proxmox-logo-stacked-840px.png)

![logo2](https://www.proxmox.com/images/proxmox/Proxmox_symbol_standard_hex.png)

**Comment by RichyHBM** [comment]
Hello, please provide an SVG image. Closing for now as I am adding all logos requested for 0.6.3 and need to clear up the list, please open again if you find an SVG. @flocke If you think this should be added let me know

**Comment by Fusl** [comment]
This should do: http://xor.meo.ws/7_ZZU61cI1fmO5qVcoJs0s92KRe2LNBU/pve.svg

**Comment by flocke** [comment]
Yes, that looks good.

**Comment by EmberHeartshine** [comment]
Optimized png: https://github.com/EmberHeartshine/SandBox/blob/master/Proxmox_96x96.svg
