### ISSUE TITLE
Android backup can cause data loss if relied on between 2 re-installs

### ISSUE THREAD

**Issue by RichyHBM** [andOTP/andOTP#341]
A while back I noticed whilst having to twice reinstall my phones OS that when you restore from the Android backup service, the settings arent being backedup/restored, this can mean that if you restore and then have to wipe your device again, it is possible that the default setting of using android backup is set to false and the data on google backup is wiped.

The fast solution would be to set the default value of `settings_key_enable_android_backup_service` in `app/src/main/res/xml/preferences.xml` to true, this would guarantee that when you restore a previous backup android keeps backing up your data.

There is then a further task to investigate if and/or why the preferences arent getting restored

**Comment by flocke** [comment]
I think it's a good choice to enable it by default. If you have the backup service enabled on your phone then it's reasonable to assume that you want all your apps data backed up anyways.

**Comment by RichyHBM** [comment]
What are your thoughts on removing the choice completely? Essentially allowing us to not have a custom BackupAgent and use the default one

**Comment by RichyHBM** [comment]
By not having choice, I mean having it backup always when enabled on the OS

**Comment by flocke** [comment]
That would be fine for me as well to be honest. I think that's the way most apps do it.

**Comment by RichyHBM** [comment]
Cool, will whip up a PR request over the weekend

**Comment by RichyHBM** [comment]
As mentioned in the PR, I don't this is an issue anymore

**Comment by RichyHBM** [comment]
@flocke After an inpromptu rom reinstall I just had this happen again, luckly I had a backup, but it now makes me think we should take this PR and have backup agent by default

**Comment by RichyHBM** [comment]
Hello, Anything I can do to help get #342 and #345 in?

**Comment by flocke** [comment]
@RichyHBM Not really, they both look good. I just want to wait until after the next stable release before merging new stuff. It should be release this weekend, after that I will merge the PRs.

**Comment by flocke** [comment]
I'm gonna move this to the next milestone since we merged #342 but keep it open to keep track of simplifying the ``BackupAgent``.

**Comment by flocke** [comment]
Closing this as we plan to keep the custom backup agent for now.
