### ISSUE TITLE
Add PyPI icon

### ISSUE THREAD

**Issue by karlding** [andOTP/andOTP#344]
It would be nice to have a [PyPI](https://pypi.org) icon. They support the TOTP 2FA method as of [today](https://pythoninsider.blogspot.com/2019/05/use-two-factor-auth-to-improve-your.html).

SVG icon available here: https://pypi.org/static/images/logo-small.6eef541e.svg

**Comment by EmberHeartshine** [comment]
Optimized PNG: https://github.com/EmberHeartshine/SandBox/blob/master/PyPI_96x96.svg
