### ISSUE TITLE
3 dot menu moves up

### ISSUE THREAD

**Issue by MLWALK3R** [andOTP/andOTP#346]
Check if all requirements are fulfilled otherwise the issue will be closed without any comment

  * Add details to fields  below
  * Use search. Check if the issue is already reported before creating a new one. 
    https://github.com/andOTP/andOTP/issues
  * Try again after clearing the apps data before posting (**don't forget to backup**)
  * Record a logcat: https://goo.gl/mc71vk
  * Bug reports without logcat will be closed (I can not reproduce every bug myself and I can not fix them without logs)
  * Delete this info block

-----------------------------

#### General information

* **App version:** 0.6.2
* **App source:** Google Play
* **Android Version:** 9.0
* **Custom ROM:** N/A

#### Expected result
**What is expected?**  Box does not move, so you can easliy seclect one of the menu items e.g Edit lable, edit tags, remove

**What does happen instead?** 
Once you click the 3 dots the menu will  jump up to the top

#### Logcat
```
Paste your logcat here (or use something like Pastbin for long logs)
```

#### Steps to reproduce
 
 * ...
Open app make sure screen is filled with OTP's click the 3 dots, at the very bottom one and it should jump to the top; it will jump about 3 times.
 video: https://cloud.walk3r.com/s/3bbHKYqWCaHgnMY

**Comment by flocke** [comment]
I can't reproduce this problem on my phone and I can't open your video, so I can't really debug this ...
@RichyHBM can you try and reproduce this issue?

**Comment by MLWALK3R** [comment]
updated the URL with the video

**Comment by flocke** [comment]
This is indeed very strange, but I have been unable to reproduce it on 3 different phones (and one Android Emulator) I tried this on...
Seems like I will have to do some more research on this.

**Comment by MLWALK3R** [comment]
Happened on my old S8+ if that helps; with around 46 2FA codes.

**Comment by marvinlehmann** [comment]
I just started using andOTP and also experienced this issue on my Honor 8 (Android 8.0.0).
After playing around I found a way to reproduce it. You just have to add enough entries to fill your screen and have [atleast?] one entry with a non default period (!=30s). This also "works" on the Android Emulator.

logcat:

```
2020-01-01 18:46:15.522 21036-21036/org.shadowice.flocke.andotp.dev D/skia: --- SkAndroidCodec::NewFromStream returned null
2020-01-01 18:46:15.526 21036-21036/org.shadowice.flocke.andotp.dev W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
2020-01-01 18:46:15.540 21036-21036/org.shadowice.flocke.andotp.dev D/skia: --- SkAndroidCodec::NewFromStream returned null
2020-01-01 18:46:16.533 21036-21036/org.shadowice.flocke.andotp.dev D/skia: --- SkAndroidCodec::NewFromStream returned null
2020-01-01 18:46:16.539 21036-21036/org.shadowice.flocke.andotp.dev W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
2020-01-01 18:46:16.543 21036-21036/org.shadowice.flocke.andotp.dev D/skia: --- SkAndroidCodec::NewFromStream returned null
2020-01-01 18:46:16.548 21036-21036/org.shadowice.flocke.andotp.dev W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
2020-01-01 18:46:16.566 21036-21036/org.shadowice.flocke.andotp.dev D/skia: --- SkAndroidCodec::NewFromStream returned null
2020-01-01 18:46:16.573 21036-21036/org.shadowice.flocke.andotp.dev D/skia: --- SkAndroidCodec::NewFromStream returned null
2020-01-01 18:46:17.525 21036-21036/org.shadowice.flocke.andotp.dev D/skia: --- SkAndroidCodec::NewFromStream returned null
```

**Comment by Leseratte10** [comment]
I have that issue on my phone as well. Menu jumps down one step, then jumps up one step every second until it reaches the top. I also have enough entries to fill the screen, and one non-standard entry (Twitch). Phone has MIUI 11.0.3.0 (= Android 10), AndOTP version 0.6.3.1-play. Pretty annoying and I've almost deleted entries multiple times.

**Comment by flocke** [comment]
The confirmation that it happens because of the non-standard time in the entry is a lot of help. Now I at least have a starting point for my debugging. Thanks a lot @marvinlehmann and @Leseratte10 !

**Comment by visualcurrent** [comment]
Just coming here to report that this is still an issue in version 0.7.1.1-play.
I discovered the bug under similar circumstances.

- I have a full screen of entries (6 total)
- The last entry is a test entry with a 120 second timeout, while the rest are as default (30 seconds)
- Removing the test entry that has the longer reset interval, resolves the issue. 

I'm on an older device: LG V20
Android 8

**Comment by flocke** [comment]
Yeah, I was able to reproduce this with a test entry with a longer timeout now as well.

This seems to be an artifact that happens when the screen gets redrawn because of the timeout bar advancing while the menu is open.

This could be troublesome to fix, I will look into it. Maybe as a first step I could temporarily disable the screen/timeout bar refresh while the menu is open.

**Comment by michatch** [comment]
Try to set  `holder.setIsRecyclable(false);` in `public void onBindViewHolder(@NonNull DeviceViewHolder holder, int position) `. This worked for me in another project.

**Comment by flocke** [comment]
> Try to set `holder.setIsRecyclable(false);` in `public void onBindViewHolder(@NonNull DeviceViewHolder holder, int position) `. This worked for me in another project.

That would work, but it also defeats the whole point of using a RecyclerView, since nothing will get recycled anymore.

I am currently working on a solution using Stable IDs for the RecyclerView, which also fixes the problem but keeps the recycling intact.
