### ISSUE TITLE
Add NSone logo

### ISSUE THREAD

**Issue by MLWALK3R** [andOTP/andOTP#347]
https://ns1.com/ 

![logo](https://ns1.com/img/ns1-logo.png)

**Comment by RichyHBM** [comment]
Hello, please provide an SVG image. Closing for now as I am adding all logos requested for 0.6.3 and need to clear up the list, please open again if you find an SVG. @flocke If you think this should be added let me know

**Comment by MLWALK3R** [comment]
https://github.com/edent/SuperTinyIcons/blob/master/images/svg/digidentity.svg

Would this do?
