### ISSUE TITLE
Add digidentity Logo

### ISSUE THREAD

**Issue by MLWALK3R** [andOTP/andOTP#348]
**https://www.digidentity.eu/en/home/**

![logo1](https://res-5.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco/ik33fnfv32webnel1r9f)

![logo2](https://pbs.twimg.com/profile_images/795644413443706880/H2ud36qB.jpg)

**Comment by RichyHBM** [comment]
Hello, please provide an SVG image. Closing for now as I am adding all logos requested for 0.6.3 and need to clear up the list, please open again if you find an SVG. @flocke If you think this should be added let me know

**Comment by MLWALK3R** [comment]
https://github.com/edent/SuperTinyIcons/blob/master/images/svg/digidentity.svg

Would this do?

**Comment by RichyHBM** [comment]
That should do

**Comment by EmberHeartshine** [comment]
Optimized SVG: https://github.com/EmberHeartshine/SandBox/blob/master/Digidentity_96x96.svg
