### ISSUE TITLE
Please add posteo.de icon

### ISSUE THREAD

**Issue by revuwa** [andOTP/andOTP#353]
There are some press-logos here: https://posteo.de/en/site/contact but none of them would match a typical square icon. So I requested one per email and got the original file: "PosteoDe_96x96.png".
From this I created: "PosteoDe_96x96.svg" and hope one of this could be added in andOTP.

[PosteoDe.zip](https://github.com/andOTP/andOTP/files/3248410/PosteoDe.zip)

**Comment by EmberHeartshine** [comment]
Optimized SVG: https://github.com/EmberHeartshine/SandBox/blob/master/PosteoDe_96x96.svg

**Comment by revuwa** [comment]
@EmberHeartshine Thanks for creating an usable .svg!
