### ISSUE TITLE
Please add name.com icon

### ISSUE THREAD

**Issue by revuwa** [andOTP/andOTP#354]
I couldn't find any logo source from: https://www.name.com/ so i grabbed the domain icon and made a "NameCom_96x96.svg" from it. Hope this could be added in andOTP.

[NameCom.zip](https://github.com/andOTP/andOTP/files/3248420/NameCom.zip)

**Comment by EmberHeartshine** [comment]
Optimized SVG: https://github.com/EmberHeartshine/SandBox/blob/master/NameCom_96x96.svg

**Comment by revuwa** [comment]
@EmberHeartshine Thanks for creating an usable .svg!
