### ISSUE TITLE
Please add lichess icon

### ISSUE THREAD

**Issue by superuser-does** [andOTP/andOTP#355]
[Lichess](https://lichess.org) is hosted [here on GitHub](https://github.com/ornicar/lila). Its logo is **already available in SVG** and has a minified version too.

It's worth nothing that Lichess doesn't actually display this knight as the logo on their site but it's shown on embeds, as the favicon on browsers and notably its official [mobile app](https://play.google.com/store/apps/details?id=org.lichess.mobileapp).

You can take your pick from these two for an icon:
1. The [favicon](https://github.com/ornicar/lila/blob/master/public/favicon.svg), which is identical to the [Wikimedia Commons piece](https://commons.wikimedia.org/wiki/File:Chess_nlt45.svg) that it's taken from. Not minified and looks to have been written by hand.
2. The [optimised SVG](https://github.com/ornicar/lila/blob/master/public/piece/cburnett/wN.svg) used in play on the website. It may have been modified to look better on different boards, I'm aware some piece sets have been. If there's any difference, it's indistinguishable.

If you're concerned, the icon is [licensed](https://github.com/ornicar/lila/blob/master/COPYING.md) under the GNU GPLv2+ with credit to [Colin M.L. Burnett](https://en.wikipedia.org/wiki/User:Cburnett).

Thanks in advance.

**Comment by superuser-does** [comment]
Okay, Lichess finally has a real logo! Just in time for the 10th anniversary next summer. You can find it [here](https://github.com/ornicar/lila/blob/master/public/logo/lichess.svg).

**Comment by flocke** [comment]
It's an Android specific vector format. You can create it from svg files using Android Studio. I will see if I can get this done for the next release.
