### ISSUE TITLE
Add fokus to pin/password at login

### ISSUE THREAD

**Issue by schwedenmut** [andOTP/andOTP#356]
#### General information

* **App version:** 0.6.2
* **App source:** Google Play and GitHub
* **Android Version:** API 28 (Emulator/Pixel2), API 23 (Emulator)
* **Custom ROM:** nope

#### Expected result
**What is expected?** 
When starting the app with password/pin protection, I would expect the input field to have focus directly at startup. This would improve the user experience by eliminate unnecessary typing into the input field.
**What does happen instead?**
Currently I start this application. Do a tap on the input field to gain focus and enter my pin/password. After this I either tap on the login button or the enter key to unlock the application.
#### Logcat
Sorry, no logcat since this is a improvement without crash or exception.
### Steps to reproduce
* start the application
* tap the input field

**Comment by flocke** [comment]
That is actually the way it used to be. I somehow managed to break it in the last update and haven't found the time yet to fix it. Thanks a lot for the PR 👍

**Comment by GambaJo** [comment]
This would be great!
