### ISSUE TITLE
Issue with arabic numbers display

### ISSUE THREAD

**Issue by BoFFire** [andOTP/andOTP#359]
Hi,
When andOTP is set by a user to arabic language, the app displays "٣٧١٣٣٣" numbers, same when it is copied into the clipboard. This field should display arabic normal numbers "1234567890".
Regards,

**Comment by flocke** [comment]
@BoFFire Sorry it took so long, I didn't have a lot of free time the last few months.
Could you test [this debug build](https://cloud.shadowice.org/s/andOTP_ArabicNumbers) and see if it works for you? It will install as a new app named "andOTP (dev)", so it won't interfere with your default install.

**Comment by BoFFire** [comment]
Hi @flocke
Solved with this build :) The numbers are now ok even on clipboard copy.

**Comment by flocke** [comment]
Alright, thank you for testing. It will be included in the next release.

**Comment by BoFFire** [comment]
Thank you.
