### ISSUE TITLE
Sizing Icons Proportionally To Each Other

### ISSUE THREAD

**Issue by SpiritWolfe** [andOTP/andOTP#365]
This is NOT a software issue. This is an issue with the Icons you offer up for users to use in each of the two-step verification processes the user enters within andOTP. 

There has to be a way we can alter each individual icon so that they do not look out of proportions with each other. For example, you only offer three ways to enlarge the icons. The "LastPass" icon is so small that the only way to see it legible and read it is to set the zoom to the   3X setting making some of the icons look out of proportion to the other. Can this be fixed, please?

**Comment by ziegenberg** [comment]
Well, the problem with LastPass seems to be that their logo is not quite square but rather longish. It's the only logo they offer, so I don't know if there's a real solution possible here.

**Comment by flocke** [comment]
Closing, since this is a problem with (some of) the icons that are provided by the respective services as @ziegenberg mentioned.
