### ISSUE TITLE
[Support] Can't decrypt backup

### ISSUE THREAD

**Issue by mar1ged** [andOTP/andOTP#367]
Before I flashed my device I created an export and kept it in a safe place.
Now I want to restore from that backup but fail:
I select `otp_accounts.json.aes` and get 
`Entschlüsselung des Backups ist fehlgeschlagen`.
What can I do to solve this ? I chose `Wiederherstellen (verschlüsselt)` 

Now I am on Resurrection Remix 7 (Android 9) and use 0.6.2 installed from the Play Store.

**Comment by flocke** [comment]
Did you set the same backup password on both devices (andOTP -> Settings -> Backup password)?
If so, could you provide a logcat of you trying to restore the backup?

**Comment by mar1ged** [comment]
Yes, I am sure because I chose the same password that protected AndOtps start and which I used for months.
I am still struggling to get a logcat (didn't root the phone by intention) and will upload it as soon as I have it

**Comment by flocke** [comment]
That's really strange. Do you have access to a PC with Linux? If so you could try this script for manually decrypting the backup: https://github.com/asmw/andOTP-decrypt

You can also try deleting the password in the settings of andOTP. In that case it will ask when you try to restore the backup, maybe that helps.

**Comment by mar1ged** [comment]
I was unable to remove the password from the settings.

I will try the script and let you know

**Comment by flocke** [comment]
If you are unable to remove the password you could reset the app completely (Android Setting -> Apps -> andOTP -> Storage -> Clear Storage) and then set it up again without setting the password. That way, when you try to import the backup file, you should get asked for the password manually.

**Comment by mar1ged** [comment]
Thanks, that way I was able to remove the password. Now I can enter it manually and tried the password and (just to be safe) some variations of it (in case I might have had the same typo when I created the backup).
All attempts show me the same error message.

I have put the script on my Ubuntu 19.04 box but no matter what I try I can not get past this message:
```
Traceback (most recent call last):
  File "/home/mg/decrypt.py", line 13, in <module>
    from aes_gcm.aes_gcm import AES_GCM, InvalidTagException
ModuleNotFoundError: No module named 'aes_gcm'
```

I made some attempts by googling and messing around with pycrypto but couldn't fix it

**Comment by mar1ged** [comment]
I guess this was an issue with my backup file. I compared it with another backup I had exported to an USB C stick directly. Restoring that one succeeded.

Thank you for your support

**Comment by flocke** [comment]
That could explain it. Did the size for the two different backups differ by a lot?

**Comment by mar1ged** [comment]
Yes, ~ 1200 vs ~ 1800. But I guess I messed it up because of the way I transferred and handled the file. So no issue with your code.

**Comment by flocke** [comment]
> Yes, ~ 1200 vs ~ 1800. But I guess I messed it up because of the way I transferred and handled the file. So no issue with your code.

Yes, sounds that way. The difference is to small for it to be a failed export (they are usually just 2-3 bytes).
