### ISSUE TITLE
Add Crowdin icon

### ISSUE THREAD

**Issue by lucavallerini** [andOTP/andOTP#369]
Hello!

Please add Crowdin icon, see here for EPS versions of their logo: [https://support.crowdin.com/using-logo/](https://support.crowdin.com/using-logo/)

I imported the EPS versions into Inkscape and saved as SVG, you can find them in attachments (it is a ZIP file because GitHub does not let me upload SVG files).

Thank you.

[crowding-logo-svg.zip](https://github.com/andOTP/andOTP/files/3414390/crowding-logo-svg.zip)

**Comment by flocke** [comment]
Thank you for the SVG version!
