### ISSUE TITLE
Consider using an upstream icon package

### ISSUE THREAD

**Issue by xM8WVqaG** [andOTP/andOTP#370]
_Idea reposted from Telegram. Please feel free to edit this issue's title/description._

Preparing and optimising icons doesn't really have much to do with TOTP. If possible, it might be a good idea to investigate outsourcing the icon maintenance to a third party.

There are several interesting icon projects around, one nice example is SuperTinyIcons: <https://github.com/edent/SuperTinyIcons>

This solves two problems:

* You can just close tickets about icons and redirect people upstream. Resolves maintenance issues like existing icon consistency: https://github.com/andOTP/andOTP/issues/365
* If the icon package is kept updated and new versions are pulled into andOTP regularly for releases then people will continue to get new icons available in the core without having to use custom icons.

**Comment by flocke** [comment]
I really like the idea of outsourcing the maintenance of the icons. And since SuperTinyIcons actually provides a lot of Android vector drawables it should be fairly straight forward to merge them. Maybe I could write a small script that takes care of that.
I will definitely look into it, but don't expect anything to soon, I don't have any free time currently.

**Comment by vangyyy** [comment]
Is this being worked on ? I would like to take a look at this.

**Comment by alexanderadam** [comment]
@vangyyy I'm not a maintainer but I have the feeling that @flocke would be _very happy_ if you would provide a PR for this.

**Comment by flocke** [comment]
@vangyyy Sorry it took me so long to respond. Just as @alexanderadam said, I would be happy if you could look into it. I don't have a lot of time currently.

**Comment by edent** [comment]
If there are any other icons you would like, please let us know in https://github.com/edent/SuperTinyIcons/issues

**Comment by RichyHBM** [comment]
@vangyyy Did you get anywhere with this? Might try and get this done today

**Comment by vangyyy** [comment]
I am working on it. Though it isn't as straight forward as importing the icons from SuperTinyIcons repository. Couple icons do not work under Android as they are in [android-vector-drawable folder](https://github.com/edent/SuperTinyIcons/tree/master/images/android-vector-drawable). I guess whoever converted them never tested them. I will probably submit some PRs to their repository to get it working as well as to improve coverage (a lot of current andOTP icons are simply not available). As far as implementation goes I was thinking of adding the repository as git submodule, which could be updated between releases. What do you think ?

**Comment by RichyHBM** [comment]
Yes, I started working on something for this this morning, I have added STI as a submodule and am adding the icons via a gradle task. I imagine most of the work for this will be done in gradle as to automate as much as possible

**Comment by edent** [comment]
@vangyyy I'm the maintainer of SuperTinyIcons. Pull requests very welcome. The android-vectors were automatically converted, not sure why they don't work - but guidance welcome!

**Comment by RichyHBM** [comment]
Hey @edent I opened an issue on SuperTinyIcons about the broken vector images, I also noticed a could of them may be the wrong size? Hopefuly that will be fixed with SuperTinyIcons#189

Anyway, I have got it all working with andOTP in an automated way, we would just need to decide wether to exclusively use STI or how we would do it @flocke. For now I have removed our versions that were also in STI

**Comment by vangyyy** [comment]
I have submitted a PR in STI that fixes the issue and also adds existing icons that were missing in android-vector-drawable folder. As for the missing icons from andOTP, I would suggest leaving them for now, but maybe create an issue in STI where we could list them and work on them.

**Comment by flocke** [comment]
Thank you @vangyyy and @RichyHBM for working on this. The PR looks really good, but I haven't had time to test it yet. And also thanks a lot @edent for SuperTinyIcons, I didn't know of it before this PR but it looks really cool.

**Comment by vangyyy** [comment]
Upstream PR that fixes android drawables was merged. All of them should work now. There is one problem though. STI doesn't require from contributors generating android drawables, they are optional. So in the future newly added icons may become broken or worse ... may not be generated at all.

**Comment by alexanderadam** [comment]
> STI doesn't require from contributors generating android drawables

Maybe @edent could consider enforcing Android Vector Drawables for new icons the in the Guidelines & PRs.

What do you think @edent?
This way the availability of the icons would be consistent.

**Comment by vangyyy** [comment]
The problem with this is that it will become a burden for contributors and may result in less icons being made for STI. The conversion itself can not be easily automated with a script. I found a [tool](https://svg2vector.com/) that produces correct image 99% of the time. It is payed though. It can only be used once (more if you open new incognito session every time ... cookies). Another solution is to convert them manually before release, but that defeats the whole point of using it in a first place.

**Comment by alexanderadam** [comment]
> The conversion itself can not be easily automated with a script

Why not?
Shouldn't it be possible with the command line interface of Android Studio?
I just searched and found [this blog entry](https://www.androiddesignpatterns.com/2018/11/android-studio-svg-to-vector-cli.html) that says that it should be possible with

```bash
$ ./vd-tool -c -in svgs/ -out vectors/
```

So couldn't this step added to [the travis configuration](https://github.com/andOTP/andOTP/blob/master/.travis.yml#L23) where the build seem to happen anyway?

**Comment by RichyHBM** [comment]
I don't really see an issue, if an icon is missing a drawable it can just be done as an issue/pr, same as if the icon didn't exist

**Comment by NeverDucky** [comment]
There is also the option of collaborating with https://github.com/2factorauth/twofactorauth for this. The project already maintains a list of icons specifically tailored to two-factor-authentication-providing services. Both projects are related and would do well to share resources.

**Comment by alexanderadam** [comment]
> The project already maintains a list of icons specifically tailored to two-factor-authentication-providing services.

Are they also offering vector icons? So far I just found low resolution raster images (i.e. [those](https://github.com/2factorauth/twofactorauth/tree/master/img/email)) which obviously will look ugly on high resolution displays.

**Comment by NeverDucky** [comment]
As far as I can tell, no. That would be the downside of using those icons.

**Comment by flocke** [comment]
Closing this issue, as we have a PR and all discussion should happen there: #398
