### ISSUE TITLE
Time Correction

### ISSUE THREAD

**Issue by thejeshgn** [andOTP/andOTP#375]
#### General information

* **App version:** 0.6.2
* **App source:** Google Play 
* **Android Version:**
* **Custom ROM:** No

#### Expected result
**What is expected?** 
Couldn't generate a valid code for gitlab

**What does happen instead?**
I couldn't login to gitlab after trying multiple times today. Then I checked another phone with Authenticator. It showed the same code as AndOTP.

 But in Authenticator i tried "Time correction for codes" in settings. Then the codes on AndOTP and Authenticator differed. Then I could use Authenticator OTP to login. 

Can we have similar functionality to sync time?

**Comment by flocke** [comment]
That's definitely on my todo list. I just don't have the time currently to implement it.
But as soon as I got some free time I'm gonna look into it.

**Comment by antifarben** [comment]
Duplicate of #285

**Comment by flocke** [comment]
Closing this because of the duplicate, thanks @antifarben.
