### ISSUE TITLE
scan QRCode in the gallery?

### ISSUE THREAD

**Issue by xiazeyu** [andOTP/andOTP#377]
#### General information

* **App version:** 0.6.2
* **App source:** Google Play
* **Android Version:** 9
* **Custom ROM:** MIUI

#### Expected result
**What is expected?** 
Import and recognize QRCode image in the gallery or download folder.
(When set up OTP on the mobile browser, it is common that a QRCode will be provided. However, I cannot find anything buttons to direct to the downloaded image. The only thing I can do is to find another phone, take a shot, and use andOTP to scan that QRCode shot.)

**What does happen instead?**
Provide a button that enables select QRCode from the gallery.

**Comment by flocke** [comment]
This was implemented in #425
