### ISSUE TITLE
AuthenticationActivity is missing secure flag and can be screencaptured

### ISSUE THREAD

**Issue by schwedenmut** [andOTP/andOTP#378]
#### General information

* **App version:** 0.6.2
* **App source:** Google Play / GitHub
* **Android Version:** 10
* **Custom ROM:** vanilla Android

#### Expected result
**What is expected?** 
While taking a debug video for another issue and improvement, I noticed that the video is blacked out on the MainActivity but not while unlocking andOTP and taking the picture of the QR Code.
With the information captured Evil could extract the Password/Pin for unlocking the app and/or gain access to a new added secret by using the QR Code which can be captured.
**What does happen instead?**
I would expect that AuthenticateActivity and the Screenshot intent would be flagged as secure like MainActivity is.
#### Logcat
No Log for this, but a video with dummy data.
![device-2019-09-11-125902](https://user-images.githubusercontent.com/9077622/64697342-f1e9d480-d4a0-11e9-99ba-ba90dda9b5d2.gif)

#### Steps to reproduce
 
 * Take screenshot or video from login screen -> working
 * Take screenshot or video from MainActivity -> not working
 * Take screenshot or video from QR Code scan -> working

**Comment by schwedenmut** [comment]
Wen't ahead to fix it for the login screen.

**Comment by schwedenmut** [comment]
Also fixed the QR Code capture to have the secure flag by extending CaptureActivity of the framework

**Comment by flocke** [comment]
I added the necessary flags to the AuthenticationActivity in 8ba9984567a788921f63e76f7761b18fd3151a5d.

But the QR code scanner is going to be harder, since I use an external library for that and don't actually have control of the window flags. I will have to implement my own scanning activity and set the flags there. So this will take some more time, I will leave the issue open as a reminder.

**Comment by schwedenmut** [comment]
I will push the camera extension in approximately 20 minutes - If you can wait.  
I worked in this last weekend.

**Comment by flocke** [comment]
Nice, then I will wait for your PR.

**Comment by schwedenmut** [comment]
PR is online.
