### ISSUE TITLE
Question about andOTP and Google

### ISSUE THREAD

**Issue by danjde** [andOTP/andOTP#382]
Hi Devs!
I would only to know if is it possible to use andOTP without any infrastructure Google, or if andOTP is properly a Google Authentication client.

Thanks!

Davide

**Comment by flocke** [comment]
Hello Davide,

andOTP is completely independent of Google. It just implements the same algorithms as Google Authenticatior, namely [HOTP](https://en.m.wikipedia.org/wiki/HMAC-based_One-time_Password_algorithm) and [TOTP](https://en.m.wikipedia.org/wiki/Time-based_One-time_Password_algorithm). You can use it as a replacement for Google Authenticatior on almost all sites that support those algorithms.

Cheers,
Jakob

**Comment by danjde** [comment]
Hi Jakob and thanks for your reply!
Excuse me but I'm newbie to 2FA, and I don't understand well how work andOTP.
andOTP is a client side application if I understand, but what is the andOTP server side?
Could you show me a short documentation or something like that around the andOTP working?

Many thanks!

Davide

**Comment by schwedenmut** [comment]
Probably (except for the RFCs) https://www.freecodecamp.org/news/how-time-based-one-time-passwords-work-and-why-you-should-use-them-in-your-app-fdd2b9ed43c3/ has some nice explanation around 2FA HOTP and TOTP with pseudo-code.

**Comment by RichyHBM** [comment]
andOTP is a client only application, there is no server side application

**Comment by flocke** [comment]
Like Richy said, there is no server side. Most sites/servers have their own implementation. But it is a standard protocol, so one app works for most implementations.

**Comment by danjde** [comment]
Well! 
I will do some test for Joomla and Wordpress login.

Thanks again to all!!

Davide

**Comment by danjde** [comment]
Ok, I've done some tests and then apply the 2FA to some of my websites (wordpress/wordfence and Jooma/native) and all works fine!
Just a note:  I didn't see from the vary choice of images Joomla!

Thanks!

Davide

**Comment by flocke** [comment]
Nice to hear everything works 👍

Could you maybe open another issue for the Joomla icon? That way we can better keep track.

**Comment by danjde** [comment]
> Nice to hear everything works +1

I will test on owncloud too and meny others ;-)

**Comment by flocke** [comment]
I use it on my Nextcloud as well. There is a TOTP app that you can install.

**Comment by danjde** [comment]
> I use it on my Nextcloud as well. There is a TOTP app that you can install.

Well, confirm, on Nextcloud 13/14 all works fine using andOTP, 2FA admin too ;-)

Thanks!

**Comment by schwedenmut** [comment]
Well it should work because andOTP follows the RFC for both methods. So every system side implementation following the RFC and beeing standard conform will work 👍.

**Comment by danjde** [comment]
Well, I've used for Nextcloud side ["Two-Factor TOTP Provider"](https://github.com/nextcloud/twofactor_totp#readme)

Thanks again!
Davide
