### ISSUE TITLE
Add automatic icon mapping if issuer is provided

### ISSUE THREAD

**Issue by schwedenmut** [andOTP/andOTP#388]
# Proposal
Most QR codes already include the issuer of the secret. Why don't we use this for automatic icon mapping. By doing so, after scanning the code, there will be no need to manually select the correct icon if provided.

@flocke if you like that approach, I could go ahead and create a PR. Probably with #372 in mind?

**Comment by flocke** [comment]
That's a great idea, I thought about it before but never had time to implement it. It would be nice if you could provide a PR.

**Comment by schwedenmut** [comment]
Perfect, will take a further look into this. Makes it a little bit more comfortable having this.  
  
Do you preferr a PR based on the current master branch or with the changes based on #372?

**Comment by flocke** [comment]
I think you can base it on #372, I will merge it after the next stable release (which I want to put out over the next weekend).
