### ISSUE TITLE
Feature request - Dark theme should be (initially) selected based on OS

### ISSUE THREAD

**Issue by jamescridland** [andOTP/andOTP#394]
I'm using Android 10, which has a global setting for a dark theme. Expected behaviour for this is that if I've selected dark mode in the OS, it should filter down to individual apps, too.

I was unaware that andOTP had a dark theme, but pleased to have discovered it. You may wish to check the below article for a few ideas on how to implement this feature in an Android 10 compatible way.

“Implementing Dark Theme in your Android app” by Frank https://medium.com/q42-engineering/android-dark-theme-b4d695f78c4f

**Comment by flocke** [comment]
This is definitely on my Todo, but not very high up as I don't have a lot of time in the moment and have more critical issues to fix.

**Comment by flocke** [comment]
Implemented in #418
