### ISSUE TITLE
[feature request] option to use fingerprint as default

### ISSUE THREAD

**Issue by xiazeyu** [andOTP/andOTP#395]
I prefer to use fingerprint to unlock the keyStore as it is quicker and more convenient. But every time it will pop up a keyboard and ask me to enter the password first. Is it possible to add an option to use fingerprint as default when use Android KeyStore?

**Comment by flocke** [comment]
The unlock screen that gets displayed when you use "Device credentials" is not part of andOTP, it's part of the Android system. So I can not influence the behaviour, sorry.

**Comment by xiazeyu** [comment]
Got it, thanks anyway.
But is it possible to use the "Fingerprint API"(provided by Android) to add fingerprint support for(Password / PIN Storage)?

**Comment by flocke** [comment]
Yes, that's on the todo list. It is a bit more complex to implement and I currently just don't have time to work on it. But it will be added at some point.
