### ISSUE TITLE
Bitmex favricon

### ISSUE THREAD

**Issue by dducted** [andOTP/andOTP#401]
Hi there, 

Could you maybe add a bitmex.com favricon? Pretty widley used crypto leverage exchange.

Thank you

**Comment by ziegenberg** [comment]
Would you either go with their [favicon](https://static.bitmex.com/assets/img/fav/favicon.ico?v=1) or their [logo with name](https://static.bitmex.com/assets/img/bitmex-logo-v2-alt-white.png)?

**Comment by flocke** [comment]
I think favicon. Those long logos with text always look bad as small thumbnails.
