### ISSUE TITLE
Add Docker icon

### ISSUE THREAD

**Issue by frauhottelmann** [andOTP/andOTP#407]
Docker Hub introduced 2FA. Could you add the docker logo?

https://www.docker.com/company/newsroom/media-resources

The ["docker logo blue"](https://www.docker.com/sites/default/files/d8/2019-07/vertical-logo-monochromatic.png) is already square.

Thanks.

**Comment by RichyHBM** [comment]
Docker would come in with #398, I'd rather just use that once ready than add docker now and have to replace it when its merged

**Comment by frauhottelmann** [comment]
Then we can close this issue :smile:
