### ISSUE TITLE
Add Bugcrowd Icon

### ISSUE THREAD

**Issue by aph3rson** [andOTP/andOTP#411]
#### General information

* **App version:** 0.6.3.1-play
* **App source:** Google Play
* **Android Version:** 9
* **Custom ROM:** Samsung OneUI 1.0

#### Request

Add an icon for Bugcrowd, as their accounts [support 2FA](https://docs.bugcrowd.com/docs/two-factor-authentication-1).

**Comment by ziegenberg** [comment]
Would you either go with their [favicon](https://www.bugcrowd.com/favicon.ico) or their oblong [logo with claim](https://www.bugcrowd.com/wp-content/uploads/2019/04/bugcrowd-logo.svg)?

**Comment by aph3rson** [comment]
Favicon would be best for symmetry, imo.
