### ISSUE TITLE
Update Firefox thumbnail

### ISSUE THREAD

**Issue by Otiel** [andOTP/andOTP#414]
Firefox newest icon: https://en.wikipedia.org/wiki/File:Firefox_logo,_2019.svg

![image](https://user-images.githubusercontent.com/3851902/67695738-dfbaeb80-f9a5-11e9-9679-b44e19ec4809.png)

**Comment by RichyHBM** [comment]
I think the latest is this one 

![https://mozilla.design/files/2019/10/logo-firefox.svg](https://mozilla.design/files/2019/10/logo-firefox.svg)

https://mozilla.design/files/2019/06/Firefox-Parent-Brand.zip

**Comment by flocke** [comment]
The problem with that is that it looks like it has gradients in it. That could become problematic.

**Comment by Otiel** [comment]
Well it's not the icon for the Firefox browser, but the icon for the Firefox brand:

![image](https://user-images.githubusercontent.com/3851902/67748276-d32ca680-fa2a-11e9-891d-e364f21dfe33.png)
(see [official blog post](https://blog.mozilla.org/opendesign/firefox-the-evolution-of-a-brand))

Not sure which one should be included in andOTP though.

**Comment by RichyHBM** [comment]
I would say it's the parent we want as it's for an account that can be used in any of the products, not just firefox

**Comment by ziegenberg** [comment]
@flocke: Was included with 0.7.0 and can be closed.

**Comment by john3voltas** [comment]
> @flocke: Was included with 0.7.0 and can be closed.

Hmmm, I see it's been closed but I currently have 0.7.0 installed and I can't find any Firefox or Mozilla icon in andOTP.
I'm using F-Droid's build.
Can anyone else confirm it made it into 0.7.0?
Anyone else with 0.7.0 from F-Droid can see if they have FF's icon in their andOTP?
Thanks in advance.
Cheers
