### ISSUE TITLE
Add Gandi.net thumbnail

### ISSUE THREAD

**Issue by Otiel** [andOTP/andOTP#415]
https://en.wikipedia.org/wiki/File:GandiSAS.svg

![image](https://user-images.githubusercontent.com/3851902/67695953-43451900-f9a6-11e9-98cd-3c52f8bd3bc4.png)

**Comment by RichyHBM** [comment]
This icon is already in andOTP

**Comment by Otiel** [comment]
My bad, probably missed it because it was added recently in the last update.
