### ISSUE TITLE
Add DiskStation Manager (Synology) thumbnail

### ISSUE THREAD

**Issue by Otiel** [andOTP/andOTP#416]
Found this icon that matches the favicon of DSM 6, I'm not sure about the rights though.

![image](https://user-images.githubusercontent.com/3851902/67696212-c4041500-f9a6-11e9-9937-89e2950d0eab.png)

**Comment by RichyHBM** [comment]
We already have a Synology Icon, is this one needed?

**Comment by Otiel** [comment]
I missed the Synology icon because it was probably added in the last update.

It's good enough for me, thanks!
