### ISSUE TITLE
change 簡體中文 to 简体中文

### ISSUE THREAD

**Issue by zhangzp9970** [andOTP/andOTP#424]
#### General information

* **App version:**0.6.3.1
* **App source:**  GitHub 
* **Android Version:**9
* **Custom ROM:** miui

#### Expected result
**What is expected?** 
see my pull request  #423 
**What does happen instead?**

#### Logcat
```
Paste your logcat here (or use something like Pastbin for long logs)
```

#### Steps to reproduce
 
 * ...

**Comment by flocke** [comment]
Closing because PR got merged
