### ISSUE TITLE
encryption details since 0.6.3

### ISSUE THREAD

**Issue by paolostivanin** [andOTP/andOTP#427]
Hello,
I'm updating my app to support the newer encryption format, but I'm a bit lost.
Here[1] you wrote that the key is 256bit, but you are using `PBKDF2WithHmacSHA1` ([EncryptionHelper.java](https://github.com/andOTP/andOTP/blob/d96b0373d9db6af6363aec59bf3a32928f0c504d/app/src/main/java/org/shadowice/flocke/andotp/Utilities/EncryptionHelper.java#L74)) which returns 160bit.
I have therefore two questions:
1) how do you get the remaining bits?

2) do you use the same key for both crypto and hmac?

Thanks :smile: 

[1] https://github.com/andOTP/andOTP/wiki/Backup-encryption

**Comment by paolostivanin** [comment]
Please see also: https://crypto.stackexchange.com/questions/9568/achieving-256-bit-encryption-strength-with-pbkdf2-hmac-sha1

**Comment by paolostivanin** [comment]
See also https://security.stackexchange.com/questions/110084/parameters-for-pbkdf2-for-password-hashing :-)

May I ask why you didn't choose sha256? 

Thanks!

**Comment by flocke** [comment]
The reason for using sha1 for the backup encryption was that is already was used for the database encryption, which I did a long time ago when I didn't have a lot of experience in crypto stuff. I can't really tell you why I chose it back then, it probably had something todo with a tutorial I was following. Now I would probably go with something completely different (like scrypt or Argon2).

Those bad decisions I made in the beginning when I was inexpereinced are basically the reason why I am rewriting the app from scratch with a completely new crypto system. I feel it doesn't make a lot sense to change the encryption here because andOTP will be abandoned once the rewrite is finished.

**Comment by paolostivanin** [comment]
Oh, that's nice :) will the new app always be FOSS?

**Comment by flocke** [comment]
It will definitely be FOSS as well. And it will support importing andOTP backup files.
Sadly I don't have a lot of time to work on it in the moment, but that should change in the next year.

**Comment by paolostivanin** [comment]
one last thing: I updated my app to support the new enc method. So far the import part is good and works like a charm, but I am struggling with the export (andotp fails to import the enc backup).
The export is in this format:
`iter` a 4 bytes int32 type stored as **big endian** in the file
`salt` of 12 bytes
`iv` of 12 bytes
`data`
`tag` of 16 bytes
Am I doing something wrong here? :thinking:

**Comment by flocke** [comment]
From what you wrote I can't see anything wrong with your format. If I find the time I will look into your code and see if I can find something.

**Comment by paolostivanin** [comment]
Thanks :) this is the link: https://github.com/paolostivanin/OTPClient/blob/2fe1079bc7719d12ba0b0e5fd085a65f184c7ecc/src/andotp.c#L170

in the meanwhile, I'll dig deeper!

**Comment by paolostivanin** [comment]
andotp_exports.json.aes (file attached) details given by otpclient before writing the file:

```
big endian iterations as int32: 1894
------
IV: 94acf221ca35c046e64d9907
------
Salt: e59f031456ae0e938a8d5680
------
Tag: 4cf7cde578e747989105523d42a4988d
------
```

As we can see, int32 `1894` is stored as `66 07` (big endian). Then we have the salt, the iv, the data and the tag. All match the above output.

```
$ hexdump -C ~/andotp_exports.json.aes 
00000000  66 07 00 00 e5 9f 03 14  56 ae 0e 93 8a 8d 56 80  |f.......V.....V.|
00000010  94 ac f2 21 ca 35 c0 46  e6 4d 99 07
...
000001c0  4c f7 cd e5 78 e7 47 98  91 05 52 3d 42 a4 98 8d  |L...x.G...R=B...|
```

Attached you can find the encrypted file. The password is `asdasd`. When I try to decrypt it using andotp I get `Decryption failed`.

[andotp_exports.json.zip](https://github.com/andOTP/andOTP/files/3874269/andotp_exports.json.zip)

Hope this helps!

**Comment by flocke** [comment]
Yeah, I can see what you mean. I have the final exam for my PhD next week, after that I will look into it myself. You can also try this web tool I developed to decrypt the backups: https://flocke.shadowice.org/andOTP/decrypt/
That way you don't have to copy it to your phone all the time. It works purely in JavaScript, so everything stays on your PC, nothing is uploaded.

**Comment by paolostivanin** [comment]
That's a very important step man, congrats :D

**Comment by paolostivanin** [comment]
problem solved :D thanks to your tool I was able to debug what I did wrong (I was using the big endian for key derivation when I should have been using the little endian instead)

https://github.com/paolostivanin/OTPClient/commit/13a6fa5f6d93d85297e285d3f98f976a9834c84d

now all works :+1:

**Comment by flocke** [comment]
I'm glad you were able to figure it out, nice work. I always have a backup of my 2FA accounts on my Linux system in your app :+1:
