### ISSUE TITLE
Add airbnb thumbnail

### ISSUE THREAD

**Issue by guoxiao** [andOTP/andOTP#429]
#### General information

* **App version:** 0.6.3.1-play
* **App source:** Google Play
* **Android Version:** 10.0
* **Custom ROM:** AOSP

Can we add airbnb thumbnail as they support 2FA for internal users.

https://upload.wikimedia.org/wikipedia/commons/6/69/Airbnb_Logo_B%C3%A9lo.svg

**Comment by ziegenberg** [comment]
@flocke: Was included with 0.7.0 and can be closed.

**Comment by guoxiao** [comment]
@flocke @ziegenberg @RichyHBM Thanks for your great work! 
But I looked into to app and found that the logo with text seems not fit into the thumbnail very well. Can we use the logo without text in our app?

**Comment by guoxiao** [comment]
Or we can use the logo with text below icon which is also used in Duo app: https://worldvectorlogo.com/logo/airbnb-2 
(I'm not sure the file can be used in our app, just as an example. The website says "You may only use this website and its content for personal, non-commercial purposes")

**Comment by flocke** [comment]
[SuperTinyIcons](https://github.com/edent/SuperTinyIcons] has a nice version of the airbnb logo: https://github.com/edent/SuperTinyIcons/blob/master/images/svg/airbnb.svg

Since we plan to use SuperTinyIcons as thumbnail provider in the future that should solve it.

**Comment by flocke** [comment]
[SuperTinyIcons](https://github.com/edent/SuperTinyIcons) has a nice version of the airbnb logo: https://github.com/edent/SuperTinyIcons/blob/master/images/svg/airbnb.svg

Since we plan to use SuperTinyIcons as thumbnail provider in the future that should solve it.
