### ISSUE TITLE
Add Fastmail icon

### ISSUE THREAD

**Issue by x80486** [andOTP/andOTP#435]
Since `Fastmail` also have 2FA, it would be great to have its icon available in `andOTP` :tada:

Here is the [link](https://www.fastmail.com/images/press/logos/FM-Icon-RGB.png) for the logo.

Thanks in advance!

**Comment by flocke** [comment]
Link to EPS: https://www.fastmail.com/images/press/logos/cmyk/FM-Icon-CMYK.eps
