### ISSUE TITLE
After OS loss, can't enable keystore

### ISSUE THREAD

**Issue by serussell** [andOTP/andOTP#437]
#### General information

* **App version:** 0.6.3.1
* **App source:** F-Droid
* **Android Version:** 10 (Pixel 2)
* **Custom ROM:** No

#### Expected result
**What is expected?** 

Should be able to setdatabase encryption to "Android KeyStore."

**What does happen instead?**

```
Encryption key not loaded
```

message, followed by

``
Failed to change database encryption,
falling back to original state!
```

message.

#### Logcat

I'm not set up to capture logs with ADB.

#### Steps to reproduce
 
Android crashed and I had to perform a hard reset, so I lost the DB on the device.  I do sync exports to desktop when adding new keys, so I had a JSON export to reload. However, for a reason I can't recall (but I *believe* was a similar message), I was unable to load the JSON into the keystore when I recreated the DB, so I used a pin.

Now I'm unable to change the DB type, which, of course is preventing me from using fingerprint login. I'm not having this issue with any other app that uses the fingerprint auth mechanism, e.g. Keepass2Android; however, none of those come from F-Droid.

**Comment by flocke** [comment]
What kind of reset did you perform? Did you do a factory reset from within Android or did you clean flash the factory images from Google? And are your rooted?
Can you try going to your phones settings and do "Apps -> andOTP -> Storage & cache -> Clear storage" and set up the app from scratch. That SHOULD clear the KeyStore.

**Comment by serussell** [comment]
It was a factory reset, and I am not rooted.

That did it, thanks! I think the difference this time was that I backed up to (and restored from) plain and not encrypted, JSON.  IIRC, the problem was that I wasn't able to restore from encrypted JSON into Keystore.  But I am not certain.

Thanks!

**Comment by flocke** [comment]
Glad the clearing of the storage fixed it for you. It shouldn't depend what kind of backup you restore.
I suspect that the factory reset did not properly clean out the old KeyStore entried for some reason and manually resetting the apps storage did.

**Comment by VNRARA** [comment]
This bug is still a thing actually. What you suggested [here ](https://github.com/andOTP/andOTP/issues/437#issuecomment-562091920) is a mere workaround (granted if you restore from a JSON file). I think that could be setup as a automatic workaround in case the normale method doesn't seem to work. I think that this bug starts when the app is restored from a cloud backup (like Samsung for example does) and tries to restore everything with it.
