### ISSUE TITLE
Improve sorting by most recent 

### ISSUE THREAD

**Issue by ThiefMaster** [andOTP/andOTP#443]
Currently sorting by most recent moves an entry to the top once you view it.

It would be (much) more useful if each entry stored a counter (incremented every time you view its code) and the list entries were then sorted by that counter.

**Comment by RichyHBM** [comment]
That would be more like sitting by most common, not recent

**Comment by ThiefMaster** [comment]
You're right, probably better to call it "most common"

**Comment by flocke** [comment]
Currently "most recent" works by just storing the timestamp an entry was used last (copied or revealed if tap-to-reveal is enabled) and sorting by this. It should be fairly easy to add a counter that is increased every time the timestamp is updated and an option to sort by that as well.

**Comment by flocke** [comment]
This was just implemented in #467
