### ISSUE TITLE
Add passwordstate icon

### ISSUE THREAD

**Issue by Fohroer** [andOTP/andOTP#446]
Please add passwordstate icon.

**Comment by ziegenberg** [comment]
@Fohroer can you provide an icon, preferably in a vector format.

**Comment by Fohroer** [comment]
> @Fohroer can you provide an icon, preferably in a vector format?
Attached!
[Passwordstate.zip](https://github.com/andOTP/andOTP/files/4620027/Passwordstate.zip)
