### ISSUE TITLE
FR: Handle otpauth:// URIs

### ISSUE THREAD

**Issue by sm4rk0** [andOTP/andOTP#447]
#### General information

* **App version:** 0.6.3.1
* **App source:** F-Droid
* **Android Version:** 10
* **Custom ROM:** stock Samsung

#### Expected result
**What is expected?** 
andOTP is opened upon tapping the otpauth:// URI (bonus points: possibility to share the URI to andOTP)
**What does happen instead?**
nothing

#### Logcat
N/A

#### Steps to reproduce
 
* tap this link on a phone with andOTP installed: [otpauth://totp/Yubico%20Demo:demo?secret=MJNZFXOHY7C52NXM&issuer=Yubico%20Demo](otpauth://totp/Yubico%20Demo:demo?secret=MJNZFXOHY7C52NXM&issuer=Yubico%20Demo)

Edit: GitHub won't make this a clickable URI, so here are alternative steps to reproduce:
* go to https://demo.yubico.com/
* create demo account and login
* try adding an authentication app
* tap the text below the QR code
* tap the revealed URI

**Comment by flocke** [comment]
This is already implemented in #393 and will be available in the next release.

**Comment by sm4rk0** [comment]
Great! Forgive me for a duplicate issue. I did search the existing ones (on my phone, in bed), but obviously not hard enough...
