### ISSUE TITLE
Forgotten Password, But Password is Weak?

### ISSUE THREAD

**Issue by UnlistedAverage** [andOTP/andOTP#448]
Hello,

I just locked myself out of my Discord app because I forgot the password to my andOTP. I logged out of my phone accidentally, which I almost never do, and now I can't get back in. I need access to that Discord account because it has chat logs I need to see and print out for my upcoming divorce. 

I'm not sure if I ever created a backup, or if one was created automatically. Where would I check for that in the file system? Is there any way to recover the password? If not, I know that my password was fairly weak, and as much as I'm loathe to suggest it, is there any way to bruteforce it? I know how that sounds, but it's my own device, and I'm fairly desperate. I really do need access to those chat logs. Divorce is not a fun time.
Edit: Or is there a debug mode? If so, would a developer be able/willing to help me using that method?

If there's no way to get this back, what are my password recovery options for if I'm forced to set up a fresh install in the future? Just in case I end up in this situation again. Or are there any recovery options that can be put in place, specifically for people who end up in a situation like mine. Which is an admittedly stupid situation, but it's a thing users do sometimes. 

Running the latest version of andOTP (I think, I'm not sure how to verify that without access to the app) from the Google Play store on my LG X Power 2, android 8.1.0

Apologies if this isn't the right place to ask this question. As I said earlier, I'm fairly desperate. 

Any help is appreciated. Thank you for your time and patience.

Thanks in advance

**Comment by gkeegan** [comment]
Check download and documents folders. Its possible you made a backup without a password on the backup, so look for "otp_accounts_[.........].json", or similar extensions. 

You could do a backup of the app data to PC and look around in it, but I'm not entirely sure how that works or how to do without root. (Probably some ADB command for it).

If you do find an encrypted file, and you know the password is weak, you could use a bruteforcing tool on it. Also don't forget to check all possible devices you may be signed into Discord on.

**Comment by gkeegan** [comment]
Also, password recovery options like "answer questions about you" are very insecure. I would hope they wouldn't ever be added to a program for security. 

Your safest bet for password recovery in the future is to write down the password of the vault and store it somewhere secure in a sealed envelope, with no context as to what it is, someplace where you wouldn't forget. (Fire safe of family member?)

**Comment by UnlistedAverage** [comment]
Thank you, that's very helpful. I'm not able to find any .json files matching that description, unfortunately. I can try to dig up the app information, assuming I can root the phone. Would you happen to know what the files look like from that perspective, in terms of naming structure or format? no worries if not.

I completely agree with your assessment of recovery options. I didn't exactly mean that, but I also didn't mean anything specific. I was more panicking than anything else. Users are going to forget passwords sometimes, it's just a thing that happens with a large enough userbase, but.. yeah, password management is ultimately the users responsibility. I'll definitely take your password storage advice on board moving forward. I wouldn't want to compromise everyone's security.

I'm taking it up with Discord too, since that's really my main issue here, and not andOTP. Hopefully they'll be able to help with my concerns on their side. Uh, though having said that, any help on this side is still welcome

Thanks again for your help

**Comment by gkeegan** [comment]
Yeah I don't have enough expertise to aid you any further into recovering it from within the files. I wouldn't try to root though, since that usually requires a factory reset afaik.

**Comment by RichyHBM** [comment]
What authentication method did you have enabled? Was it key store, or was it and otps own one?

**Comment by UnlistedAverage** [comment]
@gkeegan I see. I guess rooting after the fact isn't really an option then. Thank you for your help! I appreciate it

@RichyHBM Sorry, I'm not sure. Is there any way I can check?

**Comment by hettipeti** [comment]
Didnt't you saved somewhere the backup codes for Discord?

**Comment by flocke** [comment]
The problem is that without a backup file or access to the database file (which you can only get if you are rooted) we can't really do anything. Closing for now.
