### ISSUE TITLE
Add GOV.UK thumbnail

### ISSUE THREAD

**Issue by prcmt** [andOTP/andOTP#451]
Government Gateway accounts support 2FA.

Website: https://www.gov.uk/
Vector icon: https://github.com/alphagov/govuk-frontend/blob/ad596de756ef51619c6e5bc8f22f3b93479773dd/dist/assets/images/govuk-mask-icon.svg

**Comment by ziegenberg** [comment]
@flocke: Was included with 0.7.0 and can be closed.
