### ISSUE TITLE
Automatic backup (import / export) synchronisation to file

### ISSUE THREAD

**Issue by fredddii** [andOTP/andOTP#46]
I know there is already an automatic backup ticket but this request is a bit broader.

I use Syncthing to synchronise files in a decentralised manner across devices. It would be great if andOTP would automatically read from and write to the unencrypted / encrypted backup file, so that it can be then picked up by Syncthing (pure file based synchronisation) and sent to other devices, to for example another Android device with andOTP, which can then automatically synchronise any new changes.

andOTP Device #1 <-> entries.json.aes <-> Syncthing <-> entries.json.aes <-> andOTP Device #2

**Comment by flocke** [comment]
This is something I have to think about, I would have to change a lot for that to work ...

**Comment by RichyHBM** [comment]
I'm personally not a fan of the automatic restore idea, auto backup will be possible once the broadcast receivers go in

**Comment by flocke** [comment]
Yeah automatic restore is something I am not to keen on as well.

What I was thinking is maybe to allow the user to define the location where `secrets.dat` is stored so you can move it to the external storage. Combined with password-based encryption that would also allow you to sync the DB between different devices using an external app like Syncthing or Nextcloud.

**Comment by flocke** [comment]
But the more I think about this moving `secrets.dat` to external storage is another security issue as it would be accessible even without root or ADB. I think I will just close this request. It's not something a pure 2FA App needs.

**Comment by RichyHBM** [comment]
I agree, a work around can be achieved once we have the trigger able backups in, and with the help of scripts to convert from an and otp backup to what ever file format is needed

**Comment by hydrian** [comment]
While not automatic, how about a reminder with short cut to backup your config every time you add a new OTP consumer?

**Comment by flocke** [comment]
I like that idea better, an (optional) notification saying you should make a backup after you changed the database. And only on big changes like adding and removing of entries not on small ones like editing the label.
