### ISSUE TITLE
Thumbnail for TurboTax

### ISSUE THREAD

**Issue by stbxxl** [andOTP/andOTP#460]
Please add a thumbnail for TurboTax. This service supports TOTP based 2FA.

[TurboTax.svg](https://www.dropbox.com/s/sdex8pnfiqhtrjv/TurboTax.svg)

**Comment by ziegenberg** [comment]
The linked svg is just an embedded png inside an svg. So basically the vector is still missing.

**Comment by stbxxl** [comment]
Here's the true vector logo:  [turbotax-vector-logo.svg](https://www.dropbox.com/s/rz8rgig1vq19k77/turbotax-vector-logo.svg?dl=0)
