### ISSUE TITLE
Thumbnail for Xing

### ISSUE THREAD

**Issue by stbxxl** [andOTP/andOTP#461]
Please add a thumbnail for Xing. This service supports TOTP based 2FA.

[Xing.svg](https://www.dropbox.com/s/cs344fk38nnrw3p/Xing.svg)

**Comment by ziegenberg** [comment]
The linked svg is just an embedded png inside an svg. So basically the vector is still missing.

**Comment by stbxxl** [comment]
Here's the logo as true SVG file: https://commons.wikimedia.org/wiki/File:Xing_logo.svg
