### ISSUE TITLE
[Thumbnail] Add Hover

### ISSUE THREAD

**Issue by r4nd0m123** [andOTP/andOTP#470]
Please consider adding a thumbnail for Hover which is domain registrar.

**Name**: Hover
**Website**: https://www.hover.com/
**Link to SVG or EPS image**: https://www.hover.com/packs/src/application/images/common/hv_logo-aeb786424e4c4ba2a199aafaa1960943.svg

**Comment by ziegenberg** [comment]
The link to the svg is broken.

**Comment by ziegenberg** [comment]
found the svg on the home
