### ISSUE TITLE
Support automatic, encypted backup

### ISSUE THREAD

**Issue by PhilLab** [andOTP/andOTP#471]
**Is your feature request related to a problem? Please describe.**
I want to make sure that I don't loose my second factor and thus always backup when a new entry is created. As this is currently a manual step, I might forget that and loose one of my tokens when I have to use an out-dated backup.

**Describe the solution you'd like**
- The backup should use the encryption
- The backup file should be created every time something changes (new entry or entry deleted)
- The backup file path and extension should be configurable as I want to place it inside my Nextcloud App folder to auto sync
- The encryption password should be configurable (for my needs it would be sufficient to use the app unlock password)

**Describe alternatives you've considered**
Always pressing on backup and manually selecting the target file whenever I change something.

**Additional context**
-

**Comment by flocke** [comment]
Everything except the automatic Nextcloud sync should already be available in the next release (of which I just release a beta version today).
I will work on Nextcloud (and other Android Document providers) for the release after that. But since Androids Storage Access framework is all over the place, this could take a while.

**Comment by PhilLab** [comment]
@flocke This is awesome to hear 👍 Thanks for these features. Actually, if it is be possible to set an arbitrary file destination for the backup (and yes, I know the horrid problems with Android's FileProvider), the Nextcloud sync is automatically been taken care of by their app - so nothing left to do here

**Comment by flocke** [comment]
Yeah, I use Nextcloud as well. It works well for the manual backups, but not yet with the automatic ones. For that to work we need to request persistent access to a folder from the documents provider. Which is apparently handled differently depending on the Android version. I will have to do some reading before implementing it...

**Comment by flocke** [comment]
Moved to the v0.8.0 milestone, which will drop the support for Androidn 4.4 and 5.0 and as a result make the storage access implementation much easier.

**Comment by flocke** [comment]
This should theoretically now be possible with the new storage access setting implemented in 356815d7e76bca3c63b5c6572162d46a293cd87b. But it does not work with the Nextcloud app yet due to an upstream issue (see https://github.com/nextcloud/android/issues/303).
