### ISSUE TITLE
[Thumbnail] Add LivelyMe

### ISSUE THREAD

**Issue by magicwiser** [andOTP/andOTP#472]
Please add the thumbnail for livelyme: 

https://livelyme.com/static/images/favicon.ico

https://livelyme.com/

**Comment by alexanderadam** [comment]
IMHO as [SuperTinyIcons will be integrated](https://github.com/andOTP/andOTP/pull/398) it probably rather makes sense to [open that issue on SuperTinyIcons](https://github.com/edent/SuperTinyIcons/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
