### ISSUE TITLE
Steam OTP

### ISSUE THREAD

**Issue by iganeshk** [andOTP/andOTP#475]
#### General information

* **App version:** v0.6.3.1
* **App source:** Google Play
* **Android Version:** 10
* **Custom ROM:** OOS

Followed the steps listed at https://github.com/andOTP/andOTP/wiki/Special-features#steam-guard-codes but unable to generate OTP.

I see that STEAM is a manual entry type but in the manual entry dropdown dialog, I don't see STEAM. Was it suppose to detect issuer from end of the secrets string?

**Comment by flocke** [comment]
You need to enable the special features first before you can see the STEAM type in the manual entry window: https://github.com/andOTP/andOTP/wiki/Special-features#how-to-enable-the-special-features

**Comment by iganeshk** [comment]
oh, that was a rhetorical question!

**Comment by iganeshk** [comment]
The generated OTP doesn't seem to match authenticator (tried shared secret as well)

**Comment by flocke** [comment]
I will try it myself again. I had it enabled for about 2 years now, so maybe something changed in that time.

**Comment by iganeshk** [comment]
found out why, I mis-read the instruction's phrase "up-to" part.

**Comment by flocke** [comment]
Alright, thank you :+1:
