### ISSUE TITLE
[Thumbnail] Star Citizen

### ISSUE THREAD

**Issue by Archerofyail** [andOTP/andOTP#483]
**Name**: Star Citizen
**Website**: https://robertsspaceindustries.com/
**Link to SVG or EPS image**: https://1drv.ms/u/s!AsnJUFCVFzngssZuv0ZdUPT76zl0nA?e=xjcK7B

**Comment by ziegenberg** [comment]
Shouldn't we use the RSI logo as it's for a RSI account? Start Citizen is "just" the game used with the RSI account. They themselves use the RSI logo their own (now broken?) authenticator app.

**Comment by ziegenberg** [comment]
I've now used a vektor image from the official fankit
