### ISSUE TITLE
UX/UI: Drag & drop indicator

### ISSUE THREAD

**Issue by Prinzhorn** [andOTP/andOTP#487]
**Is your feature request related to a problem? Please describe.**

If you hold down your finger on an item, there is no indication that you can drag it. Only after moving your finger you realize that andOTP does indeed support reordering.

**Describe the solution you'd like**

As soon as the mode goes from scrolling to dragging (I guess like 700ms or whatever) there needs to be a visual indication. For example the background color of the item could change. Or it could become slightly larger with a stronger shadow giving the illusion of it hovering above its original location. I'm sure there are interface guidelines for Android that describe this in detail. Google Authenticator behaves different in this regard (an item can have a _selected_ state) but it does feature multiple drag-indicators on the selected item (background color, stronger shadow and an icon on the left).

**Comment by flocke** [comment]
Implemented in #488
