### ISSUE TITLE
Automatic backup did not create backup

### ISSUE THREAD

**Issue by Offerel** [andOTP/andOTP#490]
I installed 0.7.0-play version and tested the automatic backup. I get a toast message that the backup is successfully created, but if I look into the backup directory, it's empty and no file is created.

**Comment by Offerel** [comment]
I have to add, that manual creating the backup is working fine (at least, when i enable the "prompt before saving" feature).

**Comment by flocke** [comment]
So even manual backups do not work if you disable the "promt before saving" option?

**Comment by Offerel** [comment]
Yes, tested it again seconds ago. 

BTW: If I understand this correctly, the automatic backup should only work if certain preconditions are met, such as appending the date to the file name. At least for me the option was greyed out before. But once I have fulfilled the conditions and then remove the corresponding options, the entry for automatic backups remains active. Probably another bug, I just noticed. I can also add another issue for it, if you prefer.

**Comment by flocke** [comment]
Yeah, or should only be available if those conditions are met. It would be nice if you could open an issue for that as well.

Your original issue begins to sound like some kind of permission problem. Are you trying to save the backup to an external storage?

**Comment by Offerel** [comment]
Servus. Will open another issue, when im back from walking the dog. The toast pop reads mentions external storage "Export auf externen Speicher erfolgreich", but i didn't use a SD card in my device. 

Its a standard Galaxy S9, hardreset made at the weekend. If i enable asking for filename, the backup is saved. I can also import a backup successfully. Path isn't changed, i use the original path and created the folder manually with Solid Explorer, since andOTP complained that it cant access/create the folder. After creating the folder, the complains are disappeared.

**Comment by Offerel** [comment]
Tested this now with a Huawei device at Android 8. At least this issue described here, is working on the Huawei device. But its not working on the Samsung Galaxy S9 on Android 10. 

I have no idea, if that's only my specific S9 device which is failing here or if its a general Samsung issue or a Android 10 issue.

**Comment by Offerel** [comment]
Any news about this issue?

**Comment by flocke** [comment]
That sounds like a problem with Android 10, they reworked the storage access. I need to rework the entire autmatic backup process around it, which will take some time. Basically they removed the ability to just create files based on the path (which is what the automatic backup is doing) and require an app to use the storage access framework.

**Comment by Offerel** [comment]
Ca

**Comment by flocke** [comment]
Implemented the storage access framework in 356815d7e76bca3c63b5c6572162d46a293cd87b.
