### ISSUE TITLE
[Thumbnail] Patreon

### ISSUE THREAD

**Issue by stbxxl** [andOTP/andOTP#497]
Please fill in **all the information below** to help speed up the process!

**Patreon**:
**www.patreon.com**:
**[patreon-vector-logo.svg](https://www.dropbox.com/s/sw8yctzfcvy7fps/patreon-vector-logo.svg?dl=0)**:

**Comment by ziegenberg** [comment]
Patreon uses a new logo now, see https://www.patreon.com/brand for reference. And the logo for Patreon is already in the app sind 0.4.0.

So imho this issue can be closed.
