### ISSUE TITLE
HOTP Support

### ISSUE THREAD

**Issue by flocke** [andOTP/andOTP#5]
Support HOTP tokens in addition to TOTP

**Comment by Datenschutz** [comment]
I'd suggest to remove the option for adding a HOTP for the time being then.

**Comment by flocke** [comment]
@Datenschutz Done, I removed the HOTP option for now (was still there from some internal testing).

**Comment by RichyHBM** [comment]
This may be useful, https://github.com/winauth/winauth/blob/master/Authenticator/HOTPAuthenticator.cs

**Comment by sjug** [comment]
This would be really great to add as one still needs to use a different app to generate HOTP tokens at the moment.

**Comment by flocke** [comment]
I'm gonna release 0.4.1 and make it stable on Google Play (if no critical issues get reported here). After that the next big step is gonna be HOTP.

**Comment by flocke** [comment]
Closed it a little prematurely. I have a working implementation for HOTP and you can already add accounts by scanning a QR code but there are still a few things to be done:
- [ ] Manually enter HOTP accounts
- [ ] Tests for the HOTP generation

**Comment by flocke** [comment]
Anyone that wants to test the HOTP support can sign up for the beta testing on the Google Play store.
I'm still trying to figure out what is the best way to distribute beta versions on F-Droid.

**Comment by sjug** [comment]
@flocke where is the beta enrollment page?

**Comment by maracuja-juice** [comment]
@flocke Releasing them as Pre-Release on GitHub is one way (but not directly done trough F-Droid)

**Comment by sjug** [comment]
Do we need to manually iterate the `#` to the left of the copy button?

**Comment by flocke** [comment]
@maracuja-juice Yes, that is on my todo list. But I'm currently not on my build machine with the correct signing keys.
@sjug Yes, for now you have to manually iterate the counter. Tapping the counter increases it by one, long pressing it opens a dialog where you can manually edit it. I will have to come up with an idea to improve the usability a bit.

**Comment by sjug** [comment]
With the hidden option enabled, it does make sense to iterate before/after reveal that way each time you show it has a new value.

**Comment by flocke** [comment]
@sjug Yes, I was thinking about maybe dropping the hidden option for HOTP type tokens and always show something like "Tap to generate token" which has to be pressed to create a new token.

**Comment by ghjkl99** [comment]
sorry, andOTP does not seem to work for Duo Security's HOTP protocol. Tried scanning Duo's QR code or entering the secret but get error "invalid QR code" or "invalid secret" respectively, using andOTP 0.7.1.1. Am I missing something ? thanks.

**Comment by Adonai** [comment]
@ghjkl99 use [puddly/android-otp-extractor](https://github.com/puddly/android-otp-extractor) to extract Duo Mobile QR code, then scan it with AndOTP. It works.

**Comment by trumad** [comment]
I struggled for a couple of hours to piece everything together, but here's how I got Duo auth imported into andOTP. This likely only works if you used Magisk to root your phone, and if you are running Windows:

1 Get [ADB shell](https://adbshell.com/downloads) (untested, but this version should work. You basically need adb.exe)
2 get Python 3
3 Download and extract or clone [this github repo](https://github.com/puddly/android-otp-extractor)
4 Copy the contents of the adbshell zip file into the src directory
5 On your rooted android phone, use Magisk to install busybox:
5a Click the puzzle piece
5b Search busybox
5c Install
5d Reboot
6 In cmd, go to the src directory
7 Type `python -m android_otp_extractor`
8 A browser window should open with a QR code
9 Use the QR code to import the Duo 2FA into andOTP
