### ISSUE TITLE
2fa on certain sites does not work with andOTP

### ISSUE THREAD

**Issue by Toto-Africa** [andOTP/andOTP#502]
There are certain sites where I cannot get 2fa to work with andOTP. I encountered the problem with the following sites: LinkedIn, Reddit and Firefox account. I scanned the corresponding QR-codes and manually entered the keys multiple times. When entering the generated OTP on the mentioned sites, it gives an error message saying that the OTP is incorrect.

**Comment by beerisgood** [comment]
Is your device time ok?
Reddit works for me without problems

**Comment by flocke** [comment]
Like  @beerisgood mentioned, that sounds like an issue with your phones clock. I wrote a little bit about this [in the FAQ](https://github.com/andOTP/andOTP/wiki/Frequently-Asked-Questions#user-content-faq3).

**Comment by Toto-Africa** [comment]
@flocke and @beerisgood   
Thanks for helping me out! The problem was indeed in the device time. I'm sorry that I had to open a bug report for this, but I did a quick search before posting and couldn't find anything useful. Thanks again for helping me out!
