### ISSUE TITLE
Discord issues

### ISSUE THREAD

**Issue by mixxit** [andOTP/andOTP#504]
Version: 0.7.0-play

Failure when trying to create 2fa for discord

![image](https://user-images.githubusercontent.com/233287/76518437-02323a80-6457-11ea-9c89-b2e74e481dce.png)

This used to work but no longer does now?

**Comment by apollo2k4** [comment]
check the accuracy of time on your devices

**Comment by mixxit** [comment]
both my local clock and phone clock are correct date and time

**Comment by mixxit** [comment]
damnit you are right one was off by a minute! this has solved it

**Comment by beerisgood** [comment]
Same problem as https://github.com/andOTP/andOTP/issues/502

@flocke 
maybe this should be added to a FAQ

**Comment by flocke** [comment]
I already have an entry about tokens not working in the FAQ. But if you have an idea what we can add to that I would be happy to edit it.

**Comment by h1z1** [comment]
Having run into this many times, I'd suggest perhaps adding a time when the token will expire?  May seem odd but there are devices out there with horrible clocks especially when they are used offline.
