### ISSUE TITLE
Present previous and most recent code

### ISSUE THREAD

**Issue by dennisguse** [andOTP/andOTP#506]
**Is your feature request related to a problem? Please describe.**
AndOTP only shows the most recent TOTP code.
Sometimes while entering the TOTP code on a 2nd device, a new TOTP is generated.
As the previous one is not visible (and I sometimes not recall the last digits), I have delete the entered digits and enter the new code.

However, the previous code is still valid for some time (I guess several seconds but did not try to measure it with systems I use).

**Describe the solution you'd like**
Present the most recent TOTP code (as it is at the moment) while also showing the previous TOTP code (smaller; left of the most recent TOTP code).

**Comment by flocke** [comment]
I am currently planing to implement it like this (right of the current token, not left):

![Screenshot_1616927948](https://user-images.githubusercontent.com/76665/112749461-97509480-8fc2-11eb-835f-703b6ba219fb.png)

I'm not sure that's really intuitive, but having the smaller number left of the token just looks really bad in my opinion:

![Screenshot_1616928128](https://user-images.githubusercontent.com/76665/112749511-fca48580-8fc2-11eb-8a03-70c3bf59d2ce.png)

**Comment by dennisguse** [comment]
To the right makes a lot more sense ;)
And it looks great! Thanks for taking the time!
