### ISSUE TITLE
Navigation bar - light icons on light background

### ISSUE THREAD

**Issue by o-alquimista** [andOTP/andOTP#507]
After upgrading to version `0.7.0-play`, the navigation bar looks strange.

Its background matches the application theme, which is light. The icons are also white, with a very subtle shadow. This makes it very hard to see them.

Darker themes are not affected. They look normal. I can't take a screenshot, as the application doesn't allow it.

Device:
- Moto G4 Play (harpia)
- LineageOS 14.1 (Android 7.1.2)

**Comment by flocke** [comment]
That behavior depends heavily on your ROM. The app only sets the background color for the nav bar, not the foreground. That is determined by the system as far as I know. On my system (Android 10, Stock) it looks like this: https://cloud.shadowice.org/s/gsi76Q4oDnm3MzS

**Comment by flocke** [comment]
Is this still happening?

**Comment by o-alquimista** [comment]
My device was upgraded to LineageOS 17.1 (Android 10) and I don't have this problem with it (on both light and dark theme).

It might still be affecting LineageOS 14 (Android 7), but I can't confirm that anymore.

Enviado via ProtonMail móvel

-------- Mensagem Original --------
Ativo 3 de mar de 2021 14:29, Jakob Nixdorf escreveu:

**Comment by flocke** [comment]
I will close the issue for now, feel free to reopen if it still happens.
