### ISSUE TITLE
Support fingerprint as authentication method

### ISSUE THREAD

**Issue by SeppPenner** [andOTP/andOTP#516]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I don't know how much effort it is but it would be nice if authentication via fingerprint was supported on device where the feature is available.

**Describe alternatives you've considered**
None yet.

**Additional context**
Maybe check https://github.com/bpellin/keepassdroid. It does have the feature enabled. (More specific, check https://github.com/bpellin/keepassdroid/blob/master/app/src/main/java/com/keepassdroid/fragments/PasswordFragment.java).

**Comment by SeppPenner** [comment]
Oh, I just found the following issues: https://github.com/andOTP/andOTP/issues/150 and https://github.com/andOTP/andOTP/issues/127. I don't know how much effort it is to integrate this here or if it's even possible.

**Comment by beerisgood** [comment]
You can already protect your database with fingerprint

**Comment by SeppPenner** [comment]
Oh, sorry :D It works. Just need to set the database security options to "Android key store" and the authentication method to "device" or so.
