### ISSUE TITLE
Password forgoten 

### ISSUE THREAD

**Issue by adlisval** [andOTP/andOTP#518]
Hi, I don't remember what password I used to open the app and I have used it only once, for 1 website.

Is it possible to reset the password for the app (andOTP)? Or will I be able to access the website without andOTP? 

Any recommendation would be helpful, thank you.

**Comment by gkeegan** [comment]
You can't reset the password for the andOTP due to security reasons. Depending on what site it was, emailing their support may help you.

**Comment by flocke** [comment]
As @gkeegan already mentioned you can't reset the password for andOTP as it is directly used to encrypt your data on your phone and any method of password recovery would basically be a backdoor in that encryption.

Usually a site should give you (multiple) backup codes when you activate 2FA for exactly that case. If you don't have them anymore contacting their support is your only option.

**Comment by adlisval** [comment]
Thanks. I just contacted the website and asked for a 2FA reset...
