### ISSUE TITLE
[Thumbnail] Mozilla Firefox

### ISSUE THREAD

**Issue by scollovati** [andOTP/andOTP#520]
I installed the new version 0.7.0 and Mozilla Firefox icon went away.

**Comment by flocke** [comment]
It's still there for me, could someone else please confirm?

**Comment by scollovati** [comment]
I forgot to add that it was installed via F-Droid.

**Comment by flocke** [comment]
It shouldn't matter if it's from F-Droid, but what could matter is your Android version and your phone model. It could have something to do with the gradients in the images.

If you enable the special features by tapping the version in the About screen seven times you can enable screenshots in the settings. It would be nice if you could do that and post a screenshot of the thumbnail selection window so I can see which icons are affected. You can disable screenshots and the special features again in the settings afterwards.

**Comment by scollovati** [comment]
Thanks for the updates.
Unfortunately even with advaced features enabled I cannot take screenshots.

Android: 6.0.1 (CyanogenOS 13.1.2)

**Comment by scollovati** [comment]
Here are some screenshot, they should cover all missing icons.

Android 6.0.1 - CyanogenOS 13.1.2

![Screenshot_20200414-201917](https://user-images.githubusercontent.com/20740642/79259776-8f6d1280-7e8d-11ea-9db4-345402049edd.png)
![Screenshot_20200414-201924](https://user-images.githubusercontent.com/20740642/79259903-b7f50c80-7e8d-11ea-892a-de301f313bf2.png)
![Screenshot_20200414-201929](https://user-images.githubusercontent.com/20740642/79259788-92680300-7e8d-11ea-8798-96688b12107c.png)
![Screenshot_20200414-201938](https://user-images.githubusercontent.com/20740642/79259794-93993000-7e8d-11ea-9252-76e54a35da5b.png)

**Comment by nsartor** [comment]
I'm using 0.7.0 from f-droid and I see it, along with a bunch of others that scollovati appears to be missing. 
Is there an accessibility setting maybe? My icons are in columns of 5, yours are showing 3 and i wonder if this missing ones are cutoff?

**Comment by flocke** [comment]
No, how many columns are shown depends on your phones display and the thumbnail size you set in the settings. The missing ones are shown as andOTP icons.
I don't think it has something to do with the accessibility settings, from what I know it is just that some phones and Android versions can't properly display icons with color gradients in them.

**Comment by flocke** [comment]
This was fixed in 9bf12085bf088c0a0ecded9e1e1d254210179f0d together with #539
