### ISSUE TITLE
Deprecation notice for old Android versions

### ISSUE THREAD

**Issue by flocke** [andOTP/andOTP#535]
Add a one-time popup message explaining the discontinued support for Android versions below Android 5.1 after 0.7.1.

**Comment by ThiefMaster** [comment]
Any reason why this notice is being shown to people on a recent Android (9)?

Deprecating old versions makes perfect sense, but bothering people who don't use a horribly outdated version is a bit annoying :) Might also scare off less technical people who think they now have to do something or find another app..
