### ISSUE TITLE
Issuer is not stripped from the label when adding via URL / QR Code

### ISSUE THREAD

**Issue by SagePtr** [andOTP/andOTP#551]
#### General information

* **App version:** 0.7.0-play, 0.7.1-beta2
* **App source:** Google Play,  GitHub
* **Android Version:** 5.1
* **Custom ROM:**

#### Expected result
**What is expected?** 
Label should not include issuer name, only username, as issuer is stored separately.
Should look: **issuer** - username

**What does happen instead?**
Label includes issuer name, so it's duplicated.
It looks: **issuer** - issuer:username

#### Steps to reproduce
Scan any QR code with openauth:// url made by [this recommendation](https://github.com/google/google-authenticator/wiki/Conflicting-Accounts#recommendation-for-code-generation-app-developers) from Google. The link has format:
```otpauth://totp/Example:username?secret=AABBCCDDEEFFGGHH&issuer=Example```
Here is example QR code with above link encoded:
![example-totp-qr](https://user-images.githubusercontent.com/3179266/82101303-782f7800-970c-11ea-95ae-61d1dd769f1b.png)

The recommendation says:
> If you encounter encoded URIs where the issuer name appears in the prefix as well as a URI parameter, consider stripping the issuer name in the UI and branding accordingly.

So, according to it, issuer should be "Example" and username should be "username" with issuer stripped from it.
Instead of this, we get "Example" as issuer name (correct) and "Example:username" as label (incorrect).
It doesn't matter whenever QR Code was scanned inside andOTP, or scanned with internal application and passed link into andOTP, so it looks that issue is related to URL parsing, not QR code recognition.

Here is screenshot how it looks (i made screenshot with emulator because andOTP prevents from making screenshots, but on actual hardware it looks the same:
![image](https://user-images.githubusercontent.com/3179266/82101592-2affd600-970d-11ea-8a91-8eb6c9a5bacf.png)

**Comment by shivasheeshyadav** [comment]
Hi @SagePtr 
I would like to work on this issue.
Also, it would be great if you could include info about the local setup of the project.

**Comment by SagePtr** [comment]
> Hi @SagePtr
> I would like to work on this issue.
> Also, it would be great if you could include info about the local setup of the project.
Thank you. I have no idea about the local setup because i'm not a java coder, tested the bug only on prebuilt binaries from Play and this repo.

**Comment by flocke** [comment]
The local setup is pretty straight forward, it's basically like every other Android project. Just fork and clone the Github repo, import it in Android Studio and you are ready to go.

**Comment by shivasheeshyadav** [comment]
Thanks @flocke 
I'll work on it. You could assign it to me.

**Comment by shivasheeshyadav** [comment]
Hi @flocke @SagePtr 
Please review
https://github.com/andOTP/andOTP/pull/560

**Comment by flocke** [comment]
Closed in #560.
