### ISSUE TITLE
[Thumbnail] Mint.com

### ISSUE THREAD

**Issue by Caligatio** [andOTP/andOTP#555]
Please fill in **all the information below** to help speed up the process!

Admittedly the actual 2FA issuer is Intuit but each of their services/products uses a different logo.

**Name**: Mint.com
**Website**: https://www.mint.com
**Link to SVG or EPS image**: [intuit-mint-logo.svg.txt](https://github.com/andOTP/andOTP/files/4643373/intuit-mint-logo.svg.txt)

**Comment by ziegenberg** [comment]
Do they share one central account or does every service has it's own account?

**Comment by Caligatio** [comment]
You go to their product page (e.g. mint.com), you get shunted off to something like account.intuit.com for login, and then redirected back to mint.com. The credentials and security settings are centralized but each service has its own profile.

My take: Intuit basically gobbles up web services and fiddles with the login slightly but leaves the user profile largely in the hands of the original service.

**Comment by ziegenberg** [comment]
If you've got an account for mint.com and turbotax you'd have the same credentials. So if one uses two or three of those services it's always the same login, and hence the same 2FA, but which icon should we apply? I find this one a bit tricky. By the way: account.intuit.com resolves to NXDOMAIN
And only mint.com got it's own domain as turbotax, proconnect and quickbooks are just subdomains of intuit.com

**Comment by Caligatio** [comment]
Sorry, it is accounts.intuit.com (plural accounts).  The login is shared across all their services: https://accounts-help.lc.intuit.com/questions/1582580-creating-an-account

I'm guessing Mint is unique as it was a later acquisition?

I agree this one is tricky. Strictly speaking it should probably be an Intuit logo but I suspect more people think "I want to use Mint" than "I need to login into my Intuit account." Maybe we can add them both and just let the user decide?

P. S. - Even https://twofactorauth.org/ lists it as Mint.

**Comment by ziegenberg** [comment]
And https://accounts.intuit.com/ is also not helpful, cause it show three icons at once 🙈
