### ISSUE TITLE
[Thumbnail] Samsung Account 

### ISSUE THREAD

**Issue by D0mm4S** [andOTP/andOTP#562]
Please fill in **all the information below** to help speed up the process!

**Samsung Logo**:
**https://www.samsung.com/**:
**was looking at the favicon, but its only an .ico, maybe some expert can help here**:

**Comment by ziegenberg** [comment]
The Samsung logo can be found here: https://commons.wikimedia.org/wiki/File:Samsung_wordmark.svg
But that's not gonna look good in andOTP because it's not even remotely square.

**Comment by kinqsley** [comment]
This is the logo use for Samsung account app in Samsung phones:
https://account.samsung.com/membership/assets/images/favicon.ico

https://account.samsung.com/membership/intro

**Comment by ziegenberg** [comment]
I've now build a svg version of the Samsung account icon, cause I couldn't find a vector based version in a quick google search.

btw: If someone knows someone at Samsung, could you please ask them for me, why their logo isn't mirror symmetric? The head is ever so slightly off-centre. Why though?

**Comment by ziegenberg** [comment]
Was fixed with #623.
