### ISSUE TITLE
[Thumbnail] OpenVPN

### ISSUE THREAD

**Issue by hschoeffmann** [andOTP/andOTP#563]
Please fill in **all the information below** to help speed up the process!

**Name**: OpenVPN
**Website**: https://openvpn.net/
**Link to SVG or EPS image**: https://upload.wikimedia.org/wikipedia/commons/f/f5/OpenVPN_logo.svg

**Comment by alexanderadam** [comment]
This issue will be solved when [PR 398](https://github.com/andOTP/andOTP/pull/398) is merged because [SuperTinyIcons already contains the OpenVPN logo](https://github.com/edent/SuperTinyIcons#security).
