### ISSUE TITLE
Latest version doesn't show icon for Github correctly

### ISSUE THREAD

**Issue by SeppPenner** [andOTP/andOTP#564]
-----------------------------

#### General information

* **App version:** 0.7.1.1-play
* **App source:** Google Play
* **Android Version:** 10
* **Custom ROM:** No

#### Expected result
Github icon shows in the app.

#### What does happen instead
Only a "G" is shown in the overview list.

#### Logcat
None.

#### Steps to reproduce
 Open the app with a Github account.

**Comment by flocke** [comment]
Can you check and see if the icon is still there if you go and change it manually?

**Comment by flocke** [comment]
@ziegenberg You changed the spelling of the Github thumbnail in one of your PRs, right? That could maybe cause this, in that case the fix should be fairly easy, I will try to work on something tomorrow.

**Comment by ziegenberg** [comment]
I can reproduce this issue for an existing GitHub Account in andOTP 0.7.1-play after the update. The icon is gone and only a "G" is shown

**Comment by flocke** [comment]
Yeah, the reason is that the Github icon was called "Github" before the update and now it's called "GitHub". Should be fairly easy to fix, we just need to make the thumbnail selection case insensitive.
The function for that already exists, I just need to use it in the correct place.

**Comment by ziegenberg** [comment]
But a newly added GitHub to andOTP is correctly recognised.

**Comment by ziegenberg** [comment]
The Issuer string given by GitHub is "GitHub". However, I am also in favor of making the thumbnail selection case-insensitive. I guess this way we will avoid possible future trouble.

**Comment by flocke** [comment]
Thank you, I just wanted your input since you did most of the thumbnail-related work in the last update. I will implement the case insensitive selection tomorrow.

**Comment by ziegenberg** [comment]
Oh, thx for considering my input. But I really just added some SVGs. Nothing big actually.

**Comment by SeppPenner** [comment]
The icon can be changed manually. Sorry for the late reply. Seems like you already figured it out ;)
