### ISSUE TITLE
Can't import my accounts 

### ISSUE THREAD

**Issue by unLieb** [andOTP/andOTP#566]
It's not really a bug, more of a problem. 

After many recommendations and due to the fact that my previous 2FA App and WinAuth are no longer being developed, I would like to switch to andOTP. 

But now I have the problem that andOTP can only import JSON files, but my Apps only want to export them as text files. 

So how do I get the text file into andOTP?

**Comment by flocke** [comment]
Currently andOTP can only restore its own backup files. We can not import backups from other apps.

**Comment by flocke** [comment]
The initial idea for importing data from other applications was to provide a JavaScript-based solution that converts this data into the JSON format that andOTP uses.

But I don't have time to work on something like that, so maybe someone else is interested in this.

**Comment by unLieb** [comment]
Okay, so then for now, no changing. 
Thanks anyway.

**Comment by unLieb** [comment]
It is a "simple" text file.

**Comment by ziegenberg** [comment]
Well, for writing an importer we'd need to know how exactly the data inside the *.txt ist formatted.

**Comment by unLieb** [comment]
The easiest thing to do would have been to quickly load WinAuth and have a look yourself. 

But all right, if this will help. In the txt file it looks like this. 


```
otpauth://totp/**********?secret=L5AKZNLVNOCWMWR*****UW7L4M53&digits=6
otpauth://totp/LastPass:********?secret=2XHYD7B******5UVX&digits=6&issuer=LastPass&icon=LastPass
otpauth://totp/Dropbox:******?secret=JJXRWLQF6VXSYJQHJDSQAWJTK4&digits=6&issuer=Dropbox&icon=Dropbox
otpauth://totp/BattleNet:******?secret=SOWAIVOUOQI2WQUIEZZAMRH6ROCXJFDC&digits=8&issuer=BattleNet&serial=EU170212731260
otpauth://totp/Amazon:*********?secret=W2Q73OIYVTBVCOGNEQG2VIFR3ATMJP4R5CS6SPR23VPQO4MLHYKQ&digits=6&issuer=Amazon&icon=Amazon
otpauth://totp/Ubisoft:**********secret=OFGEMVCXMJEW4Q2J&digits=6&issuer=Ubisoft
otpauth://totp/Facebook:*********?secret=P5OOBRQRK7QFMY4B2ETG5IN5UTFQKCQG&digits=6&issuer=Facebook&icon=Facebook
otpauth://totp/Steam:Steam?secret=7EPGWEEJNEGTBE3*******JTWKGHDHB&digits=5&issuer=Steam&deviceid=android%3a8f7f8b9b-a053-*****-97ff-*********%7b%22shared_secret%22%3a%22%2bR5rEI******eig2tHpnZRjjOE%3d%22%2c%22serial_number%22%3a%22*********55772%22%2c%22revocation_code%22%3a%22R74218%22%2c%22uri%22%3a%22otpauth%3a%2f%2ftotp%2fSteam%3aprinceporn%3fsecret%3d7EPGWEEJNEGTBE3J5CQNVUPJTWKGHDHB%26issuer%3dSteam%22%2c%22server_time%22%3a%221590250224%22%2c%22account_name%22%3a%22princeporn%22%2c%22token_gid%22%3a%221dd9cee08c1ede84%22%2c%22identity_secret%22%3a%22N0eZInkk4z7bOZWO59hM2IcmNVQ%3d%22%2c%22secret_1%22%3a%22L8GRWa18x2APkiW%2fUAwRbfeid0k%3d%22%2c%22status%22%3a1%2c%22steamid%22%3a%2276561198009421196%22%2c%22steamguard_scheme%22%3a%222%22%7d
otpauth://totp/SynologyAccount(**********)%40?secret=AXAEN*********I&digits=6
otpauth://totp/HumbleBundle:*********?secret=3NIFALOZFP**********Z3EQ&digits=6&issuer=HumbleBundle
otpauth://totp/eu.wargaming.net:********(ID%3a+500********66)?secret=KHLASKYJGF4APOGUF********R&digits=6&issuer=eu.wargaming.net
otpauth://totp/FRITZ!Box 7590:***************?secret=3NLAR35A2H6U6NW*********V2UFZTS&digits=6&issuer=FRITZ!Box+7590
```

**Comment by flocke** [comment]
So it's basically just the otpauth URLs, that should be fairly easy to parse.

**Comment by gkeegan** [comment]
Uh are you sure that is safe to post online?

**Comment by unLieb** [comment]
Why? My account names are starred, and I have starred several stables in the keys.

**Comment by flocke** [comment]
@unLieb You censored a lot of the important parts, but now that we got an idea of the file structure you should probably delete that part of the comment just to be sure.

**Comment by unLieb** [comment]
That was the reason why I thought it was easy to see for yourself. 
I mentioned above that I use WinAuth.

**Comment by flocke** [comment]
In your original post you said something about WinAuth and "my previous 2FA App", so we were not really sure which you were talking about. But now that we know what the file contains everything is fine, that's a pretty common format and should be fairly easy to parse.

**Comment by flocke** [comment]
Now that I think about it that should be the same format that #360 is talking about, which aims to be a standard between different 2FA apps. Maybe we should make an exception and implement importing of that format directly in andOTP.

**Comment by ziegenberg** [comment]
hi @unLieb!
I should have been more precise and tell upfront not to post secrets and usernames online and mask them altogether.
The following would have been sufficent.
```
otpauth://totp/Google:USER@google.com?secret=SECRET&issuer=Google
```

I advise you to delete the following post completely. It has an edit history...

> The easiest thing to do would have been to quickly load WinAuth and have a look yourself.
> 
> But all right, if this will help. In the txt file it looks like this.
> 
> ```
> otpauth://totp/**********?secret=
> ```

**Comment by flocke** [comment]
The format is the same as that discussed in #360, so I will close this issue since it is basically a duplicate.
