### ISSUE TITLE
Switching language is not working.

### ISSUE THREAD

**Issue by BoFFire** [andOTP/andOTP#567]
#### General information

* **App version:** 0.7.1.1
* **App source:** GitHub
* **Android Version:** 6

#### Expected result
**What is expected?** 
When switching language, the UI should display the right language

**What does happen instead?**

The app is falling back to english

#### Steps to reproduce
 
I think that the app should use `values-ar` `values-fr` etc instead of the regionalized `values-rLangRegion`

This can be disabled on Crowdin.

**Comment by flocke** [comment]
Which language are you trying to switch to? Because it works without problems for me.

**Comment by BoFFire** [comment]
From English or French to arabic.

**Comment by flocke** [comment]
And are you switching the language in the app or for your entire phone?

**Comment by BoFFire** [comment]
I tried switching from the app. Result : fallback to english.
Tried to switch the Android system to arabic and app in arabic. Result : fallback to english.

**Comment by BoFFire** [comment]
See : https://github.com/TwidereProject/Twidere-Android/issues/1319
