### ISSUE TITLE
Consider supporting encrypting and backing up text

### ISSUE THREAD

**Issue by emchristiansen** [andOTP/andOTP#568]
It would be nice if andOTP could also encrypt and backup text, e.g. website passwords and crypto wallet seed phrases.
Is this something that can be supported?
Apologies if this is a naive question / ill advised.

**Comment by flocke** [comment]
At some point there will be support for adding custom text to the database (see #538), but what you are describing is more like a password manager than a 2FA app. There are way better solutions for that than andOTP, e.g. [KeePassDX](https://github.com/Kunzisoft/KeePassDX).
