### ISSUE TITLE
HOTP confusingly shows countdown yellow bar

### ISSUE THREAD

**Issue by axelsimon** [andOTP/andOTP#572]
#### General information

* **App version:** 0.7.0
* **App source:** F-Droid 
* **Android Version:** 10
* **Custom ROM:** GrapheneOS

An HTOP, or event-based OTP, is only renewed when the user requests a new one, as such, there is no concept of time countdown for HOTPs.

#### Expected result
**What is expected?** 
HOTPs should not present the user with a countdown, in the form of the yellow bar at the top of the token, especially if the only entry in andOTP is a HOTP.

**What does happen instead?**
The yellow bar representing the 30 seconds appears above the HOTP, leading users to believe the token will only be valid until the bar empties out, or that it will automatically regenerate when the bar empties out.

#### Logcat
```
(design issue, not needed)
```

#### Steps to reproduce
 
 * add an HOTP to andOTP

**Comment by ziegenberg** [comment]
Is this maybe the global yellow countdown bar you are seeing?

**Comment by axelsimon** [comment]
I'm guessing it is.

I only have one token in AndOTP, an HOTP, but from what you are saying, i understand this bar is always shown. I think that's the crux of the issue, there should probably be a test to check that there is a least one TOTP before showing it, otherwise it makes no sense and just confuses users.

**Comment by flocke** [comment]
Your suggestion makes sense, and I probably will implement it at some point. But it has a low priority since there are a lot more pressing issues that I have to work on.
For now you can always disable it manually from the settings if you don't want it (Settings -> UI section -> Hide global timeout bar).

**Comment by axelsimon** [comment]
Thanks for your reply.

I just went into my settings and… i don't have that option.

**Comment by flocke** [comment]
Right, it was added in version 0.7.1, which just became available on F-Droid.

**Comment by flocke** [comment]
Closing, the option to hide the timeout bar should be enough for now.
