### ISSUE TITLE
Enable PGP backups via Keybase

### ISSUE THREAD

**Issue by bartlettc22** [andOTP/andOTP#577]
It would be great if you could enter a [Keybase username](https://keybase.io/docs/api/1.0/call/user/pgp_keys.asc) and have andOTP encrypt backups using that PGP key.

I'm not exactly sure how restores would be done though...

**Comment by flocke** [comment]
This won't be added to andOTP since andOTP doesn't actually manage the PGP keys for the backup itself, it relies on an external app (OpenKeychain) for that.
From what I know OpenKeychain already supports searching and importing keys from keybase.

**Comment by beerisgood** [comment]
Keybase is owned by Zoom so I wouldn't use it at all.
