### ISSUE TITLE
Dragging tokens with automatic backups enabled for all changes, creates lots of backups

### ISSUE THREAD

**Issue by Gnarfoz** [andOTP/andOTP#579]
#### General information

* **App version:** 0.7.1.1-play
* **App source:** Google Play
* **Android Version:** 8.0
* **Custom ROM:** -

#### Expected result
**What is expected?** 
I'm not sure the position of the token in the list is even included in the backup.
If it is, a backup should only be triggered when the token is not being dragged anymore.

**What does happen instead?**
A backup is created for each position change *while being dragged*, resulting in possibly dozens of backups when moving a freshly created token from the bottom of the list to the top, depending on length of list.

Not quite a bug (probably even qualifies as "working as intended"), but still a bit silly. ;-)

**Comment by flocke** [comment]
Fixed in fff5a9079dfa005954333c4f1e8f9832c2c1ba22.

**Comment by Gnarfoz** [comment]
Wow, that was quick! Thanks! 👍
