### ISSUE TITLE
[Thumbnail] Proxmox

### ISSUE THREAD

**Issue by cmonty14** [andOTP/andOTP#586]
**Name**: Proxmox
**Website**: [https://www.proxmox.com/](https://www.proxmox.com/)
**Link to SVG or EPS image**: [https://www.proxmox.com/images/proxmox/Proxmox_logo_standard_hex_400px.png](https://www.proxmox.com/images/proxmox/Proxmox_logo_standard_hex_400px.png)

**Comment by flocke** [comment]
This has been in andOTP for about a year now. See #337 and https://github.com/andOTP/andOTP/commit/3eecadfa9a7015f0c08a1c689eaa9ddc7a8aaad9
