### ISSUE TITLE
PC version

### ISSUE THREAD

**Issue by CodingSpiderFox** [andOTP/andOTP#587]
I want to use my OTP codes also when I forgot my phone at home.
So it would be nice to have a PC app (for all major platforms) where I can import the backup file.

**Comment by beerisgood** [comment]
Already possible:
https://github.com/andOTP/andOTP#opening-the-backups-on-your-pc

**Comment by CodingSpiderFox** [comment]
Can it only decrypt the backup or also generate the OTP codes from the backup?

**Comment by magiruuvelvet** [comment]
Doesn't look like any of the methods generate anything, just decrypt the backup. At this point I shamelessly self advertise my desktop application which is cable of generating OTP passwords (https://github.com/magiruuvelvet/OTPGen). It can directly import andOTP encrypted backups too, so no need of those tools mentioned. I don't provide binaries though so building it from source is required.

**Comment by beerisgood** [comment]
Or use a OTP app from Windows Store but remember that two factor mean that at least two different devices are used.
- Password from device A
- OTP from device B

Or you need to switch to online solution like Bitwarden if you need such sync features for more then using one device

**Comment by flocke** [comment]
I won't create a PC version myself. But as the other already mentioned, there are some apps already available that can import andOTP backups and generate 2FA tokens from them. Besides the one from @magiruuvelvet there is also this one: https://github.com/paolostivanin/OTPClient

**Comment by ziegenberg** [comment]
I suggest to close this issue, because even if there every will be a PC version, it most certainly will live within it's own repository, because this is for the android app.
