### ISSUE TITLE
[Thumbnail] ESEA

### ISSUE THREAD

**Issue by TheBliTzzzzzz** [andOTP/andOTP#594]
Please fill in **all the information below** to help speed up the process!

The green star is the small logo, but I couldn't find an SVG of that only.

**Name**: ESEA
**Website**: https://play.esea.net/
**Link to SVG or EPS image**: https://cdn.worldvectorlogo.com/logos/esea-2.svg

**Comment by ziegenberg** [comment]
The provided SVG is not an original one. Especially the s' shape is distorted. Luckily they use vector images on their homepage and therefore I'll use the svg paths from their page.

**Comment by TheBliTzzzzzz** [comment]
Awesome to hear.
