### ISSUE TITLE
check andOTP security problems by "Immuniweb" Mobile Application Security Test

### ISSUE THREAD

**Issue by beerisgood** [andOTP/andOTP#596]
**Is your feature request related to a problem? Please describe.**
andOTP 0.7.1.1 has some security flaws. See https://www.immuniweb.com/mobile/?id=b2fxy6Xo

**Describe the solution you'd like**
The app shouldn't have any "risks"

**Additional context**
Immuniweb can test Apps automatically and display any founded problems:
![Framapic Image](https://framapic.org/wju3ED2xzNfF/ZgaDr8DsX8TK.png)
Clicking on details show more info and provide solutions

**Comment by beerisgood** [comment]
@flocke 
Maybe this issue can help you: https://github.com/Kunzisoft/KeePassDX/issues/616

**Comment by flocke** [comment]
Most of the issues in that report are not really related to andOTP at all:

- The logcat messages it flags as "High risk" are generated by the Android System and not andOTP
- It detects connection to Youtube even though andOTP does not has network permissions
- The weak encryption it reports is in the KeyStore backend, which I eventually hope to phase out anyways
