### ISSUE TITLE
Samsung Galaxy Watch Support

### ISSUE THREAD

**Issue by Vascomax** [andOTP/andOTP#598]
Is someone interested in support for the Samsung Galaxy Watch? For myself I implemented the support via Samsung Accessory Protocol (SAP) to sync the accounts with the Galaxy Watch. In case someone else uses these watches and there is some common interest to test it, I can work on updating and testing the things to make it available to other Galaxy Watch users too.
![mainapp1](https://user-images.githubusercontent.com/65168100/87225583-83aac280-c38e-11ea-9f2b-4fdb6ecf97ae.png)

**Comment by beerisgood** [comment]
So you sync all your 2FA over Samsung cloud to your watch?
Not very secure.

**Comment by Vascomax** [comment]
I'm not sure if it will go via the cloud since in the SAP config, I can also give the option for bluetooth or wifi transfer separatly. With bluetooth it would be more local...?! Do you know more about the SAP and might help? In any case, I use the encrypted data which will be decrypted on the watch. Instead of saving a the password encrypted backup file in andOTP, I fust send that via SAP. I would also rather prefer to stay offline. Always a trade-off with convenience... So I also have the option of loading encrypted backup files on the watch, but since there is no usb port, these files need to go on the watch also via wifi. But this can be done via sdb local peer to peer, with  disconnected internet. 
I will look a bit further into SAP if I can find out more about the specifics (e.g. how exactly the data is reaching the watch)

**Comment by Vascomax** [comment]
After reaching out to Samsung dev support, I got the confirmation: when using Accessory SDK, data will not go via any cloud servers etc. It is exactly how I already assumed above: it will use direct communication according to the service profile which is defined and configured by the developer. Options are:
- Bluetooth 
- Bluetooth LE
- USB
- WiFi

Of course additional application specific end-to-end encryption makes it even more secure.

So in my case I will limit transmission to bluetooth to keep it as local as possible and using end-to-end encryption.
But due to the small niche and basically not many users, it's now not worth implementing that properly for actual distribution. Or maybe later a specific fork version with the built-in SAP support can be uploaded only to the Samsung Galaxy store for people who use the Samsung watches and their ecosystem, keeping the normal google play version unchanged...?

**Comment by victor-rds** [comment]
>
> Is someone interested in support for the Samsung Galaxy Watch? For myself I implemented the support via Samsung Accessory Protocol (SAP) to sync the accounts with the Galaxy Watch. In case someone else uses these watches and there is some common interest to test it, I can work on updating and testing the things to make it available to other Galaxy Watch users too.
>

I would love to test, I'm migrating from Authy to andOTP, and was, just now, reading the Tizen SDK documentation.

**Comment by Vascomax** [comment]
@victor-rds Sorry, I was not active on the project for a while since there seems not to be much Tizen-interest or Samsung watch users. I saw your reply just now. 
If you are still interested to test / use it, you can communicate via the Issue in my fork: (https://github.com/Vascomax/andOTP/issues/5#issue-708819343). 
Please also tell me there which Galaxy watch and Tizen version you are using, since I need to make adjustments. Tizen 4.0 and original Galaxy Watch works best at the moment.

**Comment by flocke** [comment]
Since there have been no comments and updates for a while now I will close this issue for now.

**Comment by Vascomax** [comment]
That's fine. Closed is good. There is not much audience anyway. Also Samsung is moving away from Tizen OS and their future smartwatches will have some form of updated wear OS in cooperation with google.
Just to conclude this issue, for people still using the Tizen watches and somehow got here: the fork of andOTP (with included SAP support as described above) can be downloaded from the Samsung Galaxy Store.
However there might be not much going on with Tizen anymore, as Samsung has decided to kill yet another operating system...
I might look into wear OS development as soon as these new watches with that updated unified wearable platform prove they can keep up regarding performance and battery life.
