### ISSUE TITLE
[Thumbnail] Mintos

### ISSUE THREAD

**Issue by grandeljay** [andOTP/andOTP#601]
**Name**: mintos
**Name (alternative)**: Mintos, Mintos Marketplace, AS Mintos Marketplace (the logo is lowercase yet all text references are with a capital first letter)
**Website**: https://www.mintos.com
**Link to SVG or EPS image**: https://treescloud.online/s/QRXMgg9w5Yf8W8q (this link will expire on 31st Dec. 2020). This is a  a SVG version I quickly made by tracing the actual logo, it's not looking too good so please only use this if you have to. Use [real logo](https://eu-browse.startpage.com/av/anon-image?piurl=https%3A%2F%2Fwww.mintos.com%2Fmintos-logo-250x250.png&sp=1595090532Tc54182f46380f2f438b0d329c439e65b77852ab2f46510475b9c0c494dcfcc56) (non vector) if possible.

**Comment by ziegenberg** [comment]
The provided vector version is not really usable, as it's visibly distorted.

On the [media center site](https://www.mintos.com/en/about-us/media-center/) they do not provide vector versions, only rasterized png.
@grandeljay maybe you could write them and ask for an vector version for andOTP?

**Comment by grandeljay** [comment]
Alright, I've sent a request and since I was at it I also asked about the capitalisation bit "mintos" or "Mintos".

**Comment by ziegenberg** [comment]
Thank you very much for contacting Mintos, hopefully they answer soon. Recreating the svg would be the last resort.

**Comment by grandeljay** [comment]
Still no reply, I just sent a follow up e-mail asking if I can expect a reply for my original request.

**Comment by ziegenberg** [comment]
thanks for the update!

**Comment by grandeljay** [comment]
I also haven't received a reply for my second email so I have tried contacting mintos directly via live chat and was told to expect a reply regarding the vector logo. If I don't by Monday (24.08.2020) I should contact them again :confounded: 

I also asked about the capitalisation again and was told that "we usually use capital M" which I still find confusing since the logo is lowercase but I guess they're not sure themselves yet.

**Comment by grandeljay** [comment]
I give up, this is not worth the hassle for me.

**Comment by grandeljay** [comment]
I still received a reply though. Here is the official vector logo: https://treescloud.online/s/T74s6zJ2fEH2Gq5.

**Comment by ziegenberg** [comment]
Yay! 🎉
