### ISSUE TITLE
[Thumbnail] Twitch.tv

### ISSUE THREAD

**Issue by walent021** [andOTP/andOTP#603]
Please fill in **all the information below** to help speed up the process!

**Name**: Twitch
**Website**: twitch.tv
**Link to SVG or EPS image**: https://seeklogo.com/vector-logo/274042/twitch

**Comment by flocke** [comment]
Already included: 
![Screenshot_20200724-173520](https://user-images.githubusercontent.com/76665/88408927-879a0400-cdd4-11ea-9b0f-8d288dd05a37.png)
