### ISSUE TITLE
[Thumbnail] Electronic Arts

### ISSUE THREAD

**Issue by walent021** [andOTP/andOTP#604]
Please fill in **all the information below** to help speed up the process!

**Name**: Electronic Arts 
**Website**: https://myaccount.ea.com/
**Link to SVG or EPS image**: https://commons.wikimedia.org/wiki/File:EA-Logo.svg

**Comment by flocke** [comment]
Already included: 
![Screenshot_20200724-173552](https://user-images.githubusercontent.com/76665/88408902-78b35180-cdd4-11ea-9544-94da532025ab.png)
