### ISSUE TITLE
[Thumbnail] Wordfence

### ISSUE THREAD

**Issue by walent021** [andOTP/andOTP#605]
Please fill in **all the information below** to help speed up the process!

**Name**: Wordfence
**Website**: https://www.wordfence.com/
**Link to SVG or EPS image**: https://findlogovector.com/wordfence-logo-vector-svg/

**Comment by ziegenberg** [comment]
I'll use the original logo from their site: https://www.wordfence.com/wp-content/themes/wordfence/img/logo-wordfence.svg
