### ISSUE TITLE
[Thumbnail] Epic Games

### ISSUE THREAD

**Issue by walent021** [andOTP/andOTP#606]
Please fill in **all the information below** to help speed up the process!

**Name**: Epic Games
**Website**: epicgames.com 
**Link to SVG or EPS image**: https://sr.wikipedia.org/wiki/Epic_Games#/media/%D0%94%D0%B0%D1%82%D0%BE%D1%82%D0%B5%D0%BA%D0%B0:Epic_Games_logo.svg

**Comment by flocke** [comment]
Already included: ![Screenshot_20200724-173532](https://user-images.githubusercontent.com/76665/88408769-4c97d080-cdd4-11ea-933f-0337e70250f8.png)
