### ISSUE TITLE
[Thumbnail] Noyb

### ISSUE THREAD

**Issue by thgoebel** [andOTP/andOTP#609]
Please fill in **all the information below** to help speed up the process!

**Name**: Noyb
**Website**: https://noyb.eu/en
**Link to SVG or EPS image**: ~https://polybox.ethz.ch/index.php/s/7hUMRMFaif47oCG~ https://polybox.ethz.ch/index.php/s/DfJA7b4olOj9ewl

**Comment by beerisgood** [comment]
I'm confused. Did they support 2FA?
If not I don't know why adding their icon make sense.

**Comment by thgoebel** [comment]
They didn't initially, but they do now.
They still send you a login code via e-mail (instead of a password), but you can enable TOTP on top of that.

**Comment by ziegenberg** [comment]
@thgoebel The provided log is not accessible. I get a "404 Not Found"

**Comment by thgoebel** [comment]
The share expired, sorry about that. I've updated it.

**Comment by ziegenberg** [comment]
I used the svg from their homepage.
