### ISSUE TITLE
[Thumbnail] cyon

### ISSUE THREAD

**Issue by zedpelin** [andOTP/andOTP#610]
cyon is one of the largest hosting providers in Switzerland.

**Name**: cyon
**Website**: https://www.cyon.ch/ or rather https://my.cyon.ch for 2FA
**Link to SVG or EPS image**: https://www.cyon.ch/files/assets/cyon-logo.svg

**Comment by thgoebel** [comment]
Is there a square one (like cyon's favicon)? That would fit better in andOTP.

**Comment by zedpelin** [comment]
I've just created a SVG version of the favicon. Hope that works better: https://www.cyon.ch/files/assets/cyon-logo-wings.svg

**Comment by ziegenberg** [comment]
@zedpelin looks good! I'll add this to PR #608 and if @flocke merges it you will see it in the next release.
