### ISSUE TITLE
[Thumbnail] QNAP

### ISSUE THREAD

**Issue by r4nd0m123** [andOTP/andOTP#615]
Please consider adding a thumbnail for QNAP.

**Name**: QNAP
**Website**: https://www.qnap.com
**Link to SVG or EPS image**:
https://www.qnap.com/assets/img/home/qnap-logo-black.svg

**Comment by ziegenberg** [comment]
I'll just use the blue and red colors from the favicon with the "Q" from the logo, because the provided logo in its entirety is not even remotely square.
