### ISSUE TITLE
[Thumbnail] SelfWealth

### ISSUE THREAD

**Issue by r4nd0m123** [andOTP/andOTP#618]
Please consider adding a thumbnail for SelfWealth.

**Name**: Selfwealth
**Website**: https://www.selfwealth.com.au
**Link to SVG or EPS image**: https://www.selfwealth.com.au/assets/themes/self-wealth/library/images/sw-logo.svg

**Comment by ziegenberg** [comment]
This could become problematic because the logo is not even remotely square. And suggestion, @r4nd0m123?

**Comment by techvanity** [comment]
Here is the square sized logo: https://svgshare.com/i/PTf.svg

I created it manually by making it similar to their [favicon](https://www.selfwealth.com.au/assets/themes/self-wealth/library/images/icons/apple-touch-icon.png). Hope that helps.

**Comment by r4nd0m123** [comment]
> Here is the square sized logo: https://svgshare.com/i/PTf.svg
> 
> I created it manually by making it similar to their [favicon](https://www.selfwealth.com.au/assets/themes/self-wealth/library/images/icons/apple-touch-icon.png). Hope that helps.

Awesome! Thank you.

**Comment by techvanity** [comment]
No further movement on this issue. Is the supplied icon not suitable?

**Comment by ziegenberg** [comment]
Just not enough spare time to work on this issue. I'll try to look into it this week.
