### ISSUE TITLE
[Thumbnail] G2A

### ISSUE THREAD

**Issue by r4nd0m123** [andOTP/andOTP#619]
Please consider adding a thumbnail for G2A.

**Name**: G2A
**Website**: https://www.g2a.com
**Link to SVG or EPS image**: https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Logo_g2a_icon.svg/1000px-Logo_g2a_icon.svg.png

**Comment by ziegenberg** [comment]
I'll use the original from: https://pay.g2a.com/img/svg/logo_g2a_icon.svg
