### ISSUE TITLE
[Thumbnail] Boxcryptor

### ISSUE THREAD

**Issue by stbxxl** [andOTP/andOTP#628]
Please fill in **all the information below** to help speed up the process!

**Name**: Boxcryptor
**Website**: https://www.boxcryptor.com/
**Link to SVG or EPS image**: https://icon-icons.com/icon/boxcryptor/146212 
**Direct Link to SVG file**: https://icon-icons.com/downloadimage.php?id=146212&root=2407/SVG/&file=boxcryptor_icon_146212.svg

**Comment by ziegenberg** [comment]
The provided svg was converted not very well from a rasterized image to a vector graphic. I'll look for something better.

**Comment by techvanity** [comment]
A vector svg is here, although needs a bit of manual editing to change the color:
https://static.boxcryptor.com/images/website/safari_pinned_tab.svg

**Comment by ziegenberg** [comment]
Ah, that's perfect
