### ISSUE TITLE
[Thumbnail] Prey

### ISSUE THREAD

**Issue by stbxxl** [andOTP/andOTP#630]
Please fill in **all the information below** to help speed up the process!

**Name**: Prey
**Website**: https://preyproject.com/
**Link to SVG or EPS image**: https://icon-icons.com/icon/prey/146113
**Direct link to SVG file**: https://icon-icons.com/downloadimage.php?id=146113&root=2407/SVG/&file=prey_icon_146113.svg

**Comment by ziegenberg** [comment]
This was added in commit d1ed312d0fdfe4c597f224ef2fddb43655d59613 with PR #557 and is available since 0.7.1 in the app.
