### ISSUE TITLE
Move database loading/file reading off of the main thread

### ISSUE THREAD

**Issue by jsoberg** [andOTP/andOTP#635]
**Is your feature request related to a problem? Please describe.**
While implementing a fix for another issue, I noticed that database loading appears to always happen on the main thread (e.g. `loadEntries()` in the `EntriesCardAdapter`). This is generally a bad practice, and the UI lag may be noticeable on slower devices. I use a Samsung S9 in my everyday usage and haven't noticed it on that device, however I can imagine that on slower/older devices the lag may be more noticeable.

**Describe the solution you'd like**
Ideally, we could offload database loading and any file parsing onto a background thread. Perhaps we could add a loading progress view (where applicable) while the background work completes.

**Additional context**
I looked at usages of `DatabaseHelper.loadDatabase` to find where this was happening, though I believe this may be happening in other places. Adding a quick `Application` impl for the app with StrictMode thread policy logging enabled can help root out any instances.

**Comment by jsoberg** [comment]
Hey @flocke, I was thinking about this again today as I got a new phone and the `AuthenticateActivity` seems to freeze for 2+ seconds when authenticating (not exactly sure why it's noticeable on a newer device and wasn't on my older device). I might put up a PR that launches an `ASyncTask` to do this work and provide UI feedback while it's happening, maybe as an initial test for what it might look like to offload some of this work to other threads. If you don't like it you can just reject it and we can discuss more about a possible service implementation. 

My only thought against a service is that most of these tasks seem to be short (i.e. authentication, loading entries, maybe some settings, etc) so adding a persistent notification might interrupt users more than it's worth. Another option is to use non-persistent `IntentService`s and the like, but connecting those back to UI components on config changes can be more annoying than using other threading methods (at least in my experience). I often end up using `RxJava` for cases like this, would you be against using that within the app? It can be a bit of a bear to learn if you're not already familiar.

**Comment by jsoberg** [comment]
Background task for authentication is up and running on my fork's branch (#635-MoveAuthenticationToBackground). Seems to be working fine, but I'd like to add more UI feedback while the task is running before creating a PR here, maybe animating the unlock button into a circular indeterminate progress bar (as-is I'm just disabling the password input/unlock button).

**Comment by jsoberg** [comment]
I was profiling the performance of authentication, and it seems that the bulk of the execution time comes from the number of iterations that are chosen for PBKDF2. It looks like we currently choose a number of iterations between 140,000 to 160,000; is there a specification that recommends this high a # of iterations for this use case? The best reference I could find was a NIST document that states a minimum of 10,000 iterations (https://pages.nist.gov/800-63-3/sp800-63b.html#sec5) which is much less than the current min/max that we have set. 

Just wanted to confirm that we want the iteration count to be this high, since it seems to cause a measurable overhead for authentication purposes (10k-20k iterations is almost instant to the user, where the current spec takes 2-3 seconds to run).

**Comment by flocke** [comment]
Fixed in #738
