### ISSUE TITLE
[Thumbnail] myGov Australia

### ISSUE THREAD

**Issue by techvanity** [andOTP/andOTP#643]
Please add thumbnail for myGov. Thanks

**Name**: myGov Australia
**Website**: https://my.gov.au/
**Link to SVG or EPS image**: https://my.gov.au/mygov/content/mgv2/icons/favicon.svg

**Comment by r4nd0m123** [comment]
I thought they only supported the myGov Code Generator app?

**Comment by techvanity** [comment]
Well, officially they only support their own code generator. But people have found a way to [grab the totp secrets](https://github.com/abrasive/mygov-totp-enroll).
