### ISSUE TITLE
[Thumbnail] Fidelity Investments

### ISSUE THREAD

**Issue by raidenii** [andOTP/andOTP#645]
Please fill in **all the information below** to help speed up the process!

**Name**: Fidelity Investments
**Website**: https://www.fidelity.com/
**Link to SVG or EPS image**: https://www.brandeps.com/logo-download/F/Fidelity-Investments-01.eps

**Comment by ziegenberg** [comment]
The webpage of fidelity says:

> "With 2-factor authentication, an extra layer of security is added to your account to prevent someone from logging in, even if they have your password. This extra security measure requires you to verify your identity using a randomized 6-digit code we’ll send you each time you attempt to log in.
> You can choose to receive your security code through one of two ways: by text or voice call to your mobile phone (or an alternate phone number)."

So I guess we do not need this logo as you cannot use the app for generating such TOTP code for 2FA?

**Comment by raidenii** [comment]
You could and I'm using it - it uses Symantec VIP just like Paypal.

**Comment by ziegenberg** [comment]
Well, in that case I'll add an PR to include their logo.

**Comment by raidenii** [comment]
Much appreciated.
