### ISSUE TITLE
Don't align codes strictly with the system clock to improve usability

### ISSUE THREAD

**Issue by wischi-chr** [andOTP/andOTP#652]
Currently the code shown is strictly aligned with the system clock. When one clicks a token (for it to be shown) it happens to me a lot that I see the token for a very brief period of time (less than a few seconds) before a new code is shown.

A way better solution would be to use the click to get the current time, determine how long the code would be valid and if it's less than half of the period just show the next code, plus always show the code for the duration of the period. Another click would just repeat that step and reset the timer. This way a code will always be shown for 30s (or the set period)

Because of they way how OTPs work and the fact that clocks aren't always in perfect sync, servers accept those codes, even if they are slightly in the future or past according to your system clock.

**Comment by flocke** [comment]
Will be solved once #506 is implemented. Closing as we don't need 2 issues.
