### ISSUE TITLE
Jump to search when opening the app

### ISSUE THREAD

**Issue by cljoly** [andOTP/andOTP#654]
I’ve a lot of codes in andOTP and currently I’m always opening the search box straight after unlocking the app.

Ideally, it would be possible to set up the app to open with search focused and the keyboard available, so as to filter the list and get to the item looked for quicker.

**Comment by nursoda** [comment]
Just tested 0.9.0b1 – nice … but the search should not re-focus when I

1. close the keyboard and
2. open tags

Tags get somewhat unusable this way ;)
