### ISSUE TITLE
Enhancement: Add Logo for "Anydesk" (anydesk.com)

### ISSUE THREAD

**Issue by TalusUnheil** [andOTP/andOTP#655]
Hello everybody! I would love it if you could add the logo for "Anydesk" (remote desktop software). You can find the logo here: https://anydesk.com/_static/img/favicon/anydesk_icon.png

Thanks in advance!

**Comment by meiser79** [comment]
duplicate of #625

**Comment by ziegenberg** [comment]
Closed as duplicate

**Comment by ziegenberg** [comment]
Not a duplicate: Anydesk != Autodesk.

Therefore reopen.

**Comment by Schluggi** [comment]
The logo posted by @TalusUnheil is an PNG. Here is the path for the SVG: 
https://upload.wikimedia.org/wikipedia/commons/6/60/AnyDesk-logo.svg

**Comment by ziegenberg** [comment]
Finally got some time to look into this. Sorry for the delay.
