### ISSUE TITLE
Exactly what are the risks of using Android Keystore?

### ISSUE THREAD

**Issue by feederaccount** [andOTP/andOTP#656]
This is a "help wanted" issue rather than a bug report. I'm not sure how to add tags so apologies for using the blank template.

When selecting the type of authentication to use, andOTP recommends against using Android Keystore and says it can causes issues on some devices. I do not want to enter a PIN every time so I elected to use it. I have used it now for 2 weeks without issue. 

What exactly am I risking by using it? I switched to andOTP for the backup feature; I was using Google Authenticator but was afraid of losing my account and getting locked out. Is there a risk that my backups won't work? That I'll suddenly be unable to open the app and have to do a restore?

Further explanation would be useful as it would enable us to make a more informed choice.

**Comment by beerisgood** [comment]
Risk is only on weak/ insecure and outdated phones/ ROMS which doesn't support correctly Keystore which end in andOTP data loss.
If your device support Keystore and it works for you, their is nothing to worry about and it increase your security a lot.

**Comment by feederaccount** [comment]
In that case, isn't the warning message over the top? It encourages people to use the PIN even when it isn't needed for most.

**Comment by beerisgood** [comment]
In my opinion it is. Don't know how "Aegis" handle that but maximum security should be used and preferred.

**Comment by flocke** [comment]
The problem with the KeyStore bug is that, while it happens very rarely now, when it happens it causes a total data loss without any chance of recovery. So that's the reason I recommend against using it.

But there haven't been any reports about this in a while, so it might be time to change this.

**Comment by feederaccount** [comment]
@flocke this total data loss doesn't apply to those of us who frequently backup to disc though, right?

**Comment by flocke** [comment]
Exactly, you are fine if you have a backup. But a lot of people don't do regular backups, so they are screwed when the bug hits.

But the encryption backend is the next thing on my todo list after 0.8.0 is released.

**Comment by beerisgood** [comment]
> But a lot of people don't do regular backups, so they are screwed when the bug hits.

Fair but we shouldn't reduce overall security because of that. Better then make backup info/ warning popup.

**Comment by WolfganP** [comment]
> 
> 
> > But a lot of people don't do regular backups, so they are screwed when the bug hits.
> 
> Fair but we shouldn't reduce overall security because of that. Better then make backup info/ warning popup.

I agree. I think a msg/popup suggesting to perform a backup (after adding/changing some entry) is worthy as a good security practice reminder (and even better if the confirm button jumps to the setting/backup page for convenience).

**Comment by lynn-stephenson** [comment]
Aside from the rare bug, users can remove their biometrics, or disable PIN mode on their device which wipes the Key Store. (At least on my device)

As pointed out by the author, users are likely to not do regular back ups. Which is an issue with no automation for it.

When you derive an encryption key (e.g: type in your passphrase) it is never stored. If you are going to store cryptographic keys, storing it in Android's Key Store is a good idea.

But saying that Android's Key Store is more secure than deriving a cryptographic key that is again, never stored, is false.

**Comment by flocke** [comment]
Closing this, I think everything important has been said.
