### ISSUE TITLE
[Thumbnail]Bitwarden (new icon)

### ISSUE THREAD

**Issue by vachan-maker** [andOTP/andOTP#660]
Please fill in **all the information below** to help speed up the process!

**Name**: Bitwarden
**Website**: vault.bitwarden.com
**Link to SVG or EPS image**: https://raw.githubusercontent.com/bitwarden/brand/master/icons/square-128x128.png

**Comment by alexanderadam** [comment]
This icon would also be available [via SuperTinyIcons](https://github.com/edent/SuperTinyIcons#security) once [PR 398](https://github.com/andOTP/andOTP/pull/398) will be considered again.

**PS:** Apart from that, [the footprint of the asset size could be decreased by replacing some of the currently integrated icons with the tiny ones](https://github.com/andOTP/andOTP/issues/550#issuecomment-665121611).

**Comment by ShubhamVerma1811** [comment]
Here,
view-source:https://bitwarden.com/images/logo-vertical-white.svg
THe logo is white so wont be visible, change background to red to see
