### ISSUE TITLE
Use font with slashed zero to disambiguate it from the letter O

### ISSUE THREAD

**Issue by maricn** [andOTP/andOTP#665]
**Is your feature request related to a problem? Please describe.**
I've had several occasions when I wanted to retype the TOTP secret (not the code, but the secret key) from the edit dialog. For instance when transferring to a device which doesn't have a camera for the QR code. In all of those occasions I had issues recognizing 0s from Os.

**Describe the solution you'd like**
In the edit dialog for the entries, use font with slashed zero `0`.

**Describe alternatives you've considered**
Copying and sending the code via some app to the device, which only works with network access between the devices and is potentially slower for one-time use.

**Additional context**
N/A

**Comment by flocke** [comment]
Closed in #772
