### ISSUE TITLE
[Thumbnail] mail.de

### ISSUE THREAD

**Issue by meiser79** [andOTP/andOTP#669]
Please add a thumbnail for mail.de, thanks a lot in advance!

**Name**: mail.de
**Website**: https://www.mail.de
**Link to SVG or EPS image**: https://mail.de/img/logo_blackMailBlue.png?1 (Sorry, could just find a png).

**Comment by meiser79** [comment]
I tried to create a SVG based on the PNG. What do you think?

[mailde.svg.zip](https://github.com/andOTP/andOTP/files/5450342/mailde.svg.zip)

**Comment by meiser79** [comment]
@ziegenberg I provided a proposal for the mail.de icon. Could you please check and remove the "vector missing" flag? Thanks!

**Comment by ziegenberg** [comment]
You just embedded a png in the SVG, so it's still a rasterized image. The "vector missing" flag stays.

**Comment by ziegenberg** [comment]
I found a PDF on their homepage, which hade a vector version of their logo and extracted it with Inkscape: https://mail.de/dl/Mediadaten-mail.de-Aktuell.pdf
