### ISSUE TITLE
"Most recent first" option

### ISSUE THREAD

**Issue by skorokithakis** [andOTP/andOTP#67]
It would be nice if the app had an option where the most recently used entry would be shown first the next time the app was launched. That way, the entries I use more often would be shown at the top, and the ones I rarely use would slowly drop to the bottom.

**Comment by flocke** [comment]
For that I would have to save the time an Entry is used. Without the tap-to-reveal option enabled this is not really doable (no way to tell which entry you are using if you just read the token and type it manually on another device).
I will think about it, but for now you could always use drag-and-drop to put your often used entries to the top.

**Comment by skorokithakis** [comment]
You'd have to, yes. It could be a new sorting mode that is only available when tap to reveal is enabled. That seems a reasonable use to me.
