### ISSUE TITLE
[Thumbnail] Qnap NAS

### ISSUE THREAD

**Issue by HerrRuin** [andOTP/andOTP#675]
Please fill in **all the information below** to help speed up the process!

**Name**: Qnap NAS
**Website**: https://www.qnap.com/de-de
**Link to SVG or EPS image**: https://www.qnap.com/assets/img/home/qnap-logo-black.svg

Please add QNAP Thumbnail 

Thank you!

**Comment by ziegenberg** [comment]
This is a duplicate. Was fixed with: #615

**Comment by HerrRuin** [comment]
Thanks, but I cant find the Qnap Logo under Q :(
What is the Symbol you are using??

**Comment by ziegenberg** [comment]
It's not released yet. Will be soon-ish in version 0.8.0
