### ISSUE TITLE
Keepass export option from andOTP

### ISSUE THREAD

**Issue by codezeeker** [andOTP/andOTP#676]
---
name: Feature request
about: Looking for export to keepass format in order to use TOTP in laptops
title: Keepass exporter
labels: enhancement
assignees: flocke

---

**Is your feature request related to a problem? Please describe.**
I am using andOTP for the mobile, but sometime want it to use with desktop, a keepass export option would resolve that

**Describe the solution you'd like**
an opensource keepass like password manager export option

**Describe alternatives you've considered**
any other opensource export option also good 

**Additional context**

**Comment by codezeeker** [comment]
Hello Folks, let me know if anything needs to be changed. I would try to contribute to this feature as well.

**Comment by flocke** [comment]
We decided at the very start of the project that we don't want to implement export and import options for different formats.

But if someone wants to implement a converter to convert andOTP backups into KeePass format that should work.

**Comment by jsoberg** [comment]
Is this a plugin for KeePass? I wasn't aware that KeePass supported TOTP codes, but if that's the case I'd be willing to write a simple converter for it at some point.

**Comment by zeitwidrig** [comment]
@jsoberg Yeah, there are several plugins for adding TOTP support: https://keepass.info/plugins.html#kpotp

I'm using [KeeOTP](https://sourceforge.net/projects/keeotp/) but apparently the author has removed any traces of the code :/

**Comment by JeGr** [comment]
@zeitwidrig That one IMHO is the recommeded one at it is current, actively in development and can deal with other codes like Blizzard and Steam as well: https://github.com/KeeTrayTOTP/KeeTrayTOTP
I'd recommend switching over to that, it also is compatible to e.g. Keepass2Android and I can even use that to input TOTP codes like AndOTP (as a backup).

But as far as an exporter I don't exactly see the problem as all you need is the "secret" that you insert while setting up TOTP for an entry in Keepass. All other options are 99% the same (30s, 6 digits etc.) so all you need is the secret you see when editing an entry in AndOTP.

**Comment by flocke** [comment]
We won't be adding import and export functions for 3rd party formats.
