### ISSUE TITLE
Hide Issuer Option

### ISSUE THREAD

**Issue by necarlson** [andOTP/andOTP#678]
**Feature Request**

It would be nice to be able to hide the issuer label, or at least change the font size of it. The issuer label takes up a lot a real-estate on the cards. With so many custom icons the issuer label is not needed in most situations.

**Feature description**
Add the ability to hide and/or change the size of the issuer text.

**Comment by flocke** [comment]
You can just delete the issuer text and it will hide the separating dash automatically.

**Comment by flocke** [comment]
Implemented in #758
