### ISSUE TITLE
GitLab logo not shown for gitlab.com

### ISSUE THREAD

**Issue by mavit** [andOTP/andOTP#685]
#### General information

* **App version:** 0.8.0-play
* **App source:** Google Play
* **Android Version:** 11
* **Custom ROM:** No.

#### Expected result
**What is expected?** 
The GitLab logo is displayed on the new entry.

**What does happen instead?**
A letter "G" is shown in place of the GitLab logo.

#### Logcat
https://gist.github.com/mavit/1d425d3bcde69b78a42b5695992d272c

#### Steps to reproduce
 
- Browse to https://gitlab.com/-/profile/two_factor_auth
- Click "Enable two-factor authentication".
- Scan the QR code with andOTP.

I notice that for most entries the issuer field contains the brand name of the service, whereas here it contains the domain name, `gitlab.com`.

**Comment by flocke** [comment]
> I notice that for most entries the issuer field contains the brand name of the service, whereas here it contains the domain name, gitlab.com.

That would be the reason. The issuer has to match the name of the icon in andOTP for the automatic selection to work. You can still assign the logo manually afterwards though.

To fix this we would need aliases for the logos as already discussed a bit in #398. I am keping this issue open as a reminder for the alias implementation.
