### ISSUE TITLE
Help - quick - lost phone, have ssh access, need to get otp keys

### ISSUE THREAD

**Issue by mb300sd** [andOTP/andOTP#686]
I lost my phone tonight, but still have SSH access to it. Is there any way to download my OTP keys from it through SSH before the battery dies?

**Comment by flocke** [comment]
Which encryption method did you use? KeyStore or Password?

With the KeyStore you don't have any chance. But with the password it's doable.

You need to download the following two files:

`/data/data/org.shadowice.flocke.andotp/secrets.dat`

`/data/data/org.shadowice.flocke.andotp/shared_prefs/org.shadowice.flocke.andotp_preferences.xml`

If you got those two files you can use [this script](https://github.com/andOTP/Tools/blob/master/decrypt_database.py) to decrypt the database.

**Comment by mb300sd** [comment]
Thanks! Ended up finding the phone, but pulled those files before I did. Might be a nice entry for the wiki, although I don't know how many people keep remote access to their phones. Also handy via adb for broken screens etc.
