### ISSUE TITLE
Cannot set up backups on cloud services other than Google Drive (e.g. OneDrive, DropBox, etc)

### ISSUE THREAD

**Issue by vureau** [andOTP/andOTP#691]
#### General information

* **App version:** 0.8.0
* **App source:** Google Play
* **Android Version:** 10
* **Custom ROM:** N/A

#### Expected result
**What is expected?** 
I am trying to set up a recurring backup on OneDrive.

**What does happen instead?**
The only available options available through the systems file manager are internal storage, SD card, and Google Drive. There are no further options to link or add available cloud services like OneDrive, DropBox, etc. I have already added my Microsoft account to my android device (Settings > Accounts and backup > Accounts

#### Steps to reproduce
 
 * Backups > Backup (encrypted) > System's Files App opens

**Comment by flocke** [comment]
That's a problem with the cloud services. The apps don't properly implement all parts of the Storage Access Framework. So until they fully support granting persistent access to the folders it won't be possible to use them for automatic backups.

**Comment by dtantsur** [comment]
As a workaround some applications (e.g. AnkiDroid) allow opening "share to" menu on backup. So I click "Backup", it saves the file and immediately opens a menu from which I can choose "save to dropbox".

**Comment by flocke** [comment]
All apps that implement the necessary parts of Androids Storage Access Framework should be supported by now.
I created a separate issue to track the idea of @dtantsur to use the Share menu: #779
