### ISSUE TITLE
Allow editing digits and time for imported accounts

### ISSUE THREAD

**Issue by SuperSandro2000** [andOTP/andOTP#694]
#### General information

* **App version:** 0.8.0-play
* **App source:** Google Play
* **Android Version:** 9
* **Custom ROM:** 

#### Expected result
**What is expected?** 

That I can edit the time or digits after importing an account in case it is wrong.

**What does happen instead?**

It is greyed out.

#### Steps to reproduce
 
* Create an account
* Try to edit it

**Comment by lynn-stephenson** [comment]
I was able to reproduce this bug.
