### ISSUE TITLE
Readme.md shows bad information and you limit your app by claiming 6-digit limitation

### ISSUE THREAD

**Issue by sanawu** [andOTP/andOTP#695]
"It implements Time-based One-time Passwords (TOTP) and HMAC-Based One-Time Passwords (HOTP). Simply scan the QR code and login with the generated 6-digit code."

Sorry to say but if you're limiting this to 6 digit codes as you say in your readme, you've crippled your app

OTP is not limited to 6 digits

Please confirm you do not limit your app to 6 digits

**Comment by lynn-stephenson** [comment]
In most cases providers use 6 digits. However you absolutely can use 8 digits, but it does not mean providers support it. See advanced settings when you edit TOTP entries.

The README may not reflect the application 100%, but you can submit a PR to fix this. :)

**Comment by sanawu** [comment]
> In most cases providers use 6 digits. However you absolutely can use 8 digits, but it does not mean providers support it. See advanced settings when you edit TOTP entries.
> 
> The README may not reflect the application 100%, but you can submit a PR to fix this. :)

The readme should be updated then, there should be no arbritary limit on this, providers use as many as they decide, some use more

**Comment by sanawu** [comment]
> In most cases providers use 6 digits. However you absolutely can use 8 digits, but it does not mean providers support it. See advanced settings when you edit TOTP entries.
> 
> The README may not reflect the application 100%, but you can submit a PR to fix this. :)

**Comment by lynn-stephenson** [comment]
> The readme should be updated then, there should be no arbritary limit on this, providers use as many as they decide, some use more

There is a limit, the RFC for TOTP specifies inclusively between 6, and 8 digits.

It was designed for average users, so it has to be convenient. Anymore than 8 digits and you're gaining negligible security.

The probability of finding the correct correct sequence of digits 1 in a 1,000,000 (million). Over a period of 30 seconds, that is a lot of authentication attempts, and most services have rate limiting in place so this is not feasible.

The chances of users' accounts being compromised is greatly reduced, for sacrificing a little bit of inconvience to the user.

Providers get to say how many digits they will do, and what algorithm. Which is (most of the time) 6 digits, with HMAC-SHA1.

Do not complain about "AndOTP not supporting 8+ digits" when you should be taking that complaint to providers, and directing it at them.

Yes the README should be updated, and I am sure it will be.

If you want the most security, you are goung to have to look elsewhere. Not at TOTP. Try a hardware security key.

**Comment by sanawu** [comment]
> > The readme should be updated then, there should be no arbritary limit on this, providers use as many as they decide, some use more
> 
> There is a limit, the RFC for TOTP specifies inclusively between 6, and 8 digits.
> 
> It was designed for average users, so it has to be convenient. Anymore than 8 digits and you're gaining negligible security.
> 
> The probability of finding the correct correct sequence of 6 digits is 1 in a 1,000,000 (million). Over a period of 30 seconds, that is a lot of authentication attempts, and most services have rate limiting in place so this is not feasible.
> 
> The chances of users' accounts being compromised is greatly reduced, for sacrificing a little bit of inconvience to the user.
> 
> Providers get to say how many digits they will do, and what algorithm. Which is (most of the time) 6 digits, with HMAC-SHA1.
> 
> Do not complain about "AndOTP not supporting 8+ digits" when you should be taking that complaint to providers, and directing it at them.
> 
> Yes the README should be updated, and I am sure it will be.
> 
> If you want the most security, you are going to have to look elsewhere. Not at TOTP. Try a hardware security key.

Care to point out the 6 and 8 digit limit in https://tools.ietf.org/html/rfc6238 ?

**Comment by lynn-stephenson** [comment]
Sorry, it is not in the TOTP RFC, but in the HOTP RFC. It MUST be at least 6 digits, and possibly 7, or 8.

**Comment by sanawu** [comment]
> Sorry, it is not in the TOTP RFC, but in the HOTP RFC. It MUST be at least 6 digits, and possibly 7, or 8.

a wide out of sync time step will greatly reduce the search space (see previous comment) would it not? so that 1 million (assuming 6 digit) becomes greatly a reduced search space

**Comment by lynn-stephenson** [comment]
Again, that is only feasible if there is a large amount (3+) of steps, and there is no rate limiting.

A lot of services only do two steps (current, and previous), and there is generally rate limiting.

**Comment by sanawu** [comment]
> Again, that is only feasible if there is a large amount (3+) of steps, and there is no rate limiting.
> 
> A lot of services only do two steps (current, and previous), and there is generally rate limiting.

2 steps cuts the search space in half, that's also a very dramatic reduction in difficulty, 1 million becomes half a million, that's not small reduction
