### ISSUE TITLE
Unable to import Google Authenticator accounts to andOTP

### ISSUE THREAD

**Issue by engineer22** [andOTP/andOTP#703]
I'm trying to import all my Authenticator accounts to andOTP, but scanning the QR code results to 'invalid barcode'.

What can be done to mass import all the accounts from one app to another?

**INFO**:
- Android 10
- non rooted device

**Comment by flocke** [comment]
The QR code that Google Authenticator generates does not use a standard format, so andOTP does not support it for now. Here are some options for migration: https://github.com/andOTP/andOTP/wiki/Migration

**Comment by engineer22** [comment]
Thank you @flocke, I will use that.

**Comment by odinho** [comment]
Came to create this issue.

Maybe it could just detect what it is, and say what you said here in the mean time? Until it is supported?
