### ISSUE TITLE
Authentification for using the app & for encrypting backups should be separate

### ISSUE THREAD

**Issue by RiseT** [andOTP/andOTP#705]
**Is your feature request related to a problem? Please describe.**
andOTP seems like an excellent 2FA solution. Trouble is, there's one single thing that prevents me from using it the way I'd like to, which unfortunately means I cannot use it at all. This is about authentification and backups. I'd like to store my backup in an automated fashion on Google Drive, i. e. in the cloud (I know, some people don't want to store their backups in the cloud, and that's fine, but I'd like to). Because it's the cloud, I want to use a very strong password for the backup file's encryption (like 90 random characters).
At the same time, I don't want to enter such a long and complex password each and every time I open the app. The app should open with either no password at all or via fingerprint.

**Describe the solution you'd like**
The authentification for the local database and the one for (automatic, in this case remote) backups should get separated, i. e. it should be independent of each other. Ideally, I'd enter my strong password used for encrypting the backup only once, when initially setting up the app or setting up automatic backups (and of course in case I'd like to restore the backup). In order to open the app and its database, i. e. in daily use, I should be able to choose no authentification, a shorter PIN or password, my fingerprint etc (preferably using Android's KeyStore).

**Comment by flocke** [comment]
That is already the case. The backup encryption has absolutely nothing to do with the password / PIN you use to unlock the app. You can set any password for the backups in the settings, even when using no authentication at all.
