### ISSUE TITLE
[Thumbnail] Terraform

### ISSUE THREAD

**Issue by endorama** [andOTP/andOTP#706]
**Name**: Terraform
**Website**: https://www.terraform.io
**Link to SVG or EPS image**: I wasn't able to find the logo in SVG and square format, so I created the SVG [terraform-square.svg.zip](https://github.com/andOTP/andOTP/files/5673068/terraform-square.svg.zip). The square format is suggested by HashiCorp for usage in square contexts [here](https://www.terraform.io/logos.html#square-logo)

Terraform is an Infrastructure as Code provisioning tool and has a hosted online version called Terraform Cloud, which supports 2FA.

I may try giving this a go (following along https://github.com/andOTP/andOTP/pull/281/files), but I've no experience with Android development nor I have the proper environment setup.

Thanks!

**Comment by ziegenberg** [comment]
If you'd like to provide a pull request, you will need at least [Android Studio](https://developer.android.com/studio) and then have a look at the [Ressource Manager](https://developer.android.com/studio/write/resource-manager). Importing an SVG is pretty straight forward.

HashiCorp provides logos for download: https://www.hashicorp.com/brand#terraform.
