### ISSUE TITLE
Please enable menu font sizes according to system accessibility settings (or manual settings)

### ISSUE THREAD

**Issue by bungabunga** [andOTP/andOTP#71]
#### General information

* **App version:*0.3.0.*
* **App source:*Google Play*
* **Android Version:*7.1.1.*
* **Custom ROM:*rooted stock*

#### Expected result
**What is expected?** 
Fonts in menu should be the size according to system accessibility settings, or at least manual (app) settings. At the moment you can only set the label font sizes (that was solved in Issue  #18) not the font sizes in menus.

**What does happen instead?**
Menu fonts are to small for people with sight problems.

**Comment by flocke** [comment]
Which menu are you talking about, the "main menu" in the top right corner of the main activity or the one for each entry?

**Comment by bungabunga** [comment]
I'm talking about all parts except from those that can already be manually set. So: the menu on the left, the menu on the top right, including the (most important) backup, settings and about submenus.

**Comment by flocke** [comment]
OK, I will have to look into how I can get it to honor the Accessibility settings. I almost never specify a font size myself but use the defaults from Android, I thought this would automatically honor those settings.

**Comment by bungabunga** [comment]
Yeah, me neither, most apps automagically set the font to what you've set in accessibility setings (small, default, large or largest). There's the same preference also in Display menu on my device (Sony Xperia XZ).

**Comment by flocke** [comment]
I just tested it and on my phone almost everything is scaled with the font size set in the Accessibility settings. Only the labels and the Tags are not (yet) scaled correctly.
This seems to be a problem with your phone. I'm gonna try the app on my girlfriends phone (Sony Xperia Z5 Compact) next weekend to see if it something specific to Sony.

**Comment by flocke** [comment]
**Help wanted**:
It would be nice if some other users could test scaling the font size in the Accessibility settings and report back if it works with andOTP.

**Comment by bungabunga** [comment]
I also checked with my old phone, Xperia Z3c, and it was the same. Will also check with my son's phone in a few days, but it's also a Sony device.

**Comment by bungabunga** [comment]
UPDATE: I just upgraded my device to Android Oreo and the font sizes now get changed according to accessibility setings! :) I don't want to close this issue, since it's still present on previous versions of Android (at least on Sony devices).

**Comment by flocke** [comment]
@bungabunga Alright I will check it out on versions below Oreo on my second device as soon as it gets back from repairs.

**Comment by MaDill** [comment]
I checked it on my Lenovo Tab4 8 Plus with Android 7.1 and the menu and nearly all other text stay in the same size. Other apps change the font size.

**Comment by flocke** [comment]
You are right, I just checked on my new phone with Android 7.1.2 and it doesn't work.
I'll have to look into how to make it work on versions below Oreo.

**Comment by flocke** [comment]
I can't seem to figure out what the problem is on Android versions below Oreo.
If someone knows how to make this work please tell me.

**Comment by flocke** [comment]
After a while of trial and error I still can't seem to figure out what the problem is ...
Any help is appreciated ...
