### ISSUE TITLE
Build in Android Studio fails with error that Base32 class is not found

### ISSUE THREAD

**Issue by CodingSpiderFox** [andOTP/andOTP#713]
Hey everyone,

I just downloaded the master branch copy of this repo and loaded it into a fresh install of Android Studio on Windows.
But the app can't compile.
I had that issue before and thought it was because of the wrong Android SDK version being installed.
So I installed version 29 but still it does not work.

The error is

```
C:\Users\user\StudioProjects\andOTP\app\src\main\java\org\shadowice\flocke\andotp\Database\Entry.java:28:
error: cannot find symbol
import org.apache.commons.codec.binary.Base32;
                                      ^
  symbol:   class Base32
  location: package org.apache.commons.codec.binary
```

I just can't remember how I fixed it last time.
Any hints?

**Comment by ziegenberg** [comment]
Try the following:

Run `gradle build --refresh-dependencies` at the project root should download all dependencies again. It might take a while.

You can also find this in the Android Studio UI:
1. Open Menu _View > Tool Windows > Gradle_
2. In the Gradle Tool Window select _andOTP_ in the project root. It has a little elephant in front of it.
3. In the Gradle Tool Window click the _Execute Gradle Task_ (button with the elephant)
4. Run the command `gradle build --refresh-dependencies`

**Comment by ziegenberg** [comment]
Hi @CodingSpiderFox, was your problem solved?

**Comment by CodingSpiderFox** [comment]
yes but I used another way: Install it on Linux ... everything works better there

**Comment by ziegenberg** [comment]
I wouldn't go as far as saying everything works better on Linux, but some things do for sure. :)

Nice to hear that your problem got solved!
