### ISSUE TITLE
[Thumbnail] peeringdb.com

### ISSUE THREAD

**Issue by herbetom** [andOTP/andOTP#715]
Please fill in **all the information below** to help speed up the process!

**Name**: PeeringDB
**Website**: https://www.peeringdb.com/
**Link to SVG or EPS image**: I'm working on it: https://github.com/peeringdb/peeringdb/issues/911

**Comment by ghankins** [comment]
[pdb-logo-square-coloured.svg.zip](https://github.com/andOTP/andOTP/files/5761918/pdb-logo-square-coloured.svg.zip)

Will this SVG work?  I had to zip it because I can't upload an SVG image.

**Comment by ziegenberg** [comment]
Gradients can be a bit challenging with android and vector drawables. Android uses an svg feature subset for internal representation.

**Comment by ziegenberg** [comment]
seems like it worked: 8810e14.

**Comment by herbetom** [comment]
@ghankins Thanks for providing the File!

I had some Issues with the SVG as the Darker Rectangles were at the wrong position in Inkscape and Affinity Designer. It was easy to fix but I'm wondering if you, @ziegenberg also had those? 

I could provide the fixed Version which worked for me.

**Comment by ziegenberg** [comment]
I used the provided SVG from @ghankins. If this had an error, I'd need to fix my PR. Please advise. This is not a problem; I just need to know.

**Comment by herbetom** [comment]
To me the left was how it looked in Inkscape (the Darker Parts are missing), the Middle is Affinity Designer and the right is the fixed Version. 

I attached the fixed version. To me that file seemed to work in Inkscape, Affinity Designer, Chromium and Firefox.

![image](https://user-images.githubusercontent.com/15121114/103490234-b9e76d00-4e1a-11eb-9beb-4ab080aefcbb.png)

[pdb-logo-square-coloured.zip](https://github.com/andOTP/andOTP/files/5762366/pdb-logo-square-coloured.zip)

**Comment by ziegenberg** [comment]
This is how it looks like in Android Studio, so I guess we are good then. No worries about the dark background, that's from the dark mode in Android Studio.


![studio64_OPINNxQzYj](https://user-images.githubusercontent.com/856916/103492453-37b37480-4e2b-11eb-9dc7-313e1011eadf.png)

**Comment by herbetom** [comment]
Okay, thank you all for the fast realization!

**Comment by ghankins** [comment]
Thank you all for adding PeeringDB!

**Comment by ziegenberg** [comment]
Well, technically it's not added yet. It's just a PR. Wait with your praises till a new version of andOTP is released... :) It might take a few days.
