### ISSUE TITLE
[Thumbnail] NextDNS

### ISSUE THREAD

**Issue by beerisgood** [andOTP/andOTP#717]
Please fill in **all the information below** to help speed up the process!

**Name**: NextDNS
**Website**: https://nextdns.io & https://github.com/nextdns
**Link to SVG or EPS image**: (not SVG or EPS but high quality and official) https://avatars3.githubusercontent.com/u/48380765

**Comment by ziegenberg** [comment]
A vector version would be required.

**Comment by beerisgood** [comment]
Done:
[NextDNS.zip](https://github.com/andOTP/andOTP/files/5762175/NextDNS.zip)

**Comment by ziegenberg** [comment]
This looks promising! 👍🏻
