### ISSUE TITLE
[Thumbnail] Sourcehut

### ISSUE THREAD

**Issue by daeluk** [andOTP/andOTP#724]
Please fill in **all the information below** to help speed up the process!

**Name**: Sourcehut
**Website**: https://sr.ht/ or https://sourcehut.org/
**Link to SVG or EPS image**:
https://git.sr.ht/~sircmpwn/sourcehut.org/blob/master/logo.svg

**Comment by ziegenberg** [comment]
@daeluk The sourcehut logo uses fancy drop shadows, which android does not know how to convert to a vector drawable. Please advise if it's ok to use the logo without the drop shadows.

**Comment by daeluk** [comment]
I don't really feel like I have the authority to comment on that.
I'm in no way affiliated with sourcehut. I am just a happy user (and honestly just like the logo).
In a pinch I'd say that's totally acceptable, though.

I believe it's [licensed](https://git.sr.ht/~sircmpwn/sourcehut.org/tree/master/item/LICENSE) permissively, allowing modifications as well.

If you'd like I could try to contact sourcehut themselves and refer them to this thread.

**Comment by krisu5** [comment]
Logo at the website banner doesn't use any drop shadows though... Just simple circle.

[sourcehut logo.zip](https://github.com/andOTP/andOTP/files/6407726/sourcehut.logo.zip)
