### ISSUE TITLE
[Thumbnail] netcup

### ISSUE THREAD

**Issue by a5a351e7** [andOTP/andOTP#726]
Please fill in **all the information below** to help speed up the process!

**Name**: netcup
**Website**: https://www.netcup.de/
**Link to SVG or EPS image**: https://www.netcup-wiki.de/images/Netcup_logos.zip
File with name 'netcup_logo.svg' in the zip file is the correct svg file.

**Comment by ziegenberg** [comment]
There exists already a netcup thumbnail in the app. Should it be changed?

**Comment by a5a351e7** [comment]
Damn, I have overlooked it. Please close my report #726, it's fine like it is! :-)
