### ISSUE TITLE
Backup to Nextcloud fails

### ISSUE THREAD

**Issue by iFreilicht** [andOTP/andOTP#729]
#### General information
* **App version:** 0.8.0
* **App source:** F-Droid
* **Android Version:** 9
* **Custom ROM:** No, but the phone is a Sony Xperia, so they likely did some stuff

#### Expected result
**What is expected?** 

Nextcloud is installed on my Phone, and can be selected as a storage location inside the Android file manager.

When setting the "Default backup location" in the settings, I'm selecting Nextcloud and some folder inside of it. After this, when I select "Backup"->"Backup (encrypted)", I would expect to see the "Export to external storage successful" message.

**What does happen instead?**

I get an error message: "Failed to create backup file!".

#### What I tried

When I select any other folder on the phone or the SD card, the export works as expected.
When I select any other folder inside Nextcloud, the export still doesn't work and I get the same error message.
Other cloud apps (Google drive, One Drive) don't even show up in this dialog, so I couldn't test whether it worked with them.

I saw that #723 tracks the opposite issue, maybe they are related?

#### Logcat

I'm not at home right now and my phone isn't rooted, so no access to adb/logcat, but I can add it later if needed.

#### Steps to reproduce
 
 * Install Nextcloud and andOTP
 * Login to Nextcloud
 * Set password protection for the backup files
 * Select Nextcloud as the default backup location
 * Try to backup (encrypted)

**Comment by flocke** [comment]
That is most likely a Nextcloud problem. I might be able to work around it, but I will have to see.

**Comment by iFreilicht** [comment]
Yeah that seems like a potential cause. Is there any way for me to debug this better? I'll gladly submit a bug report on the nextcloud android repo, but I'm not exactly sure what to even call it.

**Comment by flocke** [comment]
Reopening to keep track of the usability improvements this still needs.

**Comment by flocke** [comment]
Most of the improvements are done and it works without problem with my Nextcloud account. Closing for now, we can always reopen if something still doesn't work.
