### ISSUE TITLE
[Question] Which icons should be included in andOTP?

### ISSUE THREAD

**Issue by flocke** [andOTP/andOTP#73]
Hey guys, it's time to ask for your opinion again.

@RichyHBM is currently in the process of implementing the ability to assign icons to the entries in andOTP (see #14).

We decided not to implement an option to manually select icons as this would make storage and backups very large and a lot more complicated. Instead we will be shipping a selection of pre-defined icons with andOTP which can be selected. For that reason we wanted to know:

**Which icons do you want to see shipped with andOTP?**

If you want to help even more please link an icon with your suggestion so I don't have to search every single one myself. Please only use icons that are available as vector graphics, everything else will increase the size of andOTP to much. You can head over to [this](https://github.com/gilbarbara/logos) Github repository to find a large collection of vector icons (searchable website [here](https://svgporn.com/)).

I will try to collect the suggestions periodically in this first post to give a quick overview. Icons I added to this post will be crossed out of the original post suggesting them.

**Icons to be included**

Icon | License | Comment | Included
----- | ---------- | ------------- | -----------
[Amazon](https://cdn.worldvectorlogo.com/logos/amazon-icon.svg) | | | ✅
AngelList | CC0-1.0 | | ✅
Apple | CC0-1.0 | | ✅
[BattleNet / Blizzard](https://visualpharm.com/assets/183/Battle.net-595b40b65ba036ed117d3c21.svg) | | | ✅
[Bitbucket](https://github.com/gilbarbara/logos/blob/master/logos/bitbucket.svg) | CC0-1.0 | | ✅
Bitcoin | CC0-1.0 | | ✅
Bitstamp | | | 🔶 **(no vector)**
[Bitwarden](https://ncloud.zaclys.com/index.php/s/kb74znzGX10e3Bn) | | | 🔶 **(no vector)**
Cloudflare | CC0-1.0  | | ✅
Coinbase | | | ✅
[Cozycloud](https://ncloud.zaclys.com/index.php/s/B6YH9x2caGPRyPL) | | to large | ✅
Digital Ocean | CC0-1.0 | | ✅
Discord | CC0-1.0 | | ✅
[Dropbox](https://upload.wikimedia.org/wikipedia/commons/3/3a/Dropbox_Logo_02.svg) | CC0-1.0 | | ✅
[Facebook](https://github.com/gilbarbara/logos/blob/master/logos/facebook.svg) | CC0-1.0 | | ✅
[Git](https://github.com/gilbarbara/logos/blob/master/logos/git-icon.svg) | CC0-1.0 | generic | ✅
[Github](https://github.com/gilbarbara/logos/blob/master/logos/github-icon.svg) | CC0-1.0 | | ✅
[GitLab](https://github.com/gilbarbara/logos/blob/master/logos/gitlab.svg) | CC0-1.0 | | ✅
[Google](https://github.com/gilbarbara/logos/blob/master/logos/google-icon.svg) | CC0-1.0 | | ✅
IFTTT | CC0-1.0 | | ✅
[Kickstarter](https://github.com/gilbarbara/logos/blob/master/logos/kickstarter.svg) | CC0-1.0 | | ✅
[LastPass](https://lastpass.com/press-room/) | | | ✅
Mailgun | CC0-1.0 | | ✅
[Mastodon](https://ncloud.zaclys.com/index.php/s/EMpJSov2fSIW7TF) | | too large | ✅
[Microsoft](https://github.com/gilbarbara/logos/blob/master/logos/microsoft.svg)| CC0-1.0 | only the icon | ✅
Origin | | | ✅
[Nextcloud](https://ncloud.zaclys.com/index.php/s/YBL1rJtYlDyxvPL) | | | ✅
Paypal | CC0-1.0 | | ✅
[Protonmail](https://ncloud.zaclys.com/index.php/s/UcI9pbijdxee4RQ) | | too large | ✅
[RSS-Feeds](https://de.m.wikipedia.org/wiki/RSS_(Web-Feed)#/media/Datei%3AFeed-icon.svg) | | | ✅
[Slack](https://cdn.worldvectorlogo.com/logos/slack-1.svg) | CC0-1.0 | | ✅
[Steam](https://github.com/gilbarbara/logos/blob/master/logos/steam.svg) | CC0-1.0 | | ✅
Stripe | CC0-1.0 | | ✅
Twitch | CC0-1.0 | | ✅
[Twitter](https://upload.wikimedia.org/wikipedia/en/thumb/9/9f/Twitter_bird_logo_2012.svg) | CC0-1.0 | | ✅
[WordPress](https://en.m.wikipedia.org/wiki/WordPress.com#/media/File%3AWordPress_blue_logo.svg) | CC0-1.0 | | ✅

**Icons without image (yet)**

- ArenaNet
- Hurricane Electric
- Teamviewer
- Ubisoft

**Comment by SuperVirus** [comment]
### Already existing SVG
- [Bitbucket](https://github.com/gilbarbara/logos/blob/master/logos/bitbucket.svg)
- [Kickstarter](https://github.com/gilbarbara/logos/blob/master/logos/kickstarter.svg)

### No SVG
Maybe I'll create some SVG files by myself.
- ArenaNet
- BattleNet / Blizzard
- Electronic Arts
- Hurricane Electric

**Comment by RichyHBM** [comment]
Given that andOTP doesn't support blizzard authenticator (yet) maybe that one should be lower priority

**Comment by flocke** [comment]
You can already use andOTP with Blizzard accounts, they use a default TOTP token. The only tricky thing is to get the account secret.

**Comment by RichyHBM** [comment]
Oh really? I had no idea, I always thought it was a propriety algorithm given you had to use their authenticator

**Comment by flocke** [comment]
Yeah, took me a while to figure that out as well. I will write up a howto in the wiki later. That's enough off topic for this issue ;)

**Comment by aircooledcafe** [comment]
- [Amazon](https://cdn.worldvectorlogo.com/logos/amazon-icon.svg)
- [Dropbox](https://upload.wikimedia.org/wikipedia/commons/3/3a/Dropbox_Logo_02.svg)
- [Slack](https://cdn.worldvectorlogo.com/logos/slack-1.svg)
- [Twitter](https://upload.wikimedia.org/wikipedia/en/thumb/9/9f/Twitter_bird_logo_2012.svg)
- Bitwarden
- [LastPass](https://lastpass.com/press-room/)

**Comment by aircooledcafe** [comment]
[BattleNet](https://visualpharm.com/assets/183/Battle.net-595b40b65ba036ed117d3c21.svg)

**Comment by stonerl** [comment]
[WordPress](https://en.m.wikipedia.org/wiki/WordPress.com#/media/File%3AWordPress_blue_logo.svg)
[RSS-Feeds](https://de.m.wikipedia.org/wiki/RSS_(Web-Feed)#/media/Datei%3AFeed-icon.svg)

**Comment by RichyHBM** [comment]
@stonerl I'm confused as to why you would need an RSS feed icon

**Comment by stonerl** [comment]
@RichyHBM I'm using Tiny Tiny RSS with 2FA and I assume there are other feed services that allow 2FA. This would be covered by the RSS-Feed icon IMHO.

**Comment by RichyHBM** [comment]
@stonerl Fair enough

Another site with logos https://worldvectorlogo.com/

**Comment by RichyHBM** [comment]
I may have come across a small issue with the resolution of the vectors, I had previously been using the size they were designed with with made them look crisp but when using an image as big as slack it caused an OOM exception, I have now made all vectors as small as possible but they look a little blurry.

Its probably best seen when I do the PR but it may beg the question about what the max resolution we want any 1 image to be

**Comment by RichyHBM** [comment]
Oh, I hadn't noticed that. Tried using a logo from them and it didn't keep the colors so I'm not even sure they conform to svg standards either

**Comment by Primokorn** [comment]
[svg for bitwarden](https://ncloud.zaclys.com/index.php/s/kb74znzGX10e3Bn) (creation based on the app icon)

**Comment by RichyHBM** [comment]
Some of those svg's are huge! I have grabbed the protonmail logo from their site and also have bitwarden.

Have added most of the suggested icons so far, and have gone through twofactorauth.org and added a bunch from there as well, I think that gives us a good amount of used services for now

**Comment by 5t0rmr1d3r** [comment]
How about:
Teamviewer
Ubisoft
Discord
?

**Comment by flocke** [comment]
@RichyHBM How big are we talking? At some point we have to think about some other approach ...

**Comment by RichyHBM** [comment]
Well the logos on linked by @Primokorn are at least half a mb each, all other logos I have been adding have been about a couple of KB each.

Not saying they shouldn't be added, but I don't like using conversion tools as they tend to bloat the files, would rather look for a file created specifically for vector format

**Comment by flocke** [comment]
I think 0.5 MB **per icon** is way to much. That could very quickly increase the size of andOTP which is something I would like to avoid.

**Comment by RichyHBM** [comment]
Yea, currently andOTP with all added icons is using up 3.64mb on my phone, so still very light

**Comment by Primokorn** [comment]
I had to do it on my phone. I can create the svg files with Inkscape this weekend if necessary.
What about using drawables instead of pictures? You can convert them using this tool: http://inloop.github.io/svg2android/
A few Kb only.

**Comment by flocke** [comment]
Yeah, we already convert the SVG files to Android drawables. But the format is very similar, so if the SVG is big the drawable will be as well.

**Comment by RichyHBM** [comment]
Yes sorry, that's what I have been doing (android studio has a built in converter now) but the size of the drawables has been roughly the same size as the svg's

**Comment by flocke** [comment]
@RichyHBM As the current APK on Github is already 3.1 MB I think 3.6 MB with all the icons is totally fine.

**Comment by Primokorn** [comment]
@flocke so you will also include my proposals/icons?

**Comment by RichyHBM** [comment]
@Primokorn already have bitwarden and proton mail, I can have a look for a logo for cozy and next cloud. Can't find any info on what mastodon is, can you provide a link to their sirlte or something?

**Comment by flocke** [comment]
I updated and organized the first post a little better.

**Comment by RichyHBM** [comment]
Looks good, FYI Origin is the Electronic Arts client. I assume that's what @SuperVirus meant?

**Comment by flocke** [comment]
Yeah, I assume that's what he meant. Just forgot to remove the "Electronic Arts" entry.

**Comment by RichyHBM** [comment]
Added cozy cloud, next cloud and mastodon

**Comment by RichyHBM** [comment]
Also, to add to the table, angellist, apple, bitcoin, cloudflare, digital ocean, discord, ifttt, mailgun, paypal, slack, stripe, twitch, twitter, wordpress all come from https://github.com/gilbarbara/logos and so are CC0-1.0

lastpass logo, https://lastpass.com/press-room/

**Comment by Primokorn** [comment]
@RichyHBM Thanks mate.
For the records: Mastodon is a decentralized microblogging network.

**Comment by flocke** [comment]
I'm gonna close this now since almost all requested icons are included.
I moved the list to the wiki: https://github.com/andOTP/andOTP/wiki/Thumbnails

If you got additional requests please open a new issue (but please not for every icon a separate one).

**Comment by flocke** [comment]
@RichyHBM I just found the time to write up something on how to use andOTP with Battle.net: https://github.com/andOTP/andOTP/wiki/Shared-secrets
Just in case you are still interested.

**Comment by ximmox** [comment]
bump issue as requested in Wiki, I added Evernote and suggested an alternative icon for Amazon, which is more square.

Please have a look and tell me if any other input is needed. Thanks for the wiki entry, that explains your preferred way of handling icons!

**Comment by scottwernervt** [comment]
Added request for Rackspace.

**Comment by Nyoroon** [comment]
Added request for Linode.

**Comment by scottwernervt** [comment]
Added request for Standard Notes.

**Comment by Nexion** [comment]
Added request for Localbitcoins and Tutanota.

**Comment by Rafficer** [comment]
Added request for Localmonero and updated Tutanota logo

**Comment by bluezed** [comment]
Added requests for Bitwala, BitPanda and HitBTC.

**Comment by Ardakilic** [comment]
Added request for cex.io exchance.

**Comment by KeenRivals** [comment]
Added request for Ubiquiti Networks.

**Comment by Southparkfan** [comment]
Added requests for Wikimedia Foundation and Miraheze.

**Comment by shrzer** [comment]
Added request for Sync.com

**Comment by krisu5** [comment]
Added request for Backblaze.

**Comment by froman753** [comment]
Snapchat and Mint.com

**Comment by ambux** [comment]
mailbox and INWX added

**Comment by Madh93** [comment]
Added request for Scaleway.

**Comment by aibaraiduas** [comment]
Added request for Fastmail and Gandi. Thanks.

**Comment by RichyHBM** [comment]
@aibaraiduas Gandi.net is already in a PR and should get added once that gets merged in, will see if I have time this week for all others requestsed

**Comment by dan9550** [comment]
Bumpity bump!

Adobe, Office365, & Trello

**Comment by velleto** [comment]
Added request for "Atlassian" (BitBucket parent company). Thank you.

**Comment by dan9550** [comment]
Added a couple more i even made these SVGs myself :)

Cloud Native, ConnectWise Manager, & Team Password Manager

Thanks

**Comment by PharmaceuticalCobweb** [comment]
Added a request for "Sophos" with the best SVG I could find. My work uses their VPN and requires two-factor authentication.

**Comment by RichyHBM** [comment]
A note: **We are going to focus on allowing custom thumbnails from now on rather than adding bespoke thumbnails** this will allow users to add any thumbnail to their entries without impacting the app or having to wait for a new release.

I will try my best to add the current requests

**Comment by jacek-1** [comment]
hi there, any timeline for that new feature with adding custom app icons by a user ?

**Comment by flocke** [comment]
There is no timeline yet, I am currently extremely busy so I don't really have time to spend working on andOTP.
