### ISSUE TITLE
Unable to import QR-Code from Ubiquiti (account.ui.com): "Invalid QR Code" message

### ISSUE THREAD

**Issue by marcopaganini** [andOTP/andOTP#730]
#### General information

* **App version:** 0.8.0-play
* **App source:** Google Play
* **Android Version:** 11
* **Custom ROM:** None

#### Expected result

**What is expected?** 

Scanning the QR Code should import the token into AndOTP.

**What does happen instead?**

Message saying "Invalid QR Code" and no import.

#### Logcat

https://bundias.com/logcat2.txt

#### Steps to reproduce

* Log in to account.ui.com, click on the account icon and select "Manage Account".
* Choose "Security" and then "Enable Two Factor Authentication".
* Scan the resulting QR-Code.
* AndOTP activates the camera and shows the barcode reader.
* Once pointed to the QR-Code, the barcode reader returns, but AndOTP shows an "Invalid QR Code" message.

Note:  I tried the same QR-Code on Aegis Authenticator and Google Authenticator without problems. It's a regular 6-digit/30s code.

Note #2: Importing the token by typing the secret manually works.

**Comment by hanndecl** [comment]
I just managed to import the QR-code from Ubiquity (accounts.ui.com)

**General information**
App version: 0.8.0-play
App source: Google Play
Android Version: 10
Custom ROM: None

**Comment by marcopaganini** [comment]
Interesting. Do you have a throwaway QR code from them I can test? Another option would be for me to generate a QR-code, save it and then delete it (sharing the image here). Any other ideas on how I can diagnose this?

**Comment by flocke** [comment]
Any updates on this issue?

**Comment by marcopaganini** [comment]
Is this fixed in v0.8.1? If so I could give it a try and report back.

**Comment by ziegenberg** [comment]
@marcopaganini, we would need a test image to verify it's fixed or confirm it's an actual bug.

**Comment by ziegenberg** [comment]
I just activated 2FA on accounts.ui.com and it worked for me.

**Comment by marcopaganini** [comment]
> I just activated 2FA on accounts.ui.com, and it worked for me without any issues.

I deactivated mine and tried again. No dice. I can PM you an image, if that works for you.

**Comment by ziegenberg** [comment]
@marcopaganini, if you could share a QR code, that would be helpful for testing.

**Comment by ziegenberg** [comment]
@marcopaganini you can send me the QR code to my email. It's listed in my profile

**Comment by marcopaganini** [comment]
Will send it soon. Thanks!

**Comment by ziegenberg** [comment]
@marcopaganini does every QR code work for you and this is the only one which does not? Or do you have problems with all QR codes in general? Can you save the QR code as an image and import it from file?

Importing your QR code from file worked for me.

**Comment by marcopaganini** [comment]
Interesting. How do I import from a file in the app? If I enter the data manually, it works.

**Comment by ziegenberg** [comment]
When you click the plus sign to add tokens, you are present with three options. One for scanning, one for entering details manually and the third one for scanning from an image file.

**Comment by marcopaganini** [comment]
Thanks. Just tried to load this image directly from the file and I get "Invalid QR code".

**Comment by ziegenberg** [comment]
@marcopaganini, I cannot reproduce your issue at all. Does any other QR code for any other 2FA work for you? Or is _account.ui.com_ your only trouble?

Have you tried resetting your app? You can do a backup first and restore your entries afterwards from said backup.

**Comment by marcopaganini** [comment]
@ziegenberg Everything else works ok. I have many other accounts imported via QR code without a hitch. QR codes from accounts.ui.com are the only ones that fail. If I type the data manually, the correct codes are generated.

I'll reset the app and report.

**Comment by marcopaganini** [comment]
@ziegenberg So I finally managed to do this. Took a backup, stopped the app, cleared all data. Tried to re-scan and bingo! It now works perfectly! Well, thanks for the help! I'm marking this issue as closed.
