### ISSUE TITLE
[Thumbnail] Ultimaker

### ISSUE THREAD

**Issue by hacker0uvert** [andOTP/andOTP#733]
**Name**: Ultimaker
**Website**: https://ultimaker.com
**Link to SVG or EPS image**: https://github.com/andOTP/andOTP/files/5842760/Ultimaker-logo.zip

**Comment by ziegenberg** [comment]
Without a vector image this will likely be postponed.

**Comment by ziegenberg** [comment]
The big "U" in the footer of the page is a svg. It's referenced from their central svg with all symbols: https://ultimaker.com/_nuxt/2ea34677543a20d276d790d76dddcd29.svg

**Comment by hacker0uvert** [comment]
Your last link seems to reference a 1 * 1 pixels file, I suppose it won't be  ok to use.
I just converted a png logo to eps, and compressed it (eps files can't be attached here).
You can find it under :
[Ultimaker-logo.zip](https://github.com/andOTP/andOTP/files/5842760/Ultimaker-logo.zip)

**Comment by ziegenberg** [comment]
Inside the SVG I linked to is a symbol with the id _i-ultimaker-u_ which represents the ultimaker logo. The corresponding path is `M290.1 5.5v177.2c0 12.4-2.1 24.3-6 35.4-10.7 30.2-34.6 54.1-64.8 64.8-11.1 3.9-23 6-35.4 6H113c-12.4 0-24.3-2.1-35.4-6-30.2-10.7-54.1-34.6-64.8-64.8-3.9-11.1-6-23-6-35.4V5.5h70.9v212.6h141.7V5.5h70.7z`. I will use that.
