### ISSUE TITLE
[Thumbnail] Bitwarden

### ISSUE THREAD

**Issue by gregorydk** [andOTP/andOTP#739]
Please fill in **all the information below** to help speed up the process!

**Name**: Bitwarden
**Website**: https://bitwarden.com/
**Link to SVG or EPS image**: https://github.com/bitwarden/brand/blob/master/icons/icon.svg

**Comment by thgoebel** [comment]
A Bitwarden thumbnail already exists. So I guess this issue is more about updating it to Bitwarden's new shade of blue?

**Comment by gregorydk** [comment]
> A Bitwarden thumbnail already exists. So I guess this issue is more about updating it to Bitwarden's new shade of blue?

Yes.
