### ISSUE TITLE
[Thumbnail] Migros

### ISSUE THREAD

**Issue by thgoebel** [andOTP/andOTP#743]
**Name**: Migros
**Website**: https://www.migros.ch
**Link to SVG or EPS image**: https://www.migros.ch/dam/jcr:784c2e31-9dd8-42ec-8142-e75d1abb22d9/migrosx.svg

The link contains the logo with the entire name "Migros". The favicons (that would be nice and square) are only PNGs. But I guess one can cut out the M from the SVG?

**Comment by ziegenberg** [comment]
As long as there's an SVG, everything's fine. Cutting and manipulating SVGs is tedious but possible - especially for those with clip, mask, gradients and many groups and subgroups.
