### ISSUE TITLE
Hide timeout bar in empty state

### ISSUE THREAD

**Issue by EeveesEyes** [andOTP/andOTP#745]
**Is your feature request related to a problem? Please describe.**
The timeout bar at the top of the screen has been mistaken for a loading bar by some inexperienced users. The user would wait for the app to do something and so would the app. 
(This is a finding from a usability study we made.)

**Describe the solution you'd like**
I would suggest hiding the timer when no accounts are registered in the app (in empty state).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by flocke** [comment]
Implemented  in #747
