### ISSUE TITLE
Better empty state (user education)

### ISSUE THREAD

**Issue by EeveesEyes** [andOTP/andOTP#746]
**Is your feature request related to a problem? Please describe.**
If the user is new to the whole principle of totp and doesn't know that an account needs to be added in the app, the + button is not very noticeable (despite being quite present in the UI), because the user is not familiar with the workflow. 
The problem might be summarized as incomplete user education.
(This is a finding from a usability study we made.)

**Describe the solution you'd like**
In empty-state, showing a small hint in the middle of the screen, guiding the user to the right option to scan a QR-code would speed up the process of user education. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by flocke** [comment]
Implemented in #747
