### ISSUE TITLE
[Thumbnail] Cisco

### ISSUE THREAD

**Issue by lloydsmart** [andOTP/andOTP#750]
**Name**: Cisco
**Website**: www.cisco.com
**Link to SVG or EPS image**: https://upload.wikimedia.org/wikipedia/commons/6/64/Cisco_logo.svg

**Comment by ziegenberg** [comment]
There is already a cisco logo in the app, but we could update it to the current version, which is the light blue one: https://commons.wikimedia.org/wiki/File:Cisco_logo_blue_2016.svg
