### ISSUE TITLE
[Thumbnail] Gandi

### ISSUE THREAD

**Issue by lloydsmart** [andOTP/andOTP#751]
**Name**: Gandi
**Website**: www.gandi.net
**Link to SVG or EPS image**: https://upload.wikimedia.org/wikipedia/en/c/c7/GandiSAS.svg

Would probably look better with just the logo and not the text to the side.

**Comment by ziegenberg** [comment]
This thumbnail is available for a long time already. If it's not chosen automatically, you may change it manually. Therefore I'll close this request.
