### ISSUE TITLE
[Thumbnail] HM Government (UK)

### ISSUE THREAD

**Issue by lloydsmart** [andOTP/andOTP#756]
**Name**: HM Government (UK)
**Website**: www.gov.uk
**Link to SVG or EPS image**: https://findvectorlogo.com/hm-government-vector-logo-svg/

Would look better with just the crown logo, no text underneath or blue bar at the side.

**Comment by ziegenberg** [comment]
There is already a logo for _HM Revenue & Customs_. So probably just removing the text and keeping the crown logo would be an option?

**Comment by lloydsmart** [comment]
Yeah that could work. I think the crown is slightly different in the one I linked, though.

**Comment by ziegenberg** [comment]
I've now chosen to just go with the crown, as that's the logo for the central gov.uk and many of the different login services for the Government Gateway.
