### ISSUE TITLE
[Thumbnail] PlayStation

### ISSUE THREAD

**Issue by osyu** [andOTP/andOTP#757]
Sony Entertainment Network accounts recently got TOTP, but since they're exclusively used for PlayStation services now the PS logo would probably be a better icon to add.

**Name**: PlayStation
**Website**: https://www.playstation.com
**Link to SVG or EPS image**: https://upload.wikimedia.org/wikipedia/commons/0/00/PlayStation_logo.svg

**Comment by osyu** [comment]
Also, the logo in this SVG is colored #1f1f1f but it should be #000000

**Comment by ziegenberg** [comment]
This is a duplicate of issue #690. It was added with PR #718 on January 22nd and will be available in the next release v0.9.0 which is currently available as a beta.
