### ISSUE TITLE
andOTP crashes the launcher and Settings-Apps

### ISSUE THREAD

**Issue by alsternerd** [andOTP/andOTP#76]
#### General information

* **App version:** Version 0.3.0 (11) - Added on 2017-11-28 
* **App source:** F-Droid
* **Android Version:** 6.0.1
* **Custom ROM:** KonstaKANG LineageOS 

#### Expected result
**What is expected?** 
The app installs/upgrades without crashes parts of the system or the whole system.

**What does happen instead?**
It crashes the App-Launcher and Settings -> Apps Menu.
No uninstallation possible without ADB-access.

#### Steps to reproduce
 
 * Install latest version.

I got this same issue with mastalab, but without crashing the launcher, it could be the same root here:

The problems are the Android SDK Platform 25 and 26, with 27 (revision: 1) it should work like a charm.

Sources:
https://github.com/stom79/mastalab/issues/31
What helped us figuring this out:  https://forums.bitfire.at/topic/1603/replicant-lineage-1-9-1-causing-instant-crash-and-bootloops/15

**Comment by flocke** [comment]
Alright, I'm gonna upgrade to SDK 27 for the next release.
Would you be willing to try a test build?

**Comment by alsternerd** [comment]
Yes, I whould. :) (Good thing abd exists in emergency. :))

**Comment by alsternerd** [comment]
Won't install over 0.2.8. The installation fails.

**Comment by flocke** [comment]
Yeah, it isn't signed by the same key (in fact it isn't at all, I'm not at my regular build rig).
You will have to uninstall 0.2.8 and install this one (don't forget the backup!!!). You will to have to repeat the same procedure when going back to the official builds after this test.

**Comment by alsternerd** [comment]
Ok, it worked! :)

I don't know why or what the issue is exactly with these two SDK-Versions but somehow they break it.

**Comment by flocke** [comment]
Nice, I will push the SDK update to Github.
It will be in the next release.
