### ISSUE TITLE
Multiple "tabs/profiles" support

### ISSUE THREAD

**Issue by vangyyy** [andOTP/andOTP#760]
**Is your feature request related to a problem? Please describe.**
I am currently storing duplicate tokens for some apps/websites. One for my personal account and different for work account. This makes my "feed" of tokens too long and it is quite time consuming to scroll through them and identify correct account. Especially at the start of the day at 6am before my first coffee of the day :(. 

**Describe the solution you'd like**
It would help if I could create separate tabs for related tokens (work/personal/...) and group them together. Somebody who has to manage multiple set of accounts may benefit from this greatly.

**Describe alternatives you've considered**
I am currently keeping track of my tokens by description, but the nature of having a lot of tokens (duplicates) and having to scroll through all of them makes navigation slow and frustrating.

**Comment by beerisgood** [comment]
You can use Android internal profiles to archive that

**Comment by flocke** [comment]
You could also use the tags to separate the different accounts. That is what I do to distinguish between my work and private tokens. If you set the "Tag selection behavior" in the settings to "Switch between tags" you can use the drawer on the main screen to switch between the different sets of accounts.

**Comment by vangyyy** [comment]
@flocke I didn't even notice tags, that actually works quite nicely for me. Thank you :)
