### ISSUE TITLE
Alpha version twice as slow as stable at unlocking app with PIN

### ISSUE THREAD

**Issue by ivanlewin** [andOTP/andOTP#763]
#### General information

Alpha:
* **App version:** andOTP (dev) 0.8.1-alpha1-dev
* **App source:** [Alpha release](https://cloud.shadowice.org/s/PBTiak4CXg8YH3F)

Stable:
* **App version:** andOTP 0.8.0
* **App source:** Google Play

* **Android Version:** 10 QKQ1.200114.002
* **Custom ROM:** (Xiaomi, untouched) MIUI Global 12.0.3 Stable

#### Expected result
**What is expected?**
Alpha version being faster when unlocking the app than stable version

**What does happen instead?**
Alpha release takes about twice as long to unlock as stable version

#### Logcat
[Alpha](https://gist.github.com/ivanlewin/b1ab9b3630749f7652a693688027d058)
[Stable](https://gist.github.com/ivanlewin/13e69a557d8301535c4eeb747992c309)

#### Steps to reproduce
 1. Have a PIN set as unlock method
 2. Open the app
 2. Unlock

**Comment by flocke** [comment]
This is most likely due to the fact that the alpha version is a debug build while the stable versions are release builds.
I will close this for now, if it still happens in the official beta (on Google Play or F-Droid) please reopen it.
