### ISSUE TITLE
[Thumbnail] tresorit

### ISSUE THREAD

**Issue by kgurr** [andOTP/andOTP#764]
**Name**: tresorit
**Website**: https://tresorit.com
**Link to SVG or EPS image**: ?

![tresorit-logo-300x300](https://user-images.githubusercontent.com/43791862/107664999-49d7cc80-6c8d-11eb-9377-fac99931e7a8.png)

**Comment by kgurr** [comment]
Tresorit ist ein sehr sicherer Cloud-Provider in der Schweiz.

**Comment by kgurr** [comment]
Perhaps one more comment when I see the long list of new icons...
Maybe a procedure like KeePass practice it makes sense:
- a set of common icons as a basis
-  then one can add his own additional icons

**Comment by ziegenberg** [comment]
The provided image is not a vector image.

**Comment by kgurr** [comment]
You are right... and I am aware of that.
But there is none available to me!?

Is this the prerequisite for the icon to be integrated?

... I could write to tresorit to see if they provide one?

**Comment by ziegenberg** [comment]
Yes, a vector image is required for integration. And you can definitely write to resorit and ask them.

**Comment by ziegenberg** [comment]
@kgurr, did you have any luck with writing to tresorit for providing a logo?

**Comment by Forage** [comment]
No need to write them, it's in their brand assets press kit: https://web.tresorit.com/l#-odCuhpGi-80FqNFPM2CkQ
I suggest going for the Tresorit_vertical_dark.svg, or take that one and remove the text underneath the icon.

**Comment by kgurr** [comment]
Thanks Forage for the hint!
The employees of Tresorit have not contacted me again, although they had announced that they would...

With the Tresorit press kit it becomes very easy: Personally I would prefer "Tresorit_vertical_light.svg"
... this graphic comes without lettering.
[Tresorit_vertical_light.zip](https://github.com/andOTP/andOTP/files/6265950/Tresorit_vertical_light.zip)

... of course you also can take "Tresorit_vertical_dark.svg" 
[Tresorit_vertical_dark.zip](https://github.com/andOTP/andOTP/files/6265982/Tresorit_vertical_dark.zip)

Most icons in andOTP are plain, without lettering.

**Comment by Forage** [comment]
The light has lettering as well, you just don't see it because it's white ;)
