### ISSUE TITLE
Broken Link on Google Play

### ISSUE THREAD

**Issue by kgurr** [andOTP/andOTP#765]
In the description of andOTP on Google Play, the link to "OTP Authenticator" by Bruno Bierbaumer is broken!

... that's not so pretty.

**Comment by ziegenberg** [comment]
I can't find any apps by Bruno Bierbaumer on Google Play anymore. Probably it's gone?

**Comment by flocke** [comment]
@ziegenberg There is a dead link to the app andOTP was originally based on in the last section of the description. Seems like it was taken down from the Play Store at some point. I will remove it  in the next update (or replace it with a link to the Github repo).

**Comment by flocke** [comment]
I replaced the dead link with one to the corresponding Github repo.
