### ISSUE TITLE
Enhancement: Add Logo for "FTX" (ftx.com)

### ISSUE THREAD

**Issue by TalusUnheil** [andOTP/andOTP#767]
Hello everybody! I would love it if you could add the logo for "FTX" (Crypto-Exchange). https://cdn.coinranking.com/WyBm4_EzM/ftx-exchange.svg

Thanks in advance!

**Comment by ziegenberg** [comment]
**Name**: FTX
**Website**: https://ftx.com/
**Link to SVG or EPS image**: https://cdn.coinranking.com/WyBm4_EzM/ftx-exchange.svg
