### ISSUE TITLE
show password with a separate timeout, not till renew

### ISSUE THREAD

**Issue by MaDill** [andOTP/andOTP#77]
Feature request!

* **App version:** 0.3.0
* **App source:** Google Play
* **Android Version:** 7.1.1
* **Custom ROM:** stock, no root or other modifications

#### Expected result
**What is expected?**
I set the option to hide the password and need to manually tap them to show up. I suggest to show the passwords for a defined time and not only till the next period starts. For example I unhide it with 10 seconds left, I want that the next password is shown after the actual expires without tap it again. After some time, for example 30 seconds, after the last tap, the password is gotten again. A tap during the visible period, reset the timeout.

**What does happen instead?**
They will be shown till the time of the password expires and then need to tab them again. If there is only a few seconds left I have to tap twice.

**Comment by flocke** [comment]
I like the idea, I'll have to look into how to best implement that without adding to many checks for timeouts.

**Comment by flocke** [comment]
While trying to implement this I noticed that this perfectly ties in with #67.
Thanks again for suggesting it ;)

**Comment by flocke** [comment]
I already implemented it, but what do you think would be a good default timeout?
You can change it anytime in the settings, I just need a good default value.

**Comment by MaDill** [comment]
I also think 30 seconds is a goog value. Thank you.
