### ISSUE TITLE
[Feature Request] Symantec VIP Support

### ISSUE THREAD

**Issue by SpotComms** [andOTP/andOTP#78]
Symantec has this proprietary TOTP management system called Symantec VIP. It is the only option for 2FA on some services.

However there exists a somewhat actively maintained Python implementation that supports creating registration credentials and outputting a a TOTP secret that can be then imported into any standard TOTP app.
Python implementation: https://github.com/dlenski/python-vipaccess

This will probably never be implemented, but I figured I'd ask anyone in case anyone was up to the task. I'm sure it would be well appreciated by many.

There are some downsides...
- It would add network access, which might deter some people from using the app
- Symantec might not like that a convenient alternative exists

**Comment by flocke** [comment]
As you already mentioned I am not to keen on implementing this. For one the Network permissions are something I never wanted to add to andOTP. And on the other hand can you easily use python-vipaccess to register an account and then print the TOTP secret to import in andOTP (that is what I did for my PayPal account).

**Comment by flocke** [comment]
I will write a small entry in the wiki on how to use python-vipaccess to get the TOTP secret and import it in andOTP (as I did for Battle.net) and then close this issue.

**Comment by Pledkae** [comment]
Does anyone know what happens when credential expires (or does it really expire)? Output from provisioning a new credential with python-vipaccess gives "This credential expires on this date:".

Regarding PayPal mentioned above - is it necessary to define token model (VSST/VSMT)?

Thanks!

**Comment by flocke** [comment]
I just added a description to the wiki: https://github.com/andOTP/andOTP/wiki/Shared-secrets

It's based on [this](https://medium.com/@dubistkomisch/set-up-2fa-two-factor-authentication-for-paypal-with-google-authenticator-or-other-totp-client-60fee63bfa4f) post (which is also linked).

@Pledkae I don't know what will happen if it expires (or if it does at all), sorry.
