### ISSUE TITLE
[Thumbnail] Migadu

### ISSUE THREAD

**Issue by MaxwellCody** [andOTP/andOTP#787]
Migadu's mail admin system supports TOPT.

**Name**: Migadu
**Website**: https://www.migadu.com
**Link to SVG or EPS image**: https://www.migadu.com/svg/logo_bg.svg

**Comment by ziegenberg** [comment]
@MaxwellCody, there is already a thumbnail for Migadu in the app. Is this an update for a more current version?

**Comment by MaxwellCody** [comment]
> @MaxwellCody, there is already a thumbnail for Migadu in the app. Is this an update for a more current version?

Yeah, it looks like Migadu changed their logo: https://www.migadu.com/blog/redesign/

**Comment by ziegenberg** [comment]
so here's your update then :)
