### ISSUE TITLE
[Thumbnail] Charles Schwab

### ISSUE THREAD

**Issue by MaxwellCody** [andOTP/andOTP#789]
Charles Schwab's main account system supports the proprietary Symantec VIP Access TOTP implementation. Secrets from VIP Access can be dumped and used with andOTP without issue.

**Name**: Charles Schwab
**Website**: https://www.schwab.com/
**Link to SVG or EPS image**: https://upload.wikimedia.org/wikipedia/commons/4/4b/Charles_Schwab_Corporation_logo.svg

**Comment by ziegenberg** [comment]
The logo on Wikimedia commons was a mess. Kinks and edges in the letters and some were even floating. I know; it's the same version they use base64 encoded on the website. I extracted a nice version from one of their PDFs and used that one instead.
