### ISSUE TITLE
[Feature request] Autofill 

### ISSUE THREAD

**Issue by Swedneck** [andOTP/andOTP#79]
Would it be possible to implement an autofill feature like in bitwarden?

**Comment by flocke** [comment]
I'll have to do some research as I have no idea on how to implement something like this. If I decide to implement this it will take some time.

**Comment by RichyHBM** [comment]
I remember looking in to this a while back and it would require our app to have accessibility permissions (read the whole screen, which I'm not keep about) as well as having some way to link an OTP entry with a particular website. As well as that there would be no easy way of identifying a 2fa input field.

What I could see easier to accomplish is include a status bar quick tile to quickly open andOTP from other apps and a way to copy a code to the clipboard

**Comment by flocke** [comment]
After some research I think we should not implement this as well. I agree with @RichyHBM that the additional permission to read the whole screen is not really something I want in andOTP.
