### ISSUE TITLE
Can't scan qr code from image file

### ISSUE THREAD

**Issue by arol9** [andOTP/andOTP#790]
-----------------------------

#### General information

**What does happen instead?**

It's for vlc on gitlab, when I try to import it via qr code from image I get - could not find confirm qr code. I also cropped it to qr code only without any background and it didn't work. Also installed Aegis and it got imported on first try. So there is something wrong somewhere. I set Issue to private to avoid some stuff going with my account on vlc.

#### Steps to reproduce

Use screenshot to reproduce
![vlc cant](https://user-images.githubusercontent.com/80759040/111304229-3fb24080-8634-11eb-979e-e73cca4f9f46.png)

 
 * ...

**Comment by flocke** [comment]
I tested scanning the QR code with a different barcode scanner app ([Binary Eye](https://f-droid.org/packages/de.markusfisch.android.binaryeye)) and was able to reproduce this there as well.
But after I rotated the image by 90° it scanned without a problem. Could you maybe try this as well?

If that works I need to figure out what Aegis is doing differently to recognize the image without rotation.

**Comment by arol9** [comment]
true, when you rotate image it helps, to the:

right -- works
left -- fails
180 -- works
original -- fails


... scanning it with camera works without a problem.

Hopefully you can sort it out, I guess if someone tries it for the first time & gets this error, probably looks for alternative right away.

**Comment by ziegenberg** [comment]
I tested and updated `com.google.zxing:core` from version _3.3.0_ to _3.3.3_ and then to _3.4.1_. It does not work with `com.google.zxing:core:3.3.3`, but changing to `com.google.zxing:core:3.4.1` helps.

Also trying `com.google.zxing:core:3.3.3` with a `DecodeHintType.TRY_HARDER` does not help.

**Comment by ziegenberg** [comment]
I have a potential fix. Please test.
