### ISSUE TITLE
PIN unlock takes about three to five seconds each time

### ISSUE THREAD

**Issue by fredddd1** [andOTP/andOTP#796]
#### General information

* **App version:** 0.8.0
* **App source:** F-Droid
* **Android Version:** 10
* **Custom ROM:** LineageOS

#### Expected result
**What is expected?** 
Instant (<1s) unlock.

**What does happen instead?**
Takes about three to five seconds to unlock.

#### Logcat
```
I rather not due to it maybe containing sensitive information. Just want to know if this is normal.
```

#### Steps to reproduce
 Have a lock configured and unlock the app when opening it.

**Comment by flocke** [comment]
This is the currently normal behavior. The unlock speed depends on the hardware and the crypto implementation included in your Android version (I'm not sure if there are vendor specific differences here).

But in the next release there are some improvements in that regard.
