### ISSUE TITLE
How to make andOTP recognize installed PGP provider

### ISSUE THREAD

**Issue by Bios-Marcel** [andOTP/andOTP#802]
Hey,

so first of all, sorry for not using the issue template, but I am not sure if this is even a bug, it's probably a user error.
I've installed andOTP and openKeychain a while ago and haven been using andOTP happily since. I've only installed openKeychain in order to to PGP encrypted backups, since the normal aes-256-gcm encrypted backups are kinda annoying to decrypt on a plain linux installation.

However, it seems andOTP doesn't recognize that a valid PGP provider is even installed.
Is there anything I have to do? Maybe there should be a wiki entry, maybe even one that tells me I don't have to do anything, because in this case I would know whether it's a bug or not :D

Running android 10 EMUI on a Huawei device and got andOTP 0.8 and openKeychain 5.7.

If you think this is a bug, I'll make a new issue with the requested data or add it to this one, whatever you prefer.

If it's a bug, i'd happily try to make a PR to fix it :)

**Comment by flocke** [comment]
You should be able to chose OpenKeychain as "OpenPGP provider" in the settings:

![Screenshot_20210407-060416_andOTP](https://user-images.githubusercontent.com/76665/113808887-492c5580-9767-11eb-95f3-e02145fe32e5.png)

**Comment by Bios-Marcel** [comment]
Damn, I thought it's all in the backup UI and would detect the provider automatically ^^

Sorry, was being stupid. Thanks for your time.
