### ISSUE TITLE
[Thumbnail]  NordVPN / NordPass / NordLocker

### ISSUE THREAD

**Issue by Yrlish** [andOTP/andOTP#811]
**Name**:
NordVPN / NordPass / NordLocker

**Website**: 
https://nordpass.com https://nordlocker.com https://nordvpn.com

**Link to SVG or EPS image**:
https://nordsecurity.com/press-area

**Comment by ziegenberg** [comment]
As all the services of "Nord" are connected to the same NordAccount I'm going for the generalized black Nord Logo with black coloring.
