### ISSUE TITLE
[Thumbnail] Square Enix ID

### ISSUE THREAD

**Issue by Ammako** [andOTP/andOTP#816]
**Name**: Square Enix ID
**Website**: https://secure.square-enix.com/
**Link to SVG or EPS image**: There isn't really one, not officially. Something like [this](https://i.imgur.com/WhAPQxn.png) could work, if someone's able to make a clean svg for it.

They *just* added TOTP support today, so...

**Comment by krisu5** [comment]
Here's SVG for full logo: https://en.wikipedia.org/wiki/File:Square_Enix_logo.svg
Square Enix uses "E" logo has small scale logo (for favicons etc)
