### ISSUE TITLE
[Thumbnail] UptimeRobot

### ISSUE THREAD

**Issue by silviuvulcan** [andOTP/andOTP#818]
**Name**: UptimeRobot
**Website**: https://uptimerobot.com/
**Link to SVG or EPS image**: https://superbig.co/uploads/images/icons/icon-uptimerobot.svg

**Comment by krisu5** [comment]
Logo in the "Link to SVG or EPS image" section is not official one.

Logo officially is either just the green dot or green dot with text. https://uptimerobot.com/assets/images/uptimerobot-logo.svg

**Comment by ziegenberg** [comment]
This is a duplicate of #459. Therefore I will close it and transfer the updated information to #459.
