### ISSUE TITLE
[Thumbnail] Purse.io

### ISSUE THREAD

**Issue by lloydsmart** [andOTP/andOTP#820]
**Name**: Purse.io
**Website**: purse.io
**Link to SVG or EPS image**: http://www.strongvc.com/wp-content/uploads/2014/12/purse.png

Would be good to have this, but without the word underneath, just the circle.

**Comment by ziegenberg** [comment]
The provided logo is not a vector image.

**Comment by krisu5** [comment]
Here's SVG, had make it myself because they're using webfonts... Brand color taken from "loading" version of the logo (@navy: https://purse.io/styleguide.html)

[Purse.io logo.zip](https://github.com/andOTP/andOTP/files/6407680/Purse.io.logo.zip)

**Comment by lloydsmart** [comment]
Thanks krisu5.

I also reached out to Purse, who provided an SVG and permission to use it; The link is here: https://purse.io/fonts/purseicon-src/purse-logo.svg
