### ISSUE TITLE
andotp 0.9.0-beta1-play can't use openkeychain

### ISSUE THREAD

**Issue by jamesmccoy0405** [andOTP/andOTP#825]
Check if all requirements are fulfilled otherwise the issue will be closed without any comment

  * Check the [FAQ](https://github.com/andOTP/andOTP/wiki/Frequently-Asked-Questions) and search the [already reported issues](https://github.com/andOTP/andOTP/issues) before opening a new one!
  * Try again after clearing the apps data before posting (**don't forget to backup**)
  * Fill in **all** the details below
  * Record a logcat: https://goo.gl/mc71vk
  * Bug reports without logcat will be closed (I can not reproduce every bug myself and I can not fix them without logs)
  * Delete this entire info block

-----------------------------

#### General information

* **App version:andotp 0.9.0-beta1-play
* **App source:Google Play
* **Android Version:11
* **Custom ROM: lineage-18.1-20210503-nightly-mata-signed.zip

#### Expected result
**What is expected?** 
openkeychain as openPGP provider is working.
**What does happen instead?**
when openkeychain had installed, openPGP provider notes "install openkeychain via google play store", and clean app storage isn't work.
#### Logcat
[logcat.txt](https://github.com/andOTP/andOTP/files/6416030/logcat.txt)
#### Steps to reproduce
1.install openkeychain from google play;
2.install andotp from google play;
3.set password for andotp;
4.open Settings; 
5.open openPGP provider notes "install openkeychain via google play store"
6.clean andotp storage;
7.set password for andotp;
8.open Settings; 
9.open openPGP provider notes "install openkeychain via google play store"

**Comment by jamesmccoy0405** [comment]
General information

    **App version:andotp 0.9.0-beta1
    **App source:F-droid
    **Android Version:11
    **Custom ROM: lineage-18.1-20210503-nightly-mata-signed.zip

Expected result

What is expected?
openkeychain as openPGP provider is working.
What does happen instead?
when openkeychain had installed, openPGP provider notes "none, and clean app storage isn't work.
Logcat
[logcat-fdroid.txt](https://github.com/andOTP/andOTP/files/6416080/logcat-fdroid.txt)
Steps to reproduce
1.install openkeychain from google play;
2.install andotp from F-droid;
3.set password for andotp;
4.open Settings;
5.open openPGP provider notes "none"
6.clean andotp storage;
7.set password for andotp;
8.open Settings;
9.open openPGP provider notes "none"

**Comment by jamesmccoy0405** [comment]
andotp 0.8.0 from f-droid the openPGP provider is openkeychain and working.

**Comment by flocke** [comment]
Seems like Google introduced a new restriction for apps to see other apps installed on the device which prevents us from accessing OpenKeychain: https://developer.android.com/training/package-visibility

**Comment by flocke** [comment]
I added a first workaround and submitted [an issue](https://github.com/open-keychain/open-keychain/issues/2701) to the OpenPGP library andOTP uses. Hopefully it can be fixed upstream as well.

**Comment by jamesmccoy0405** [comment]
Thx
