### ISSUE TITLE
Implementation for Linux based smartphones

### ISSUE THREAD

**Issue by nesnera** [andOTP/andOTP#829]
**Describe the solution you'd like**
Be able to use andOTP at linux based mobiles e.g. [PinePhone](https://wiki.pine64.org/wiki/PinePhone#Hardware_revisions)

**Comment by flocke** [comment]
I currently barely have the time to maintain andOTP, so I won't be developing a new application myself.

But there are some Linux apps already available that support opening andOTP backup files. Maybe one of those can be adapted to support phone UIs (or supports them already). You could try this app for example: https://github.com/paolostivanin/OTPClient
