### ISSUE TITLE
[Feature request] add option to separate token into blocks

### ISSUE THREAD

**Issue by hvhaugwitz** [andOTP/andOTP#83]
To improve readability of tokens with a length >= 6 please consider to add an option to separate the token into blocks (e.g. 123456 -> 123 456 or 12345678 -> 1234 5678).

**Comment by flocke** [comment]
I was thinking about this as well because I always read the tokens in blocks of 3.
I will try to get this in for the next release (v0.3.2 as v0.3.1 is already in preparation).
