### ISSUE TITLE
[Thumbnail] Pixelfed

### ISSUE THREAD

**Issue by the7thNightmare** [andOTP/andOTP#833]
**Name**: Pixelfed
**Website**: Pixelfed.org
**Link to SVG or EPS image**: https://raw.githubusercontent.com/pixelfed/pixelfed/bfe6969dae0bfe87710f49deefdf02c5b230898c/public/img/pixelfed-icon-color.svg (and the PNG: https://raw.githubusercontent.com/pixelfed/pixelfed/dev/public/img/pixelfed-icon-color.png)

**Comment by ziegenberg** [comment]
Duplicate of #452.
