### ISSUE TITLE
Send OTP code via bluetooth as a keyboard function

### ISSUE THREAD

**Issue by jmiezitis** [andOTP/andOTP#840]
We use OTP for ssh connections to many different servers.  By connecting the android device to my laptop using https://play.google.com/store/apps/details?id=io.appground.blek I can copy the text from andotp paste it into the bluetooth keyboard app and have the text appear on my laptop terminal session.
It would be awesome if andotp was able to connect direct to the laptop eliminating the need for the bluetooth keyboard app and subsequent steps required on the android device.

**Comment by flocke** [comment]
I don't think this should be implemented in andOTP. We would need to implement an entire Bluetooth keyboard inside andOTP for this to work directly, which is something that has no place in a simple 2FA app.

You will always need a second app to handle the data transfer, but in the new version you can share the OTP token directly with that app: https://github.com/andOTP/andOTP/pull/693

**Comment by jmiezitis** [comment]
That would work for me.
