### ISSUE TITLE
Copy and switch to previous app

### ISSUE THREAD

**Issue by Akhilesh-T** [andOTP/andOTP#845]
Whenever I copy an OTP, I have to manually switch to the app demanding it.

For instance, the shortest way to enter an OTP while logging into Amazon app is
1. copy the **OTP**,
2. go to **recent apps**,
3. open **Amazon**.

It would be awesome if the previous app could open automatically after I single tap or double tap the OTP.

[Sorry if someone already requested this feature]

**Comment by flocke** [comment]
This was already requested in #584. Currently there seems to be no way to do this since Android does not allow normal apps access to the previous apps.

**Comment by Akhilesh-T** [comment]
That's bad 🙁

I'm using an app called **One Hand Operation +** which can switch between apps with a shortcut. See if it can help.

- https://play.google.com/store/apps/details?id=com.samsung.android.sidegesturepad&hl=en_IN&gl=US
- https://www.apkmirror.com/apk/samsung-electronics-co-ltd/one-hand-operation/
- https://galaxystore.samsung.com/detail/com.samsung.android.sidegesturepad

Thanks!
