### ISSUE TITLE
[Feature Request] Add git support to push and pull encrpyted backup from remote repository.

### ISSUE THREAD

**Issue by akhilkpdasan** [andOTP/andOTP#86]

**Comment by RichyHBM** [comment]
If you need git support you should use another app with andOTP, I don't think andOTP should include git support directly

**Comment by flocke** [comment]
I agree with @RichyHBM. I already decided against supporting cloud storage for backups, which basically comes down to the same thing.

The main reason is that I want to keep andOTP as light and simple as possible, which includes not adding features that can be easily achieved with other apps. You should use a third-party app to upload the backups to git.
