### ISSUE TITLE
insecure ?

### ISSUE THREAD

**Issue by araripi1** [andOTP/andOTP#870]
https://www.immuniweb.com/mobile/org.shadowice.flocke.andotp/4qvKPIyn/
![Capturar](https://user-images.githubusercontent.com/76633999/124384682-cf91fe00-dca8-11eb-8068-f25f7dc6ff8b.PNG)

**Comment by flocke** [comment]
1. The "weak encryption" detected here is only used for key wrapping when using the Android KeyStore. And even then the result is only stored in the applications private data files, which an attacker would need root access to get a hold of. So the impact of this is very limited, but it will be changed at some point.

2. This just means the data **can** be backed up by Androids internal backup function. For that to happen the user still has to enable Android Backup in the phone settings. The backup only includes the encrypted data, no unencrypted secrets are ever backed up.
