### ISSUE TITLE
Dark Thumbnails (nearly) invisible black theme

### ISSUE THREAD

**Issue by SuperVirus** [andOTP/andOTP#88]
#### General information

* App version: 0.3.1
* App source: F-Droid
* Android Version: 7.1.2
* Custom ROM: LineageOS 14.1-20171215

#### Problem description
All dark thumbnails are (nearly) invisible if the black theme is selected.

These thumbnails are affected:
* Amazon
* AWS
* AngelList
* Apple
* Bitstamp
* GitHub
* LastPass
* Steam

#### Steps to reproduce
* Switch andOTP to the black theme
* Choose one of the thumbnails listed above

#### Possible solution/workaround
1. Adding an background to all thumbnails
2. Adding an outline around each logo with transparent background
3. Placing an light background behind the/some thumbnails in the black and dark theme
4. Including different thumbnail for dark/black theme, where needed

**Comment by RichyHBM** [comment]
I can take a look at this tonight, I think adding an outline or a background when using a dark theme should be easy enough.
If there are any other ideas as to how best to accomplish this do mention

**Comment by flocke** [comment]
I think you should test both (outline and background) and see which one looks better.
I'm against different icons for the dark theme just because it would increase the size of the APK again.

**Comment by flocke** [comment]
@SuperVirus @RichyHBM I got an updated proposal on how this could look for a dark theme in PR #90, I would love your input.
