### ISSUE TITLE
Setting "Tap to reveal" missing

### ISSUE THREAD

**Issue by limes007** [andOTP/andOTP#885]
#### General information

* **App version:** 0.9.0.1-play
* **App source:** Google Play
* **Android Version:** 11
* **Custom ROM:** Stock OnePlus

#### Expected result
**What is expected?** 
Setting "Tap to reveal" is available as shown in the screen shots

**What does happen instead?**
Setting "Tap to reveal" is not available, all tokens are visible always

**Comment by flocke** [comment]
The setting has moved, you now have to set the "Single-tap" or "Double-tap" setting to "Reveal/Hide":

![Screenshot_20210806-161351_andOTP_1](https://user-images.githubusercontent.com/76665/128523884-0a3cc891-05b1-4100-a49d-caf9bc313642.png)

**Comment by limes007** [comment]
Thank you, great feature. But not necessarily intuitive.

**Comment by flocke** [comment]
Yes, it's not really intuitive currently. The entire settings screen needs a rework sooner or later because there are some deprecated APIs used.
