### ISSUE TITLE
LinusTechTips (LTT)

### ISSUE THREAD

**Issue by szabiakanich** [andOTP/andOTP#916]
**Name**: Linus Tech Tips (LTT)
**Website**: https://linustechtips.com/
**Link to SVG or EPS image**: https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/2018_Linus_Tech_Tips_logo.svg/512px-2018_Linus_Tech_Tips_logo.svg.png

**Comment by Monklite** [comment]
https://github.com/andOTP/andOTP/issues/850

This currently exists already
