### ISSUE TITLE
3 dots menu is hidden behind "+" button

### ISSUE THREAD

**Issue by MaDill** [andOTP/andOTP#95]
when add more accounts and the accounts are just enough to fit the screen and you can not scroll up/down, then the 3 dot menu of the last account is hidden behind the "+" button. Other apps handle this with a "jumping" add button.

**Comment by RichyHBM** [comment]
Can you link to an app with this "jumping" thing?

**Comment by flocke** [comment]
As @RichyHBM said, could you provide an example of an app that is doing this? I tried to figure out how to handle this for a while now.

**Comment by MaDill** [comment]
On Macrodroid https://play.google.com/store/apps/details?id=com.arlosoft.macrodroid the "check and save" button is jumping. But it is not OS.

**Comment by flocke** [comment]
The problem with a jumping Add button is that it may block the OTP token (if we have it jump in middle for example). I was thinking of adding a kind of padding at the bottom if the list so if you scroll all the way down the button is just displayed over a blank space.

**Comment by flocke** [comment]
I will experiment a bit in the new year. Maybe I can come up with something nice.

**Comment by RichyHBM** [comment]
Something I have seen in other apps is a dragable fab button, so the user can drag the button to either side or even to the middle.

I should be able to make a PR hopefully tomorrow with this for you to try out if you want

**Comment by flocke** [comment]
Sure, if you want I would be happy about a PR. Tomorrow is more than fine, I won't be home for the next 2 days, after that I will review it.

**Comment by RichyHBM** [comment]
I got the fab moving and snapping to either left, right or the centre depending on where you let go. Still need to make the mini fabs that pop up move with it as they still must pop up on the right.

That said the more I try it out the more I'm siding with just having extra padding on the bottom as the moving fab just isn't very intuitive

**Comment by MaDill** [comment]
the moving "+" was just a suggestion which I see on another app. If you think it is not intuitive, what do you think to put the "+" to the top tool bar next to the sorting and search and kick away the other button?

**Comment by alexanderadam** [comment]
A probable easy fix would be to enable more scrolling tolerance.
So if a user could scroll and stay into the empty space access would be possible again.

**Comment by flocke** [comment]
I tried the PR by @RichyHBM and I also don't find the moving FAB very intuitive. I got it working with a bit of extra padding at the bottom looking something like this if you scroll to the bottom:

![screenshot_andotp_20180111-154640](https://user-images.githubusercontent.com/76665/34831399-2571ef34-f6e7-11e7-8038-0a665ff7c695.png)

If you are not at the bottom the padding disappears and it's the normal list again.
