### ISSUE TITLE
PlayStore link is broken

### ISSUE THREAD

**Issue by ggruening** [andOTP/andOTP#954]
-----------------------------

#### General information

* **App version:** current
* **App source:** there is no source, this IS the problem indeed...
* **Android Version:** any
* **Custom ROM:**

#### Expected result
**What is expected?** 
The download link is working.

**What does happen instead?**
The provided link to the app in Google Play Store (https://play.google.com/store/apps/details?id=org.shadowice.flocke.andotp) is broken. There is a "not found" error instead. In addition, the app cannot be found in playstore using the search function.

#### Steps to reproduce
Use the Link above.

**Comment by flocke** [comment]
It has been remove from the PlayStore due to an error in the review process. I have submitted an appeal and am currently waiting for a response.

**Comment by ggruening** [comment]
Ok, thanks for all your work :-)

**Comment by hayalci** [comment]
Can I suggest keeping the issue open until the app is reinstated? 

Otherwise people will keep filing bugs thinking it's not noticed.

**Comment by tomekit** [comment]
This is still going. Out of interest what did Google exactly say @flocke? 
It is pretty concerning that such important app can be taken down like this.

In my case I am linking to `andOTP` project when suggesting 2FA apps on Android and someone complained that it no longer works.

**Comment by soulhunter** [comment]
Hi!

I have heard that google can be a pain on all of this.  Reaching through many methods, specially public ones might be needed.  Just look what happened to the Terraria creator (for instance).

Ildefonso

**Comment by averon420** [comment]
yeah, its a pain. I also wonder why they took it off the store.

**Comment by flocke** [comment]
They had some trouble during the review because they didn't read the instructions.

During the setup there is a screen where you can chose a password for the database. Because of the password field they thought that this was a login screen. They asked me to provide them credentials for this "login" so they can finish their review.

I submitted an appeal, explaining what the screen actually does. But I haven't heard back from them yet.

**Comment by averon420** [comment]
> They had some trouble during the review because they didn't read the instructions.
> 
> During the setup there is a screen where you can chose a password for the database. Because of the password field they thought that this was a login screen. They asked me to provide them credentials for this "login" so they can finish their review.
> 
> I submitted an appeal, explaining what the screen actually does. But I haven't heard back from them yet.

Thanks for the info. Really a shame they take so long. I like your app.

**Comment by lessload** [comment]
Try to create app free version and pro version with 0.9$ like [Simple Gallery Pro](https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery.pro). Google may reply you much faster haha.

**Comment by ericcurtin** [comment]
This can also be downloaded on F-Droid app store in you download and install that. Might be at least a temporary solution or maybe even a long-term one to sponsor open source efforts. Nice to have on two app stores for redundancy though, for cases just like this.

**Comment by k-obrien** [comment]
Might be worth updating the README just to hide/remove the Google Play link and adding something to the effect that it's still being actively developed and to please use alternative installation sources while the appeal process is under way. The app is excellent (thank you!) so having to install via F-Droid, for example, is no barrier to me as long as I know it's still supported.

**Comment by kacnje** [comment]
> They had some trouble during the review because they didn't read the instructions.
> 
> During the setup there is a screen where you can chose a password for the database. Because of the password field they thought that this was a login screen. They asked me to provide them credentials for this "login" so they can finish their review.
> 
> I submitted an appeal, explaining what the screen actually does. But I haven't heard back from them yet.

As usual with big companies. No reply or pointless answers. 
Sometimes works if you prepare a new version and send it again.

**Comment by timwoj** [comment]
Looks fixed now! https://play.google.com/store/apps/details?id=org.shadowice.flocke.andotp actually goes to the page for the app.
