### ISSUE TITLE
scroll description

### ISSUE THREAD

**Issue by MaDill** [andOTP/andOTP#96]
When the description is too longer, it is cut by ... depending on screen size. Maybe the text can slowly scroll to be able to read it. I have the description like <site, url: account>. The important information to decide which account of a site I have to use is in the end. I could change the description, but the account name I use on more sites and then the site information is hidden behind the ...

**Comment by flocke** [comment]
As of version 0.3.0 that is already an option. You should have an option named "Scroll label" (at least if your app language is English) in the settings.

**Comment by MaDill** [comment]
found it. thank you
