### ISSUE TITLE
[Thumbnail] Yahoo

### ISSUE THREAD

**Issue by ChaoticHolon** [andOTP/andOTP#962]
**Name**: Yahoo
**Website**:  login.yahoo.com; yahoo.com; mail.yahoo.com
**Link to SVG or EPS image**: https://uxwing.com/wp-content/themes/uxwing/download/10-brands-and-social-media/yahoo.svg

Yahoo finally added TOTP/Authenticator support! The QR code generated by the site doesn't seem to scan properly (in anything, lol; whoops) but manually putting the secret in works just fine, there's just no Yahoo logo available in the app.

**Comment by flocke** [comment]
Duplicate of #882
