### ISSUE TITLE
Add ability to show seed from within andOTP

### ISSUE THREAD

**Issue by saberblaze** [andOTP/andOTP#99]
Hello, would it be possible to add an option to show the seed from within the app? Maybe with a password prompt before showing them. I use WinAuth on Windows and usually add seeds to both at the same time when I'm setting up 2 factor authorization for a website. However if I am away from my computer and set up the authenticator on andOTP only I would have to export a plain text backup to be able to see and copy the seed manually into WinAuth if I'm not mistaken.

**Comment by flocke** [comment]
I'm not against this, but wouldn't exporting a plain-text backup be easier? You could copy it to your PC and copy-paste the seed to WinAuth instead of having to type the Base32 string manually.

**Comment by saberblaze** [comment]
You're right, I guess my initial concern was storing it unencrypted when exporting but it's probably not that big a deal as long as it's properly wiped/shredded.

**Comment by flocke** [comment]
Exactly, that's what I do when I need the secrets on my PC for some reason.
I export it PGP-encrypted, copy it to my PC, decrypt it using gnupg (only dumping the plain text to STDOUT so the secrets are never actually written to my disk) and copy-paste it wherever I need it.
But using plain-text backups and properly wiping the file afterwards should also work.

**Comment by flocke** [comment]
I'm still not sure if I should implement this as plain-text backups should easily do the trick.
Maybe @RichyHBM can chime in here and tell me his opinion on this ...

**Comment by RichyHBM** [comment]
My gut feeling is that it isn't needed, you can still get this data from the backups

**Comment by flocke** [comment]
That's basically the way I feel as well. So I won't be implementing this, sorry.
